### ISSUE TITLE
Can't type in Terminus

### ISSUE THREAD

**Issue by omipenguin** [Eugeny/tabby#2951]
I'm facing one issue which is popping every now and then , while im typing it doesn't reflect on Terminal. I have to close the session and and then relaunch it then it start working.

![image](https://user-images.githubusercontent.com/8554876/91656852-dec28100-eac4-11ea-8714-37bd2884f496.png)

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by agarmu** [comment]
I too have this issue.

**Comment by tujh-rf** [comment]
+1

`
/Applications/Terminus.app/Contents/Resources/app.asar/dist/[object%20Module]:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/Applications/Terminus.app/Contents/Resources/builtin-plugins/terminus-core/dist/index.js:7574 [ssh] Using user's default private key
(16) xterm.js:1 Unable to preventDefault inside passive event listener invocation.
  t._bubbleScroll | @ | xterm.js:1
...
/Applications/Terminus.app/Contents/Resources/builtin-plugins/terminus-terminal/dist/index.js:13825 
Uncaught TypeError: Cannot read property 'runAsAdministrator' of undefined
    at TerminalService.openTabWithOptions (/Applications/Terminus.app/Contents/Resources/builtin-plugins/terminus-terminal/dist/index.js:13825)
    at /Applications/Terminus.app/Contents/Resources/builtin-plugins/terminus-terminal/dist/index.js:15221
    at ZoneDelegate.invoke (/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/zone.js/dist/zone.js:386)
    at Object.onInvoke (/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/@angular/core/bundles/core.umd.js:28264)
    at ZoneDelegate.invoke (/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/zone.js/dist/zone.js:385)
    at Zone.run (/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/zone.js/dist/zone.js:143)
    at NgZone.run (/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/@angular/core/bundles/core.umd.js:28159)
    at click (/Applications/Terminus.app/Contents/Resources/builtin-plugins/terminus-terminal/dist/index.js:15220)
    at CallbacksRegistry.apply (/Applications/Terminus.app/Contents/Resources/app.asar/dist/electron/js2c/renderer_init.js:2549)
    at /Applications/Terminus.app/Contents/Resources/app.asar/dist/electron/js2c/renderer_init.js:1469
    at EventEmitter.<anonymous> (/Applications/Terminus.app/Contents/Resources/app.asar/dist/electron/js2c/renderer_init.js:1449)
    at EventEmitter.emit (/Applications/Terminus.app/Contents/Resources/app.asar/dist/events.js:210)
    at Object.onMessage (/Applications/Terminus.app/Contents/Resources/app.asar/dist/electron/js2c/renderer_init.js:2204)
/Applications/Terminus.app/Contents/Resources/builtin-plugins/terminus-core/dist/index.js:7475
  [terminal] Starting profile bash 
  Object
  name: "bash"
  shell: "binbash"
  icon: undefined
  sessionOptions:
  command: "/bin/bash"
  args: ["-l"]
  env: {}
  __proto__: Object
  isBuiltin: true
  __proto__: Object
/Applications/Terminus.app/Contents/Resources/builtin-plugins/terminus-core/dist/index.js:7475
  [terminal] Using session options: 
  Object
  command: "/bin/bash"
  args: ["-l"]
  env: {}
  pauseAfterExit: undefined
  cwd: undefined
  __proto__: Object
`

**Comment by tujh-rf** [comment]
```
/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/@angular/core/bundles/core.umd.js:4302 ERROR Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (/Applications/Terminus.app/Contents/Resources/app.asar/dist/_stream_writable.js:253)
    at Channel.Writable.write (/Applications/Terminus.app/Contents/Resources/app.asar/dist/_stream_writable.js:302)
    at SSHSession.write (/Applications/Terminus.app/Contents/Resources/builtin-plugins/terminus-ssh/dist/index.js:2037)
    at SSHTabComponent.sendInput (/Applications/Terminus.app/Contents/Resources/builtin-plugins/terminus-terminal/dist/index.js:9035)
    at SafeSubscriber._next (/Applications/Terminus.app/Contents/Resources/builtin-plugins/terminus-terminal/dist/index.js:9234)
    at SafeSubscriber.__tryOrUnsub (/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/rxjs/internal/Subscriber.js:205)
    at SafeSubscriber.next (/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/rxjs/internal/Subscriber.js:143)
    at Subscriber._next (/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/rxjs/internal/Subscriber.js:89)
    at Subscriber.next (/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/rxjs/internal/Subscriber.js:66)
    at Subject.next (/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/rxjs/internal/Subject.js:60)
    at /Applications/Terminus.app/Contents/Resources/builtin-plugins/terminus-terminal/dist/index.js:12456
    at e.fire (/Applications/Terminus.app/Contents/Resources/builtin-plugins/terminus-terminal/dist/index.js:70400)
    at /Applications/Terminus.app/Contents/Resources/builtin-plugins/terminus-terminal/dist/index.js:70400
    at e.fire (/Applications/Terminus.app/Contents/Resources/builtin-plugins/terminus-terminal/dist/index.js:70400)
    at t.triggerDataEvent (/Applications/Terminus.app/Contents/Resources/builtin-plugins/terminus-terminal/dist/index.js:70400)
    at t._keyDown (/Applications/Terminus.app/Contents/Resources/builtin-plugins/terminus-terminal/dist/index.js:70400)
    at HTMLTextAreaElement.<anonymous> (/Applications/Terminus.app/Contents/Resources/builtin-plugins/terminus-terminal/dist/index.js:70400)
    at ZoneDelegate.invokeTask (/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/zone.js/dist/zone.js:421)
    at Object.onInvokeTask (/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/@angular/core/bundles/core.umd.js:28252)
    at ZoneDelegate.invokeTask (/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/zone.js/dist/zone.js:420)
    at Zone.runTask (/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/zone.js/dist/zone.js:188)
    at ZoneTask.invokeTask [as invoke] (/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/zone.js/dist/zone.js:503)
    at invokeTask (/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/zone.js/dist/zone.js:1671)
    at HTMLTextAreaElement.globalZoneAwareCaptureCallback (/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/zone.js/dist/zone.js:1729)
    at HTMLTextAreaElement.sentryWrapped (/Applications/Terminus.app/Contents/Resources/app.asar/dist/sentry.js:1118)
```

**Comment by oktayaa** [comment]
I have this issue when an SSH session closes (why does it close so much I don't know) and I have to reconnect. I think it happens more in split window.

**Comment by edgarsendernet** [comment]
Same issue (terminal stops accepting input after SSH connection dies):
```
Error: Uncaught (in promise): Error: Failed to send data to channel
Error: Failed to send data to channel
    at resolvePromise (zone.js:1193:31)
    at zone.js:1100:17
    at zone.js:1116:33
    at rejected (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/russh/lib/channel.js:6:89)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:127:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:171:47)
    at drainMicroTaskQueue (zone.js:581:35)
```
