### ISSUE TITLE
Wsl.exe cannot be started as a configuration

### ISSUE THREAD

**Issue by Spinestars** [Eugeny/tabby#3738]
When I set WSL up as the default startup, it didn't work.
But I can boot it in PowerShell.
The screenshot is as follows:

![image](https://user-images.githubusercontent.com/7272900/115987975-18af3d00-a5ea-11eb-9225-1d4573a411ef.png)
![image](https://user-images.githubusercontent.com/7272900/115988017-4b593580-a5ea-11eb-843f-4c0b3139f90e.png)
![image](https://user-images.githubusercontent.com/7272900/115988045-6cba2180-a5ea-11eb-9fdd-4128aab43ca7.png)

**Comment by Spinestars** [comment]
terminus version: 1.0.137

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by Spinestars** [comment]
C:\Users\aaa103439@h…es\core.umd.js:6479 ERROR Error: Uncaught (in promise): Error: Can not find Squirrel
Error: Can not find Squirrel
    at AutoUpdater.method [as checkForUpdates] (electron/js2c/browser_init.js:17:1405)
    at handler (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@electron\remote\dist\src\main\server.js:454:64)
    at IpcMainImpl.<anonymous> (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@electron\remote\dist\src\main\server.js:313:27)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10351)
    at Object.emit (events.js:315:20)
    at Object.apply [as emit] (domain.js:467:12)
    at Object.n.emit (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@sentry\electron\dist\main\integrations\electron.js:66:25)
    at resolvePromise (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1255:35)
    at resolvePromise (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1209:21)
    at C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1321:21
    at ZoneDelegate.invokeTask (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:434:35)
    at Object.onInvokeTask (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29190:37)
    at ZoneDelegate.invokeTask (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:433:64)
    at Zone.runTask (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:205:51)
    at drainMicroTaskQueue (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:620:39)

**Comment by Spinestars** [comment]
C:\Users\aaa103439@h…\dist\index.js:6578 Error: Failed to read PROCESS_BASIC_INFORMATION.PebBaseAddress
    at getWorkingDirectoryFromPID (C:\Users\aaa103439@h…rectory\index.js:25)
    at Session.<anonymous> (C:\Users\aaa103439@h…\dist\index.js:6575)
    at Generator.next (<anonymous>)
    at C:\Users\aaa103439@h…\dist\index.js:1696
    at new ZoneAwarePromise (C:\Users\aaa103439@h…s\dist\zone.js:1340)
    at __awaiter (C:\Users\aaa103439@h…\dist\index.js:1692)
    at Session.getWorkingDirectory (C:\Users\aaa103439@h…\dist\index.js:6566)
    at Session.<anonymous> (C:\Users\aaa103439@h…\dist\index.js:6450)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\aaa103439@h…\dist\index.js:1693)
    at ZoneDelegate.invoke (C:\Users\aaa103439@h…js\dist\zone.js:400)
    at Object.onInvoke (C:\Users\aaa103439@h…s\core.umd.js:29203)
    at ZoneDelegate.invoke (C:\Users\aaa103439@h…js\dist\zone.js:399)
    at Zone.run (C:\Users\aaa103439@h…js\dist\zone.js:160)
    at C:\Users\aaa103439@h…s\dist\zone.js:1318
    at ZoneDelegate.invokeTask (C:\Users\aaa103439@h…js\dist\zone.js:434)
    at Object.onInvokeTask (C:\Users\aaa103439@h…s\core.umd.js:29190)
    at ZoneDelegate.invokeTask (C:\Users\aaa103439@h…js\dist\zone.js:433)
    at Zone.runTask (C:\Users\aaa103439@h…js\dist\zone.js:205)
    at drainMicroTaskQueue (C:\Users\aaa103439@h…js\dist\zone.js:620)

**Comment by Spinestars** [comment]
C:\Users\aaa103439@h…es\core.umd.js:6479 ERROR Error: Uncaught (in promise): Error: Can not find Squirrel
Error: Can not find Squirrel
    at AutoUpdater.method [as checkForUpdates] (electron/js2c/browser_init.js:17:1405)
    at handler (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@electron\remote\dist\src\main\server.js:454:64)
    at IpcMainImpl.<anonymous> (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@electron\remote\dist\src\main\server.js:313:27)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10351)
    at Object.emit (events.js:315:20)
    at Object.apply [as emit] (domain.js:467:12)
    at Object.n.emit (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@sentry\electron\dist\main\integrations\electron.js:66:25)
    at resolvePromise (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1255:35)
    at resolvePromise (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1209:21)
    at C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1321:21
    at ZoneDelegate.invokeTask (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:434:35)
    at Object.onInvokeTask (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29190:37)
    at ZoneDelegate.invokeTask (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:433:64)
    at Zone.runTask (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:205:51)
    at drainMicroTaskQueue (C:\Users\aaa103439@hotmail.com\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:620:39)

**Comment by Spinestars** [comment]
GET file:///C:/Users/aaa103439@hotmail.com/AppData/Local/Programs/Terminus/resources/app.asar/dist/[object%20Module] net::ERR_FILE_NOT_FOUND

**Comment by adrian-dinu** [comment]
I am having the same issue and errors in 139

**Comment by Eugeny** [comment]
Figured it out - wsl.exe is just exiting. You should enter separate arguments as separate items: 
![image](https://user-images.githubusercontent.com/161476/124646143-928a5f00-de94-11eb-98f4-ecae168b8382.png)
