### ISSUE TITLE
Check for updates error

### ISSUE THREAD

**Issue by baek-sang** [Eugeny/tabby#4031]
Terminus 1.0.139/1.0.140
Windows 10 20H2(19042.1052)

![ch2](https://user-images.githubusercontent.com/69100154/122865682-bb253b80-d361-11eb-84b1-34fec25cffd5.png)

```
C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:9999 [updater] Error: Update URL is not set
    at AutoUpdater.method [as checkForUpdates] (electron/js2c/browser_init.js:17:1456)
    at handler (C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@electron\remote\dist\src\main\server.js:454:64)
    at IpcMainImpl.<anonymous> (C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@electron\remote\dist\src\main\server.js:313:27)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10099)
    at Object.emit (events.js:315:20)
    at Object.apply [as emit] (domain.js:467:12)
    at Object.n.emit (C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@sentry\electron\dist\main\integrations\electron.js:66:25)
doLog @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:9999
doLog @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-electron\dist\index.js:22050
error @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:9991
(anonymous) @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-electron\dist\index.js:22097
apply @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\callbacks-registry.js:54
(anonymous) @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:338
(anonymous) @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:320
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:93
C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:6795 ERROR Error: Uncaught (in promise): Error: Update URL is not set
Error: Update URL is not set
    at AutoUpdater.method [as checkForUpdates] (electron/js2c/browser_init.js:17:1456)
    at handler (C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@electron\remote\dist\src\main\server.js:454:64)
    at IpcMainImpl.<anonymous> (C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@electron\remote\dist\src\main\server.js:313:27)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10099)
    at Object.emit (events.js:315:20)
    at Object.apply [as emit] (domain.js:467:12)
    at Object.n.emit (C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@sentry\electron\dist\main\integrations\electron.js:66:25)
    at resolvePromise (C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1255:35)
    at C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1162:21
    at rejected (C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-settings\dist\index.js:3450:89)
    at ZoneDelegate.invoke (C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:400:30)
    at Object.onInvoke (C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29340:37)
    at ZoneDelegate.invoke (C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:399:56)
    at Zone.run (C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:160:47)
    at C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1318:38
    at ZoneDelegate.invokeTask (C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:434:35)
    at Object.onInvokeTask (C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29327:37)
    at ZoneDelegate.invokeTask (C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:433:64)
    at Zone.runTask (C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:205:51)
    at drainMicroTaskQueue (C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:620:39)
defaultErrorLogger @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:6795
ErrorHandler.handleError @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:6843
next @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29951
(anonymous) @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\dist\cjs\internal\Subscriber.js:160
Subscriber._next @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\dist\cjs\internal\Subscriber.js:100
Subscriber.next @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\dist\cjs\internal\Subscriber.js:71
Subject.next @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\dist\cjs\internal\Subject.js:63
EventEmitter_.emit @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:26622
(anonymous) @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29366
ZoneDelegate.invoke @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:400
Zone.run @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:160
NgZone.runOutsideAngular @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29238
onHandleError @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29366
ZoneDelegate.handleError @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:404
Zone.runGuarded @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:174
_loop_2 @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1113
api.microtaskDrainDone @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1125
drainMicroTaskQueue @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:627
Promise.then (async)
scheduleMicroTask @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:603
ZoneDelegate.scheduleTask @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:424
onScheduleTask @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:311
ZoneDelegate.scheduleTask @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:414
Zone.scheduleTask @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:248
Zone.scheduleMicroTask @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:268
scheduleResolveOrReject @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1308
resolvePromise @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1246
(anonymous) @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1162
onError @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-electron\dist\index.js:22135
apply @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\callbacks-registry.js:54
(anonymous) @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:338
(anonymous) @ C:\Users\Administrator\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:320
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:93

```

**Comment by baek-sang** [comment]
@Eugeny Any update? Alpha 150 same issue.

![cfu](https://user-images.githubusercontent.com/69100154/127875508-a132e477-d7db-489c-92d5-2a8b921d2c47.png)

```
C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:16803 [updater] Error: Update URL is not set
    at AutoUpdater.method [as checkForUpdates] (electron/js2c/browser_init.js:17:1456)
    at handler (C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\app.asar\dist\webpack:\tabby\node_modules\@electron\remote\dist\src\main\server.js:454:64)
    at IpcMainImpl.<anonymous> (C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\app.asar\dist\webpack:\tabby\node_modules\@electron\remote\dist\src\main\server.js:313:27)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10099)
    at Object.emit (events.js:315:20)
    at Object.apply [as emit] (domain.js:467:12)
    at Object.n.emit (C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\app.asar\dist\webpack:\tabby\node_modules\@sentry\electron\dist\main\integrations\electron.js:63:25)
doLog @ C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:16803
doLog @ C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:22201
error @ C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:16795
(anonymous) @ C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:22248
apply @ C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\callbacks-registry.js:54
(anonymous) @ C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:345
(anonymous) @ C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:327
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:93
core.js:6456 ERROR Error: Uncaught (in promise): Error: Update URL is not set
Error: Update URL is not set
    at AutoUpdater.method [as checkForUpdates] (electron/js2c/browser_init.js:17:1456)
    at handler (C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\app.asar\dist\webpack:\tabby\node_modules\@electron\remote\dist\src\main\server.js:454:64)
    at IpcMainImpl.<anonymous> (C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\app.asar\dist\webpack:\tabby\node_modules\@electron\remote\dist\src\main\server.js:313:27)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10099)
    at Object.emit (events.js:315:20)
    at Object.apply [as emit] (domain.js:467:12)
    at Object.n.emit (C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\app.asar\dist\webpack:\tabby\node_modules\@sentry\electron\dist\main\integrations\electron.js:63:25)
    at resolvePromise (file:///C:/Users/Administrator/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:116754:31)
    at file:///C:/Users/Administrator/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:116661:17
    at rejected (C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-settings\dist\index.js:8759:89)
    at ZoneDelegate.invoke (file:///C:/Users/Administrator/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:115913:26)
    at Object.onInvoke (file:///C:/Users/Administrator/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:78446:33)
    at ZoneDelegate.invoke (file:///C:/Users/Administrator/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:115912:52)
    at Zone.run (file:///C:/Users/Administrator/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:115675:43)
    at file:///C:/Users/Administrator/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:116817:36
    at ZoneDelegate.invokeTask (file:///C:/Users/Administrator/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:115947:31)
    at Object.onInvokeTask (file:///C:/Users/Administrator/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:78433:33)
    at ZoneDelegate.invokeTask (file:///C:/Users/Administrator/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:115946:60)
    at Zone.runTask (file:///C:/Users/Administrator/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:115719:47)
    at drainMicroTaskQueue (file:///C:/Users/Administrator/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:116123:35)
defaultErrorLogger @ core.js:6456
handleError @ core.js:6504
next @ core.js:29269
(anonymous) @ Subscriber.js:161
__webpack_modules__.85125.Subscriber._next @ Subscriber.js:101
__webpack_modules__.85125.Subscriber.next @ Subscriber.js:72
(anonymous) @ Subject.js:66
errorContext @ errorContext.js:22
__webpack_modules__.63032.Subject.next @ Subject.js:58
emit @ core.js:25946
(anonymous) @ core.js:28692
invoke @ zone.js:372
run @ zone.js:134
runOutsideAngular @ core.js:28565
onHandleError @ core.js:28692
handleError @ zone.js:376
runGuarded @ zone.js:147
api.microtaskDrainDone @ zone.js:1074
drainMicroTaskQueue @ zone.js:589
Promise.then (async)
scheduleMicroTask @ zone.js:565
scheduleTask @ zone.js:396
onScheduleTask @ zone.js:283
scheduleTask @ zone.js:386
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1266
resolvePromise @ zone.js:1204
(anonymous) @ zone.js:1120
onError @ C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:22286
apply @ C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\callbacks-registry.js:54
(anonymous) @ C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:345
(anonymous) @ C:\Users\Administrator\AppData\Local\Programs\Tabby\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:327
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:93
```
![cfu2](https://user-images.githubusercontent.com/69100154/127875685-0777e138-dcba-425b-bc9c-9dd6d6626d6b.png)

**Comment by Eugeny** [comment]
Still unable to reproduce. Are you using the installer or the portable version?

**Comment by baek-sang** [comment]
Using installer.
