### ISSUE TITLE
A blank window appears when running

### ISSUE THREAD

**Issue by nihanbiao** [Eugeny/tabby#4354]
Version: 1.0.151
Platform: macOS 11.5

Add serial port profile at first time 
but can not connect
then opening with a blank window every time
![image](https://user-images.githubusercontent.com/84727428/128297204-05b51790-5be9-488c-bc6b-ef3eb108c164.png)

**Comment by codepope** [comment]
Seem to be seeing a similar issue here: Open serial terminal and it whites out.... Move the window and it crashes out: Console log below. 

```
bby
(node:17823) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Tabby Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
(node:17823) Electron: Loading non-context-aware native module in renderer: '/var/folders/9c/v839zhb10kg6nqwj61fbpnd80000gn/T/.org.tabby.sGrpWD'. This is deprecated, see https://github.com/electron/electron/issues/18397.
Checking for update
dyld: lazy symbol binding failed: Symbol not found: __ZN2v86Object18InternalFieldCountEv
  Referenced from: /var/folders/9c/v839zhb10kg6nqwj61fbpnd80000gn/T/.org.tabby.sGrpWD
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v86Object18InternalFieldCountEv
  Referenced from: /var/folders/9c/v839zhb10kg6nqwj61fbpnd80000gn/T/.org.tabby.sGrpWD
  Expected in: flat namespace

[0905/144339.724923:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffedfe41000, 0x2000): (os/kern) invalid address (1)
Update for version 1.0.156 is not available (latest version: 1.0.156, downgrade is disallowed).
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: index.js:30060:26
Remote event names: update-not-available
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: bundle.js:116716:26
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
sendToFrame() failed: Error: Render frame was disposed before WebFrameMain could be accessed
Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (electron/js2c/browser_init.js:165:413)
    at Object.send (electron/js2c/browser_init.js:161:2471)
    at t.Window.send (/Users/dj/Downloads/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/lib/window.ts:194:33)
    at apply (/Users/dj/Downloads/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/lib/window.ts:264:18)
    at Object.next (/Users/dj/Downloads/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/node_modules/rxjs/dist/cjs/internal/Subscriber.js:161:21)
    at t._next (/Users/dj/Downloads/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/node_modules/rxjs/dist/cjs/internal/Subscriber.js:101:26)
    at t.next (/Users/dj/Downloads/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
    at emit (/Users/dj/Downloads/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/node_modules/rxjs/dist/cjs/internal/operators/debounceTime.js:19:28)
    at t.work (/Users/dj/Downloads/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/node_modules/rxjs/dist/cjs/internal/operators/debounceTime.js:30:13)
    at t._execute (/Users/dj/Downloads/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncAction.js:76:18)
electron/js2c/browser_init.js:165
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0});const o=r(/*! @electron/internal/browser/message-port-main */"./lib/browser/message-port-main.ts"),{WebFrameMain:n,fromId:s}=process._linkedBinding("electron_browser_web_frame_main");n.prototype.send=function(e,...t){if("string"!=typeof e)throw new Error("Missing required channel argument");return this._send(!1,e,t)},n.prototype._sendInternal=function(e,...t){if("string"!=typeof e)throw new Error("Missing required channel argument");return this._send(!0,e,t)},n.prototype.postMessage=function(...e){Array.isArray(e[2])&&(e[2]=e[2].map(e=>e instanceof o.MessagePortMain?e._internalPort:e)),this._postMessage(...e)},t.default={fromId:s}},"./lib/browser/default-menu.ts":
                                                                                                                                                                                                                                                                                                                                                                                                                            ^

Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (electron/js2c/browser_init.js:165:413)
    at Object.send (electron/js2c/browser_init.js:161:2471)
    at t.Window.send (/Users/dj/Downloads/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/lib/window.ts:194:33)
    at t.Application.broadcast (/Users/dj/Downloads/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/lib/app.ts:140:20)
    at process.<anonymous> (/Users/dj/Downloads/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/lib/index.ts:31:17)
    at process.apply (events.js:327:22)
    at process.on.process.emit (/Users/dj/Downloads/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/node_modules/source-map-support/source-map-support.js:495:21)
    at process._fatalException (internal/process/execution.js:163:25)
```

**Comment by Chealer** [comment]
Does this persist on 1.0.230 or above? If so, please provide reproduction steps.
