### ISSUE TITLE
Publish to Flathub

### ISSUE THREAD

**Issue by tracker1** [Eugeny/tabby#4728]
Would be really nice if this could be published to Flathub at the very least, though not sure how well it will work as a flatpack application.

**Comment by tracker1** [comment]
afaik, still active issue.

**Comment by czadikem** [comment]
Is this every going to happen?

**Comment by calvinweb** [comment]
But i think it is useless to publish it to flatpak because apps in flatpak cant access host's shell directly

**Comment by tracker1** [comment]
@calvinweb Have to agree...  Tried to use the flatpak version of VS Code, which was kind of painful as it didn't quite work right with the isolated shell experience.  I don't think Tabby would fare much better.  I don't know enough about flatpak to know if there's a configuration that could be done with an "easy button" for the user to grant real access.

**Comment by czadikem** [comment]
So then can we publish this as an AppImage would that work?  It just really sucks that it works so well on Windows, Ubuntu, and Mac, but not anything RPM based.

**Comment by tracker1** [comment]
Hyper.is seems to be available as an appImage, so that should work.

**Comment by tracker1** [comment]
Closing since this won't really work in Flathub, and created an Issue for AppImage target.

**Comment by patriziobruno** [comment]
@tracker1 this is actually inaccurate, you can start a host shell in flatpak using `flatpak-spawn --host /bin/bash` instead of just `/bin/bash`. You lose the advantages of a sandbox entirely, but I guess that's the point in this case.

**Comment by calvinweb** [comment]
> @tracker1 this is actually inaccurate, you can start a host shell in flatpak using `flatpak-spawn --host /bin/bash` instead of just `/bin/bash`. You lose the advantages of a sandbox entirely, but I guess that's the point in this case.

I think it is able to make a switch for "execute shell inside flatpak" but it may need to makeing breaking change of the code

**Comment by ghazyami** [comment]
Hello, I started experimenting packaging Tabby as Flatpak.
I am not an expert or have deep knowledge of how Flatpak works, I am also not sure if it's possible to run `Bash` without needing to change the code or not.


Currently, I am generating a flatpak based on the tar ball of Tabby, when it starts, I get the splash screen and this on the logs
```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[49:0309/201454.897476:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[49:0309/201454.915065:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[49:0309/201456.902465:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```
I would appreciate some help.

**Comment by BinaryShrub** [comment]
I know this message isn't helpful but I would REALLY like to see Tabby in Flathub for super easy install! When I was setting up my Linux Mint I totally expected to see it in Software Manager, and because it wasn't there I did a "Terminal" search before deciding to go through with a manual install.

This would be add to exposure.

**Comment by calvinweb** [comment]
> Hello, I started experimenting packaging Tabby as Flatpak.
> I am not an expert or have deep knowledge of how Flatpak works, I am also not sure if it's possible to run `Bash` without needing to change the code or not.
> 
> 
> Currently, I am generating a flatpak based on the tar ball of Tabby, when it starts, I get the splash screen and this on the logs
> ```
> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
> [49:0309/201454.897476:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
> [49:0309/201454.915065:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
> [49:0309/201456.902465:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
> ```
> I would appreciate some help.

can u paste your memifest here?

**Comment by hfluz** [comment]
I got more test to do in next days, but I got Tabby working through flatpak using /usr/bin/flatpak-spawn.

It's available in this repository: https://github.com/hfluz/tabby-flatpak

**Comment by hfluz** [comment]
NVM, actually flatpak-spawn is not working. When I click on Profiles and Connections -> Flatpak Spawn, it opens and closes another tab, similar to what's described in this snap issue: https://github.com/Eugeny/tabby/issues/548

I get the exceptions bellow on log:

```
Failed to list serial ports Error: spawn udevadm ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_errnoException (node:internal/errors:623:12)
    at Process.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(anonymous) @ /app/main/resources/builtin-plugins/tabby-serial/dist/index.js:3406
rejected @ /app/main/resources/builtin-plugins/tabby-serial/dist/index.js:3048
invoke @ zone.js:368
onInvoke @ ng_zone.ts:423
invoke @ zone.js:367
run @ zone.js:127
(anonymous) @ zone.js:1257
invokeTask @ zone.js:402
onInvokeTask @ ng_zone.ts:408
invokeTask @ zone.js:401
runTask @ zone.js:171
drainMicroTaskQueue @ zone.js:581
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
nativeScheduleMicroTask @ zone.js:557
scheduleMicroTask @ zone.js:568
scheduleTask @ zone.js:392
onScheduleTask @ zone.js:279
scheduleTask @ zone.js:382
scheduleTask @ zone.js:214
scheduleMicroTask @ zone.js:234
scheduleResolveOrReject @ zone.js:1247
resolvePromise @ zone.js:1184
(anonymous) @ zone.js:1100
(anonymous) @ zone.js:1116
emit @ node:events:514
(anonymous) @ node:internal/child_process:289
onErrorNT @ node:internal/child_process:476
processTicksAndRejections @ node:internal/process/task_queues:82
/app/main/resources/builtin-plugins/tabby-core/dist/index.js:15819 [local] Destroying
helpers.ts:111 Uncaught TypeError: Cannot read properties of undefined (reading 'dimensions')
    at get dimensions [as dimensions] (/app/main/resources/builtin-plugins/tabby-terminal/dist/index.js:25632:41)
    at t.Viewport._innerRefresh (/app/main/resources/builtin-plugins/tabby-terminal/dist/index.js:24403:60)
    at /app/main/resources/builtin-plugins/tabby-terminal/dist/index.js:24399:149
    at sentryWrapped (helpers.ts:87:17)
get dimensions @ /app/main/resources/builtin-plugins/tabby-terminal/dist/index.js:25632
_innerRefresh @ /app/main/resources/builtin-plugins/tabby-terminal/dist/index.js:24403
(anonymous) @ /app/main/resources/builtin-plugins/tabby-terminal/dist/index.js:24399
sentryWrapped @ helpers.ts:87
requestAnimationFrame (async)
(anonymous) @ trycatch.ts:129
_refresh @ /app/main/resources/builtin-plugins/tabby-terminal/dist/index.js:24399
XTermFrontend.resizeHandler @ /app/main/resources/builtin-plugins/tabby-terminal/dist/index.js:38901
(anonymous) @ /app/main/resources/builtin-plugins/tabby-terminal/dist/index.js:38967
timer @ zone.js:2355
invokeTask @ zone.js:402
runTask @ zone.js:171
invokeTask @ zone.js:483
ZoneTask.invoke @ zone.js:472
data.args.<computed> @ zone.js:2335
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonymous) @ trycatch.ts:119
scheduleTask @ zone.js:2337
scheduleTask @ zone.js:389
scheduleTask @ zone.js:214
scheduleMacroTask @ zone.js:237
scheduleMacroTaskWithCurrentZone @ zone.js:672
(anonymous) @ zone.js:2379
proto.<computed> @ zone.js:962
(anonymous) @ /app/main/resources/builtin-plugins/tabby-terminal/dist/index.js:38967
/app/main/resources/builtin-plugins/tabby-local/dist/index.js:3021 Could not read working directory: Error: ENOENT: no such file or directory, readlink '/proc/163/cwd'
    at Object.readlinkSync (node:fs:1736:3)
    at getWorkingDirectoryFromPID (/app/main/resources/app.asar/node_modules/native-process-working-directory/index.js:23:19)
    at ElectronPTYProxy.<anonymous> (/app/main/resources/builtin-plugins/tabby-electron/dist/index.js:35651:93)
    at Generator.next (<anonymous>)
    at fulfilled (/app/main/resources/builtin-plugins/tabby-electron/dist/index.js:25912:24)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:127:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:171:47)
    at drainMicroTaskQueue (zone.js:581:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by hfluz** [comment]
It's working now, I had to create the executable file /app/main/flatpak-spawn that calls `/usr/bin/flatpak-spawn --host bash`, this way Tabby doesn't add the quotes around the command.

However, I don't think there's a way to set this profile as the default, only the user can do that on settings, it will just be listed under available profiles.

**Comment by MajorTomDE** [comment]
I also wanted to ask again about official availability on Flathub. It would be so great...

**Comment by rugk** [comment]
BTW also note [there are many other terminals on Flathub](https://flathub.org/apps/search?q=terminal) like [BlackBox](https://flathub.org/apps/org.kde.konsole) (now deprecated AFAIK) or [Ptyxis](https://flathub.org/apps/app.devsuite.Ptyxis), so it seems to be doable / you can maybe get ideas from them (recipes are always in corresponding GitHub repos AFAIK).

**Comment by damajor** [comment]
Wezterm also works pretty fine as Flatpak, there is no reason Tabby shouldnt.

**Comment by TrueASL** [comment]
I'm sorry for the useless message, but is there any news about the publication in flatpak? Tabby is just amazing, but his absence from flatpak makes me depressed 😅

**Comment by tracker1** [comment]
I wish I was far more familiar with how flatpacks actually worked than I am.  Glad to see there's till ongoing interest in this here.

**Comment by jing2uo** [comment]
While this waits on Flathub, I've published a Flatpak of Tabby via [FlatPark](https://flatpark.org) (a small community hub for good apps that aren't on Flathub yet):

**https://flatpark.org/apps/org.tabby.Tabby/**

```sh
flatpak --user remote-add --if-not-exists flatpark https://dl.flatpark.org/flatpark.flatpakrepo
flatpak --user install flatpark org.tabby.Tabby
```

It repackages your **official `.deb` release, unmodified** — FlatPark just wraps the upstream binary as `extra-data`, so each install pulls the release straight from your GitHub. The manifest, install script and sandbox permissions are all open to review: [registry/org.tabby.Tabby](https://github.com/jing2uo/flatpark/tree/main/registry/org.tabby.Tabby).

@Eugeny if you'd rather this not exist, just say the word and I'll take it down. And if you're OK with it, I'd be glad to add a verified developer-authorization badge to the listing so users can see the approval is genuinely yours. Hope it helps Tabby's Linux users in the meantime 🙏
