### ISSUE TITLE
tabby 1.0.159 crash when run on ubuntu 16.04

### ISSUE THREAD

**Issue by frank2019** [Eugeny/tabby#4744]
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js:33:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}

tabby version：1.0.159
OS system:  ubuntu 16.04

**Comment by Paul75** [comment]
I have same problem

**Comment by Eugeny** [comment]
The Tabby builds are linked against libc 2.28, so this or a newer version is required.
