### ISSUE TITLE
start does not work after compile from git clone

### ISSUE THREAD

**Issue by boonkerz** [Eugeny/tabby#5140]
`thomas@elementaryosdesktopa0f94055:~/projekte/tabby$ yarn start
yarn run v1.22.17
$ cross-env TABBY_DEV=1 electron app --debug --inspect
Debugger listening on ws://127.0.0.1:9229/0512b712-db5d-4847-96bd-5a9542b859cf
For help, see: https://nodejs.org/en/docs/inspector
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /home/thomas/projekte/tabby/app/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js
- /home/thomas/projekte/tabby/app/node_modules/@tabby-gang/node-pty/lib/index.js
- /home/thomas/projekte/tabby/app/dist/main.js
- /home/thomas/projekte/tabby/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/home/thomas/projekte/tabby/app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/thomas/projekte/tabby/app/node_modules/@tabby-gang/node-pty/src/unixTerminal.ts:20:11)
    at Module._compile (/home/thomas/projekte/tabby/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/thomas/projekte/tabby/app/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js',
    '/home/thomas/projekte/tabby/app/node_modules/@tabby-gang/node-pty/lib/index.js',
    '/home/thomas/projekte/tabby/app/dist/main.js',
    '/home/thomas/projekte/tabby/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
App threw an error during load
Error: The module '/home/thomas/projekte/tabby/app/node_modules/@tabby-gang/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 102. This version of Node.js requires
NODE_MODULE_VERSION 89. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/home/thomas/projekte/tabby/app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/thomas/projekte/tabby/app/node_modules/@tabby-gang/node-pty/src/unixTerminal.ts:16:9)
    at Module._compile (/home/thomas/projekte/tabby/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: The module '/home/thomas/projekte/tabby/app/node_modules/@tabby-gang/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 102. This version of Node.js requires
NODE_MODULE_VERSION 89. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/home/thomas/projekte/tabby/app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/thomas/projekte/tabby/app/node_modules/@tabby-gang/node-pty/src/unixTerminal.ts:16:9)
    at Module._compile (/home/thomas/projekte/tabby/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)`

**Comment by Eugeny** [comment]
Tabby needs a relatively recent glibc (2.26+)

**Comment by boonkerz** [comment]
thomas@elementaryosdesktopa0f94055:~$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31
Copyright © 2020 Free Software Foundation, Inc.

**Comment by boonkerz** [comment]
`thomas@elementaryosdesktopa0f94055:~/Downloads$ ldd /home/thomas/projekte/tabby/app/node_modules/@tabby-gang/node-pty/build/Release/pty.node 
        linux-vdso.so.1 (0x00007ffc103ee000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f261224d000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f261206b000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2612048000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2611e56000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2611d07000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2612275000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2611cec000)
thomas@elementaryosdesktopa0f94055:~/Downloads$`

**Comment by boonkerz** [comment]
finished nodejs install via binarys
