### ISSUE TITLE
Settings/Terminal Tab has some rendering issues

### ISSUE THREAD

**Issue by wudisheng** [Eugeny/tabby#5263]
**Describe the problem**:
[A clear and concise description of what the bug is.]
Since .165 (or earlier) the Terminal tab in Settings has an issue that
- After switch to it, you can not switch to other tabs in Settings;
- The selection on it does not show (e.g. for Right Client, none of Off / Context Menu / Paste is highlighted even if I repeatedly click them);
- Some other functionality in Settings seems not responding;
- (I observed first in .168) The terminal display of SSH connection window sometimes cracks (e.g. shift of lines when using Vim to jump to the next match when searching), seems a rendering issue.

All the above issue disappear after I rolled back to .160, I'm not going to bisecting to find the exact version with the issue(s).

**To Reproduce**:
[Steps to reproduce the behavior]
Install corresponding versions.

**Comment by wudisheng** [comment]
Forgot to mention, I'm using MacOS on a M1 MBP.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by eugenov** [comment]
https://github.com/Eugeny/tabby/issues/5276
This is it.

**Comment by wudisheng** [comment]
Here's the console log from .169

Window bootstrap data: Object
plugins.ts:132 Found community-color-schemes in /Applications/Tabby.app/Contents/Resources/builtin-plugins
plugins.ts:132 Found core in /Applications/Tabby.app/Contents/Resources/builtin-plugins
plugins.ts:132 Found electron in /Applications/Tabby.app/Contents/Resources/builtin-plugins
plugins.ts:132 Found linkifier in /Applications/Tabby.app/Contents/Resources/builtin-plugins
plugins.ts:132 Found local in /Applications/Tabby.app/Contents/Resources/builtin-plugins
plugins.ts:132 Found plugin-manager in /Applications/Tabby.app/Contents/Resources/builtin-plugins
plugins.ts:132 Found serial in /Applications/Tabby.app/Contents/Resources/builtin-plugins
plugins.ts:132 Found settings in /Applications/Tabby.app/Contents/Resources/builtin-plugins
plugins.ts:132 Found ssh in /Applications/Tabby.app/Contents/Resources/builtin-plugins
plugins.ts:132 Found telnet in /Applications/Tabby.app/Contents/Resources/builtin-plugins
plugins.ts:132 Found terminal in /Applications/Tabby.app/Contents/Resources/builtin-plugins
entry.ts:67 Starting with plugins: Array(8)
plugins.ts:178 Loading terminal: /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-terminal/dist/index.js
plugins.ts:178 Loading ssh: /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-ssh/dist/index.js
plugins.ts:178 Loading settings: /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-settings/dist/index.js
plugins.ts:178 Loading plugin-manager: /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-plugin-manager/dist/index.js
plugins.ts:178 Loading local: /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-local/dist/index.js
plugins.ts:178 Loading electron: /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-electron/dist/index.js
plugins.ts:178 Loading core: /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js
plugins.ts:178 Loading community-color-schemes: /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-community-color-schemes/dist/index.js
/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:17440 [main] v 1.0.169
/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275 Unhandled exception: TypeError: Cannot read properties of null (reading 'setTrafficLightPosition')
    at IpcMainImpl.<anonymous> (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/lib/window.ts:433:25)
    at IpcMainImpl.emit (node:events:406:35)
    at IpcMainImpl.emit (node:domain:475:12)
    at Object.<anonymous> (node:electron/js2c/browser_init:161:9959)
    at Object.emit (node:events:394:28)
    at Object.apply [as emit] (node:domain:475:12)
    at Object.n.emit (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25)
(anonymous) @ /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275
/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275 Unhandled exception: TypeError: Cannot read properties of null (reading 'setOpacity')
    at IpcMainImpl.<anonymous> (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/lib/window.ts:437:25)
    at IpcMainImpl.emit (node:events:406:35)
    at IpcMainImpl.emit (node:domain:475:12)
    at Object.<anonymous> (node:electron/js2c/browser_init:161:9959)
    at Object.emit (node:events:394:28)
    at Object.apply [as emit] (node:domain:475:12)
    at Object.n.emit (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25)
(anonymous) @ /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275
core.js:6456 ERROR TypeError: Cannot read properties of undefined (reading 'modifier')
    at Object.eval [as updateDirectives] (ng:///TerminalModule/TerminalSettingsTabComponent.ngfactory.js:872)
    at Object.updateDirectives (bundle.js:82066)
    at checkAndUpdateView (bundle.js:81721)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81972)
    at execEmbeddedViewsAction (bundle.js:81925)
    at execProjectedViewsAction (bundle.js:81990)
    at callViewAction (bundle.js:81975)
    at execEmbeddedViewsAction (bundle.js:81925)
    at execProjectedViewsAction (bundle.js:81990)
    at callViewAction (bundle.js:81975)
    at execEmbeddedViewsAction (bundle.js:81925)
    at execProjectedViewsAction (bundle.js:81990)
    at callViewAction (bundle.js:81965)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at Object.checkAndUpdateView (bundle.js:81727)
    at ViewRef_.detectChanges (bundle.js:74183)
    at ApplicationRef.tick (bundle.js:79473)
    at bundle.js:79333
    at ZoneDelegate.invoke (bundle.js:116363)
    at Object.onInvoke (bundle.js:78477)
    at ZoneDelegate.invoke (bundle.js:116362)
    at Zone.run (bundle.js:116125)
    at NgZone.run (bundle.js:78331)
defaultErrorLogger @ core.js:6456
8core.js:6456 ERROR TypeError: Cannot read properties of undefined (reading 'modifier')
    at Object.eval [as updateDirectives] (ng:///TerminalModule/TerminalSettingsTabComponent.ngfactory.js:872)
    at Object.updateDirectives (bundle.js:82066)
    at checkAndUpdateView (bundle.js:81721)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at Object.checkAndUpdateView (bundle.js:81727)
    at ViewRef_.detectChanges (bundle.js:74183)
    at ApplicationRef.tick (bundle.js:79473)
    at bundle.js:79333
    at ZoneDelegate.invoke (bundle.js:116363)
    at Object.onInvoke (bundle.js:78477)
    at ZoneDelegate.invoke (bundle.js:116362)
    at Zone.run (bundle.js:116125)
    at NgZone.run (bundle.js:78331)
defaultErrorLogger @ core.js:6456
/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275 Unhandled exception: TypeError: Cannot read properties of null (reading 'setOpacity')
    at IpcMainImpl.<anonymous> (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/lib/window.ts:437:25)
    at IpcMainImpl.emit (node:events:406:35)
    at IpcMainImpl.emit (node:domain:475:12)
    at Object.<anonymous> (node:electron/js2c/browser_init:161:9959)
    at Object.emit (node:events:394:28)
    at Object.apply [as emit] (node:domain:475:12)
    at Object.n.emit (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25)
(anonymous) @ /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275
/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275 Unhandled exception: TypeError: Cannot read properties of null (reading 'setTrafficLightPosition')
    at IpcMainImpl.<anonymous> (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/lib/window.ts:433:25)
    at IpcMainImpl.emit (node:events:406:35)
    at IpcMainImpl.emit (node:domain:475:12)
    at Object.<anonymous> (node:electron/js2c/browser_init:161:9959)
    at Object.emit (node:events:394:28)
    at Object.apply [as emit] (node:domain:475:12)
    at Object.n.emit (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25)
(anonymous) @ /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275
2core.js:6456 ERROR TypeError: Cannot read properties of undefined (reading 'modifier')
    at Object.eval [as updateDirectives] (ng:///TerminalModule/TerminalSettingsTabComponent.ngfactory.js:872)
    at Object.updateDirectives (bundle.js:82066)
    at checkAndUpdateView (bundle.js:81721)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at Object.checkAndUpdateView (bundle.js:81727)
    at ViewRef_.detectChanges (bundle.js:74183)
    at ApplicationRef.tick (bundle.js:79473)
    at bundle.js:79333
    at ZoneDelegate.invoke (bundle.js:116363)
    at Object.onInvoke (bundle.js:78477)
    at ZoneDelegate.invoke (bundle.js:116362)
    at Zone.run (bundle.js:116125)
    at NgZone.run (bundle.js:78331)
defaultErrorLogger @ core.js:6456
/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275 Unhandled exception: TypeError: Cannot read properties of null (reading 'setOpacity')
    at IpcMainImpl.<anonymous> (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/lib/window.ts:437:25)
    at IpcMainImpl.emit (node:events:406:35)
    at IpcMainImpl.emit (node:domain:475:12)
    at Object.<anonymous> (node:electron/js2c/browser_init:161:9959)
    at Object.emit (node:events:394:28)
    at Object.apply [as emit] (node:domain:475:12)
    at Object.n.emit (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25)
(anonymous) @ /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275
/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275 Unhandled exception: TypeError: Cannot read properties of null (reading 'setTrafficLightPosition')
    at IpcMainImpl.<anonymous> (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/lib/window.ts:433:25)
    at IpcMainImpl.emit (node:events:406:35)
    at IpcMainImpl.emit (node:domain:475:12)
    at Object.<anonymous> (node:electron/js2c/browser_init:161:9959)
    at Object.emit (node:events:394:28)
    at Object.apply [as emit] (node:domain:475:12)
    at Object.n.emit (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25)
(anonymous) @ /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275
3core.js:6456 ERROR TypeError: Cannot read properties of undefined (reading 'modifier')
    at Object.eval [as updateDirectives] (ng:///TerminalModule/TerminalSettingsTabComponent.ngfactory.js:872)
    at Object.updateDirectives (bundle.js:82066)
    at checkAndUpdateView (bundle.js:81721)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at checkAndUpdateView (bundle.js:81727)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execEmbeddedViewsAction (bundle.js:81925)
    at checkAndUpdateView (bundle.js:81722)
    at callViewAction (bundle.js:81962)
    at execComponentViewsAction (bundle.js:81904)
    at Object.checkAndUpdateView (bundle.js:81727)
    at ViewRef_.detectChanges (bundle.js:74183)
    at ApplicationRef.tick (bundle.js:79473)
    at bundle.js:79333
    at ZoneDelegate.invoke (bundle.js:116363)
    at Object.onInvoke (bundle.js:78477)
    at ZoneDelegate.invoke (bundle.js:116362)
    at Zone.run (bundle.js:116125)
    at NgZone.run (bundle.js:78331)
defaultErrorLogger @ core.js:6456
/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275 Unhandled exception: TypeError: Cannot read properties of null (reading 'setOpacity')
    at IpcMainImpl.<anonymous> (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/lib/window.ts:437:25)
    at IpcMainImpl.emit (node:events:406:35)
    at IpcMainImpl.emit (node:domain:475:12)
    at Object.<anonymous> (node:electron/js2c/browser_init:161:9959)
    at Object.emit (node:events:394:28)
    at Object.apply [as emit] (node:domain:475:12)
    at Object.n.emit (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25)
(anonymous) @ /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275
/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275 Unhandled exception: TypeError: Cannot read properties of null (reading 'setTrafficLightPosition')
    at IpcMainImpl.<anonymous> (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/lib/window.ts:433:25)
    at IpcMainImpl.emit (node:events:406:35)
    at IpcMainImpl.emit (node:domain:475:12)
    at Object.<anonymous> (node:electron/js2c/browser_init:161:9959)
    at Object.emit (node:events:394:28)
    at Object.apply [as emit] (node:domain:475:12)
    at Object.n.emit (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25)
(anonymous) @ /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275
/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275 Unhandled exception: TypeError: Cannot read properties of null (reading 'setOpacity')
    at IpcMainImpl.<anonymous> (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/lib/window.ts:437:25)
    at IpcMainImpl.emit (node:events:406:35)
    at IpcMainImpl.emit (node:domain:475:12)
    at Object.<anonymous> (node:electron/js2c/browser_init:161:9959)
    at Object.emit (node:events:394:28)
    at Object.apply [as emit] (node:domain:475:12)
    at Object.n.emit (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25)
(anonymous) @ /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275
/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275 Unhandled exception: TypeError: Cannot read properties of null (reading 'setTrafficLightPosition')
    at IpcMainImpl.<anonymous> (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/lib/window.ts:433:25)
    at IpcMainImpl.emit (node:events:406:35)
    at IpcMainImpl.emit (node:domain:475:12)
    at Object.<anonymous> (node:electron/js2c/browser_init:161:9959)
    at Object.emit (node:events:394:28)
    at Object.apply [as emit] (node:domain:475:12)
    at Object.n.emit (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25)
(anonymous) @ /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27275
DevTools failed to load source map: Could not parse content for file:///Applications/Tabby.app/Contents/Resources/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@angular/cdk/bundles/cdk-drag-drop.umd.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@angular/cdk/bundles/cdk-scrolling.umd.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@angular/cdk/bundles/cdk-coercion.umd.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@angular/cdk/bundles/cdk-platform.umd.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@angular/cdk/bundles/cdk-bidi.umd.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@angular/cdk/bundles/cdk-collections.umd.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@angular/cdk/bundles/cdk-a11y.umd.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@angular/cdk/bundles/cdk-keycodes.umd.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@angular/cdk/bundles/cdk-observers.umd.js.map: Unexpected end of JSON input
7DevTools failed to load source map: Could not parse content for file:///Applications/Tabby.app/Contents/Resources/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
