### ISSUE TITLE
Cannot sync with my previous config at Tabby cloud

### ISSUE THREAD

**Issue by alansenairj** [Eugeny/tabby#5310]
Version: 1.0.169
Platform: Fedora 35
Plugins: alot

I upload configs but it is not syncing. I need to reproduce it on fresh install and it downloaded, overwrited and nothing happens.

**Comment by alansenairj** [comment]
![image](https://user-images.githubusercontent.com/20565821/147496250-e0ba305a-7a83-4d86-9ada-e8b7d7b4589f.png)

**Comment by ql-isaac** [comment]
me too!

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by ql-isaac** [comment]
```
electron/js2c/renderer_init.js:33 The vm module of Node.js is deprecated in the renderer process and will be removed.
o._load @ electron/js2c/renderer_init.js:33
entry.ts:56 Window bootstrap data: Object
plugins.ts:132 Found community-color-schemes in E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins
plugins.ts:132 Found core in E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins
plugins.ts:132 Found electron in E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins
plugins.ts:132 Found linkifier in E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins
plugins.ts:132 Found local in E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins
plugins.ts:132 Found plugin-manager in E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins
plugins.ts:132 Found serial in E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins
plugins.ts:132 Found settings in E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins
plugins.ts:132 Found ssh in E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins
plugins.ts:132 Found telnet in E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins
plugins.ts:132 Found terminal in E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins
entry.ts:67 Starting with plugins: Array(11)
plugins.ts:178 Loading terminal: E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-terminal\dist\index.js
plugins.ts:178 Loading telnet: E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-telnet\dist\index.js
plugins.ts:178 Loading ssh: E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-ssh\dist\index.js
plugins.ts:178 Loading settings: E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-settings\dist\index.js
plugins.ts:178 Loading serial: E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-serial\dist\index.js
plugins.ts:178 Loading plugin-manager: E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-plugin-manager\dist\index.js
plugins.ts:178 Loading local: E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-local\dist\index.js
plugins.ts:178 Loading linkifier: E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-linkifier\dist\index.js
plugins.ts:178 Loading electron: E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-electron\dist\index.js
plugins.ts:178 Loading core: E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-core\dist\index.js
plugins.ts:178 Loading community-color-schemes: E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-community-color-schemes\dist\index.js
E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-core\dist\index.js:17440 [main] v 1.0.167
index.html:1 Autofocus processing was blocked because a document already has a focused element.
E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-core\dist\index.js:17440 [hostApp] CLI arguments received: Object
E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-core\dist\index.js:17440 [updater] Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105)
    at SimpleURLLoaderWrapper.emit (events.js:315)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:467)
doLog @ E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-core\dist\index.js:17440
zone.js:1063 Unhandled Promise rejection: net::ERR_CONNECTION_RESET ; Zone: <root> ; Task: null ; Value: Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105)
    at SimpleURLLoaderWrapper.emit (events.js:315)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:467) Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:467:12)
api.onUnhandledError @ zone.js:1063
undefined:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
undefined:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-terminal\dist\index.js:7973 Color: null is invalid using fallback #000000
e._parseColor @ E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-terminal\dist\index.js:7973
E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-core\dist\index.js:17440 [ssh-42.192.40.202-6100]  !  Agent auth selected, but no running agent is detected
E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-core\dist\index.js:17440 [ssh-42.192.40.202-6100] Host key fingerprint:
E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-core\dist\index.js:17440 [ssh-42.192.40.202-6100]  SHA256  11804a90a0ecac8d47257ce13664d105583256e21525e241ff091d04936b7eda 
E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-core\dist\index.js:17440 [ssh-42.192.40.202-6100] Handshake complete: Object
E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-core\dist\index.js:17440 [ssh-42.192.40.202-6100] Trying saved password
4dae7eacbecb691d7ec8.otf:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/resources/app.asar/dist/cdk-drag-drop.umd.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/resources/app.asar/dist/cdk-scrolling.umd.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/resources/app.asar/dist/cdk-coercion.umd.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/resources/app.asar/dist/cdk-platform.umd.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/resources/app.asar/dist/cdk-bidi.umd.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/resources/app.asar/dist/cdk-collections.umd.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/resources/app.asar/dist/cdk-a11y.umd.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/resources/app.asar/dist/cdk-keycodes.umd.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/resources/app.asar/dist/cdk-observers.umd.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/resources/app.asar/dist/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///E:/Portable/tabby-1.0.167-portable/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-core\dist\index.js:17440 [ssh-42.192.40.202-6100] Destroying
E:\Portable\tabby-1.0.167-portable\resources\builtin-plugins\tabby-core\dist\index.js:17440 [ssh-42.192.40.202-6100] Shell session ended
```

**Comment by Eugeny** [comment]
Can you copy the log again after trying to sync?

**Comment by ql-isaac** [comment]
> Can you copy the log again after trying to sync?
nothing changed

**Comment by ql-isaac** [comment]
> Can you copy the log again after trying to sync?

nothing changed

**Comment by Eugeny** [comment]
Do you see new requests popping up on the Network page of the devtools window when you're syncing?

**Comment by ql-isaac** [comment]
> Do you see new requests popping up on the Network page of the devtools window when you're syncing?

When clicking Config sync:
![image](https://user-images.githubusercontent.com/53886119/149294845-af73d093-87e7-4c07-9d8a-fb34578ba7ea.png)
When clicking Download,there is nothing happening.

**Comment by JaheimLee** [comment]
same problem on windows!
