### ISSUE TITLE
Tabs does not close after typing exit

### ISSUE THREAD

**Issue by saudiqbal** [Eugeny/tabby#5332]
Typing exit on terminal does not close the tab, doing some other action like minimize and maximize closes the tab, happens on both Linux and Windows.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by LinderNet** [comment]
That' mine with same problem:

`node:electron/js2c/renderer_init:33 The vm module of Node.js is deprecated in the renderer process and will be removed.
o._load @ node:electron/js2c/renderer_init:33
entry.ts:56 Window bootstrap data: Object
plugins.ts:139 Found community-color-schemes in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found core in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found electron in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found linkifier in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found local in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found plugin-manager in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found serial in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found settings in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found ssh in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found telnet in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found terminal in D:\Programme\Tabby\resources\builtin-plugins
entry.ts:67 Starting with plugins: Array(11)
plugins.ts:185 Loading terminal: D:\Programme\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js
plugins.ts:185 Loading telnet: D:\Programme\Tabby\resources\builtin-plugins\tabby-telnet\dist\index.js
plugins.ts:185 Loading ssh: D:\Programme\Tabby\resources\builtin-plugins\tabby-ssh\dist\index.js
plugins.ts:185 Loading settings: D:\Programme\Tabby\resources\builtin-plugins\tabby-settings\dist\index.js
plugins.ts:185 Loading serial: D:\Programme\Tabby\resources\builtin-plugins\tabby-serial\dist\index.js
plugins.ts:185 Loading plugin-manager: D:\Programme\Tabby\resources\builtin-plugins\tabby-plugin-manager\dist\index.js
plugins.ts:185 Loading local: D:\Programme\Tabby\resources\builtin-plugins\tabby-local\dist\index.js
plugins.ts:185 Loading linkifier: D:\Programme\Tabby\resources\builtin-plugins\tabby-linkifier\dist\index.js
plugins.ts:185 Loading electron: D:\Programme\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js
plugins.ts:185 Loading core: D:\Programme\Tabby\resources\builtin-plugins\tabby-core\dist\index.js
plugins.ts:185 Loading community-color-schemes: D:\Programme\Tabby\resources\builtin-plugins\tabby-community-color-schemes\dist\index.js
D:\Programme\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19158 [main] v 1.0.172
D:\Programme\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19158 [hostApp] CLI arguments received: Object
D:\Programme\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19158 [updater] No updates
undefined:1          Failed to load resource: net::ERR_FILE_NOT_FOUND
D:\Programme\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:8046 Color: null is invalid using fallback #000000
e._parseColor @ D:\Programme\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:8046
index.html:1 Autofocus processing was blocked because a document already has a focused element.
core.js:6456 ERROR Error: Uncaught (in promise): [object Number]
    at resolvePromise (zone.js:1213:1)
    at zone.js:1120:1
    at rejected (D:\Programme\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:10724:89)
    at ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.js:28666:1)
    at ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1276:1
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28653:1)
    at ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:582:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:1)
    at invokeTask (zone.js:1600:1)
    at HTMLElement.globalZoneAwareCallback (zone.js:1626:1)
    at HTMLElement.sentryWrapped (helpers.js:72:1)
defaultErrorLogger @ core.js:6456
6DevTools failed to load source map: Could not parse content for file:///D:/Programme/Tabby/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///D:/Programme/Tabby/resources/app.asar/dist/index.js.map: Unexpected end of JSON input
5DevTools failed to load source map: Could not parse content for file:///D:/Programme/Tabby/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
D:\Programme\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19158 [local] Destroying`

**Comment by LinderNet** [comment]
That's mine with same problem:

`node:electron/js2c/renderer_init:33 The vm module of Node.js is deprecated in the renderer process and will be removed.
o._load @ node:electron/js2c/renderer_init:33
entry.ts:56 Window bootstrap data: Object
plugins.ts:139 Found community-color-schemes in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found core in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found electron in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found linkifier in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found local in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found plugin-manager in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found serial in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found settings in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found ssh in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found telnet in D:\Programme\Tabby\resources\builtin-plugins
plugins.ts:139 Found terminal in D:\Programme\Tabby\resources\builtin-plugins
entry.ts:67 Starting with plugins: Array(11)
plugins.ts:185 Loading terminal: D:\Programme\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js
plugins.ts:185 Loading telnet: D:\Programme\Tabby\resources\builtin-plugins\tabby-telnet\dist\index.js
plugins.ts:185 Loading ssh: D:\Programme\Tabby\resources\builtin-plugins\tabby-ssh\dist\index.js
plugins.ts:185 Loading settings: D:\Programme\Tabby\resources\builtin-plugins\tabby-settings\dist\index.js
plugins.ts:185 Loading serial: D:\Programme\Tabby\resources\builtin-plugins\tabby-serial\dist\index.js
plugins.ts:185 Loading plugin-manager: D:\Programme\Tabby\resources\builtin-plugins\tabby-plugin-manager\dist\index.js
plugins.ts:185 Loading local: D:\Programme\Tabby\resources\builtin-plugins\tabby-local\dist\index.js
plugins.ts:185 Loading linkifier: D:\Programme\Tabby\resources\builtin-plugins\tabby-linkifier\dist\index.js
plugins.ts:185 Loading electron: D:\Programme\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js
plugins.ts:185 Loading core: D:\Programme\Tabby\resources\builtin-plugins\tabby-core\dist\index.js
plugins.ts:185 Loading community-color-schemes: D:\Programme\Tabby\resources\builtin-plugins\tabby-community-color-schemes\dist\index.js
D:\Programme\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19158 [main] v 1.0.172
D:\Programme\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19158 [hostApp] CLI arguments received: Object
D:\Programme\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19158 [updater] No updates
undefined:1          Failed to load resource: net::ERR_FILE_NOT_FOUND
D:\Programme\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:8046 Color: null is invalid using fallback #000000
e._parseColor @ D:\Programme\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:8046
index.html:1 Autofocus processing was blocked because a document already has a focused element.
core.js:6456 ERROR Error: Uncaught (in promise): [object Number]
    at resolvePromise (zone.js:1213:1)
    at zone.js:1120:1
    at rejected (D:\Programme\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:10724:89)
    at ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.js:28666:1)
    at ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1276:1
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28653:1)
    at ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:582:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:1)
    at invokeTask (zone.js:1600:1)
    at HTMLElement.globalZoneAwareCallback (zone.js:1626:1)
    at HTMLElement.sentryWrapped (helpers.js:72:1)
defaultErrorLogger @ core.js:6456
6DevTools failed to load source map: Could not parse content for file:///D:/Programme/Tabby/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///D:/Programme/Tabby/resources/app.asar/dist/index.js.map: Unexpected end of JSON input
5DevTools failed to load source map: Could not parse content for file:///D:/Programme/Tabby/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
D:\Programme\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19158 [local] Destroying`
