### ISSUE TITLE
Tabby not opening in Ubuntu 20.04

### ISSUE THREAD

**Issue by eldhothebest** [Eugeny/tabby#5777]
**### tabby problem on ubuntu**
@Eugeny plz help
i cant open tabby in ubuntu 20.04 and i don't know what is happening. The tabby app runs on background and i cant use it
![Tabby Problem](https://user-images.githubusercontent.com/61624460/154264247-92d89d35-40e2-47d2-9dbb-8b3634c57663.png)
![background](https://user-images.githubusercontent.com/61624460/154265031-11c87e2b-149a-48e8-9665-c3b547935a14.png)
help me plz
if you don't understand i have a video maybe explain

https://user-images.githubusercontent.com/61624460/154266102-6fa06c1e-e9a9-4e86-9d33-8810d156be76.mp4

**Comment by Eugeny** [comment]
Which version are you on? Try killing all `tabby` processes first and then starting it again.

**Comment by eldhothebest** [comment]
> Which version are you on? Try killing all `tabby` processes first and then starting it again.
i downgrade to 1.68 and its working. i think from 1.69 version its not working

**Comment by eldhothebest** [comment]
> Which version are you on? Try killing all `tabby` processes first and then starting it again.
i tried but its not working 'sad emoji'

**Comment by Eugeny** [comment]
Do you get any console output if you kill the processes again and start `tabby --debug` from a different terminal?

**Comment by akshaybharwani** [comment]
Was this ever addressed? Manually installed it and I just can't get it to open.

`tabby --debug`

```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:2:117760)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}
zXx^X^Z
[1]+  Stopped                 tabby
[akshaybharwani@pop-os ~]$ tabby --debug
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:2:117760)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}
```
