### ISSUE TITLE
Unable to open a new Tab 

### ISSUE THREAD

**Issue by christophermarsh** [Eugeny/tabby#5789]
Version: 1.0.172
Platform: Windows x64 10.0.22543
Plugins: none
Frontend: xterm

GET file:///C:/Users/chris/AppData/Local/Programs/Tabby/resources/app.asar/dist/undefined net::ERR_FILE_NOT_FOUND
C:\Users\chris\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19158 [local] Destroying
C:\Users\chris\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:5754 Could not read working directory: Error: Failed to read PROCESS_BASIC_INFORMATION.PebBaseAddress
    at getWorkingDirectoryFromPID (C:\Users\chris\AppData\Local\Programs\Tabby\resources\app.asar\node_modules\native-process-working-directory\index.js:25:36)
    at Session.<anonymous> (C:\Users\chris\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:5751:96)
    at Generator.next (<anonymous>)
    at C:\Users\chris\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:5254:71
    at new ZoneAwarePromise (zone.js:1387:1)
    at __awaiter (C:\Users\chris\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:5250:12)
    at Session.getWorkingDirectory (C:\Users\chris\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:5742:16)
    at Session.<anonymous> (C:\Users\chris\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:5627:42)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\chris\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:5251:58)
    at ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.js:28666:1)
    at ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1276:1
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28653:1)
    at ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:582:1)

**Comment by wangbin3961** [comment]
I have the same problem. Try turn off [Shell -> Use conPTY]. It works for me , although the error msg still exist in dev tools.

**Comment by UAnton** [comment]
Why is the Issue closed if the problem is present and there is no solution?
