### ISSUE TITLE
Latest nightly builds don't start on MacOS

### ISSUE THREAD

**Issue by imTHAI** [Eugeny/tabby#6089]
Hello,

After you fixed [the squares displayed in place of icons](https://github.com/Eugeny/tabby/issues/6071), I wanted to try it. So I downloaded a nightly build (zip arm MacOS version, since I have a Mac-mini with M1 silicon). But when I run it, Tabby starts but doesn't open any window. I tried 2 different days (= 2 different nightly builds).

As soon as I put back the Alpha 174 release, it works again. Any idea ? Would there be a bug in the nightly build regarding the MacOS versions ?

KR,

**Comment by Eugeny** [comment]
It works for me - do you see any errors when running `/Applications/Tabby.app/Contents/MacOS/Tabby --debug` in another terminal?

**Comment by imTHAI** [comment]
So I downloaded the build of [today ](https://nightly.link/Eugeny/tabby/workflows/build/master/macOS%20.zip%20%28arm64%29.zip)

When I launch it, it start (I get the icon in the docker) but no window.

```
❯ /Applications/Tabby.app/Contents/MacOS/Tabby --debug
[33079:0405/191716.373004:ERROR:node_bindings.cc(242)] Error parsing Node.js cli flags
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js
- /Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js
- /Applications/Tabby.app/Contents/Resources/app.asar/dist/main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js:33:15)
    at Module._compile (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js',
    '/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js',
    '/Applications/Tabby.app/Contents/Resources/app.asar/dist/main.js',
    undefined
  ]
}
objc[33082]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x2443171a8) and /Applications/Tabby.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x1050293c8). One of the two will be used. Which one is undefined.
```

**Comment by imTHAI** [comment]
Hello, 
I just notice now your edited message with the link you mentioned. 
> https://github.com/Eugeny/tabby/actions/runs/2094697789
So I tried and, indeed, this build runs on Mac-Mini Silicon.
Although, it didn't solve the problem mentioned [here](https://github.com/Eugeny/tabby/issues/6071):
![image](https://user-images.githubusercontent.com/36070606/162136910-00785750-230e-4bce-a814-9f0c1e774ed7.png)

**Comment by imTHAI** [comment]
It is solved
![image](https://user-images.githubusercontent.com/36070606/162425253-ea395b5a-b3b6-4746-96ce-d38a55b80dab.png)
