### ISSUE TITLE
MacOS Windows 10 Bootcamp don't have any Terminal

### ISSUE THREAD

**Issue by maverickmeydieu** [Eugeny/tabby#6094]
Version: 1.0.174
Platform: Windows x64 10.0.19044
Plugins: none
Frontend: xterm

I can't use Tabby on MacOS Windows 10 Bootcamp because it doesn't offer any terminal.

![image](https://user-images.githubusercontent.com/101877847/161694321-5fc5af40-a619-4b6b-89c5-d19e54f27092.png)

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by maverickmeydieu** [comment]
```
node:electron/js2c/renderer_init:33 The vm module of Node.js is deprecated in the renderer process and will be removed.
o._load @ node:electron/js2c/renderer_init:33
entry.ts:56 Window bootstrap data: Object
plugins.ts:139 Found community-color-schemes in C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found core in C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found electron in C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found linkifier in C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found local in C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found plugin-manager in C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found serial in C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found settings in C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found ssh in C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found telnet in C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found terminal in C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins
entry.ts:67 Starting with plugins: Array(11)
plugins.ts:185 Loading terminal: C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js
plugins.ts:185 Loading telnet: C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-telnet\dist\index.js
plugins.ts:185 Loading ssh: C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-ssh\dist\index.js
plugins.ts:185 Loading settings: C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-settings\dist\index.js
plugins.ts:185 Loading serial: C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-serial\dist\index.js
plugins.ts:185 Loading plugin-manager: C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-plugin-manager\dist\index.js
plugins.ts:185 Loading local: C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-local\dist\index.js
plugins.ts:185 Loading linkifier: C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-linkifier\dist\index.js
plugins.ts:185 Loading electron: C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js
plugins.ts:185 Loading core: C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js
plugins.ts:185 Loading community-color-schemes: C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-community-color-schemes\dist\index.js
C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19570 [main] v 1.0.174
C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:29861 Unhandled exception: TypeError: Cannot read properties of undefined (reading 'disableVibrancyWhileDragging')
    at IpcMainImpl.<anonymous> (C:\Users\<username>\AppData\Local\Programs\Tabby\resources\app.asar\dist\webpack:\tabby\lib\window.ts:418:81)
    at IpcMainImpl.emit (node:events:390:28)
    at IpcMainImpl.emit (node:domain:475:12)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10120)
    at EventEmitter.emit (node:events:390:28)
    at EventEmitter.apply [as emit] (node:domain:475:12)
    at EventEmitter.n.emit (C:\Users\<username>\AppData\Local\Programs\Tabby\resources\app.asar\dist\webpack:\tabby\node_modules\@sentry\electron\dist\main\integrations\electron.js:63:25)
(anonymous) @ C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:29861
index.html:1 Autofocus processing was blocked because a document already has a focused element.
C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19570 [hostApp] CLI arguments received: Object
C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19570 [hostApp] CLI handler matched: AutoOpenTabCLIHandler
core.js:6456 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'type')
TypeError: Cannot read properties of undefined (reading 'type')
    at C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:27364:81
    at Array.find (<anonymous>)
    at ProfilesService.providerForProfile (C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:27364:54)
    at ProfilesService.getConfigProxyForProfile (C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:27463:31)
    at TerminalService.<anonymous> (C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:6164:54)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:5251:58)
    at _ZoneDelegate.invoke (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:125940:26)
    at Object.onInvoke (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:87629:33)
    at _ZoneDelegate.invoke (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:125939:52)
    at Zone.run (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:125702:43)
    at file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:126843:36
    at _ZoneDelegate.invokeTask (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:125974:31)
    at Object.onInvokeTask (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:87616:33)
    at _ZoneDelegate.invokeTask (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:125973:60)
    at Zone.runTask (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:125746:47)
    at drainMicroTaskQueue (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:126153:35)
    at resolvePromise (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:126779:31)
    at file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:126686:17
    at fulfilled (C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:5251:86)
    at _ZoneDelegate.invoke (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:125940:26)
    at Object.onInvoke (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:87629:33)
    at _ZoneDelegate.invoke (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:125939:52)
    at Zone.run (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:125702:43)
    at file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:126843:36
    at _ZoneDelegate.invokeTask (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:125974:31)
    at Object.onInvokeTask (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:87616:33)
    at _ZoneDelegate.invokeTask (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:125973:60)
    at Zone.runTask (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:125746:47)
    at drainMicroTaskQueue (file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:126153:35)
defaultErrorLogger @ core.js:6456
C:\Users\<username>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19570 [updater] No updates
6DevTools failed to load source map: Could not parse content for file:///C:/Users/<username>/AppData/Local/Programs/Tabby/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/<username>/AppData/Local/Programs/Tabby/resources/app.asar/dist/index.js.map: Unexpected end of JSON input
5DevTools failed to load source map: Could not parse content for file:///C:/Users/<username>/AppData/Local/Programs/Tabby/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
```
