### ISSUE TITLE
Fresh Windows 11: No profile

### ISSUE THREAD

**Issue by maverickmeydieu** [Eugeny/tabby#6110]
**Describe the problem**:
I don't have any profile to use Tabby.
![image](https://user-images.githubusercontent.com/101877847/162042678-14abbd67-c969-45a2-8484-ed3308a668d1.png)

**To Reproduce**:
1. Install Windows 11
2. Install Tabby
3. Run Tabby

**Theory**:
I also reported a similar error on a MacOS Windows 10 Bootcamp: [https://github.com/Eugeny/tabby/issues/6094](https://github.com/Eugeny/tabby/issues/6094)
These two installation's username are "User NAME". Can a space in a username break the software?

**DevTools**:
```
node:electron/js2c/renderer_init:33 The vm module of Node.js is deprecated in the renderer process and will be removed.
o._load @ node:electron/js2c/renderer_init:33
entry.ts:56 Window bootstrap data: Object
plugins.ts:139 Found community-color-schemes in C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found core in C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found electron in C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found linkifier in C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found local in C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found plugin-manager in C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found serial in C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found settings in C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found ssh in C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found telnet in C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins
plugins.ts:139 Found terminal in C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins
entry.ts:67 Starting with plugins: Array(11)
plugins.ts:185 Loading terminal: C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js
plugins.ts:185 Loading telnet: C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-telnet\dist\index.js
plugins.ts:185 Loading ssh: C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-ssh\dist\index.js
plugins.ts:185 Loading settings: C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-settings\dist\index.js
plugins.ts:185 Loading serial: C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-serial\dist\index.js
plugins.ts:185 Loading plugin-manager: C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-plugin-manager\dist\index.js
plugins.ts:185 Loading local: C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-local\dist\index.js
plugins.ts:185 Loading linkifier: C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-linkifier\dist\index.js
plugins.ts:185 Loading electron: C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js
plugins.ts:185 Loading core: C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js
plugins.ts:185 Loading community-color-schemes: C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-community-color-schemes\dist\index.js
C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19570 [main] v 1.0.174
C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:29861 Unhandled exception: TypeError: Cannot read properties of undefined (reading 'disableVibrancyWhileDragging')
    at IpcMainImpl.<anonymous> (C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\app.asar\dist\webpack:\tabby\lib\window.ts:418:81)
    at IpcMainImpl.emit (node:events:390:28)
    at IpcMainImpl.emit (node:domain:475:12)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10120)
    at EventEmitter.emit (node:events:390:28)
    at EventEmitter.apply [as emit] (node:domain:475:12)
    at EventEmitter.n.emit (C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\app.asar\dist\webpack:\tabby\node_modules\@sentry\electron\dist\main\integrations\electron.js:63:25)
(anonymous) @ C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:29861
index.html:1 Autofocus processing was blocked because a document already has a focused element.
C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19570 [hostApp] CLI arguments received: Object
C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19570 [hostApp] CLI handler matched: AutoOpenTabCLIHandler
C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19570 [terminal] Starting profile Serial: (Standard port types) ConfigProxy
C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19570 [configSync] Remote config changed, downloading
C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19570 [updater] No updates
core.js:6456 ERROR Error: Uncaught (in promise): [object Number]
    at resolvePromise (zone.js:1211:1)
    at zone.js:1118:1
    at rejected (C:\Users\<user name>\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:5252:89)
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.js:28666:1)
    at _ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1275:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28653:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:1)
    at invokeTask (zone.js:1648:1)
    at globalCallback (zone.js:1679:1)
    at HTMLElement.globalZoneAwareCallback (zone.js:1712:1)
    at HTMLElement.sentryWrapped (helpers.js:72:1)
defaultErrorLogger @ core.js:6456
6DevTools failed to load source map: Could not parse content for file:///C:/Users/<user name>/AppData/Local/Programs/Tabby/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/<user name>/AppData/Local/Programs/Tabby/resources/app.asar/dist/index.js.map: Unexpected end of JSON input
5DevTools failed to load source map: Could not parse content for file:///C:/Users/<user name>/AppData/Local/Programs/Tabby/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
```

**Comment by Eugeny** [comment]
Fixed in the nightly build.

**Comment by maverickmeydieu** [comment]
I installed the nightly build but Tabby doesn't start anymore.
