### ISSUE TITLE
can't launch on macos

### ISSUE THREAD

**Issue by debugly** [Eugeny/tabby#6208]
tabby-1.0.175-macos-arm64.zip  
macOS Monterry M1

```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js
- /Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js
- /Applications/Tabby.app/Contents/Resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js:33:15)
    at Module._compile (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js',
    '/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js',
    '/Applications/Tabby.app/Contents/Resources/app.asar/dist/main.js',
    undefined
  ]
}
Error returned: <dictionary: 0x20a69e520> { count = 1, transaction: 0, voucher = 0x0, contents =
	"XPCErrorDescription" => <string: 0x20a69e6b8> { length = 18, contents = "Connection invalid" }
}
```

**Comment by samurai00** [comment]
Cannot launch either.
tabby-1.0.175-macos-arm64.pkg
macOS 12.3.1
Apple M1 Pro

**Comment by samurai00** [comment]
duplicated #6201

**Comment by Eugeny** [comment]
Should be fixed in the nightly build - please let me know.
