### ISSUE TITLE
Error: Cannot find module '../build/Debug/pty.node'

### ISSUE THREAD

**Issue by woodmeal** [Eugeny/tabby#6231]
**Describe the problem**:
So I added a new feature in the tabby-ssh folder and I wanted to test it. So I followed the instructions of the [HACKING.md](https://github.com/Eugeny/tabby/blob/master/HACKING.md#getting-started) everything looks okay until I run `yarn start` where it shows me these errors: 
```
$ cross-env TABBY_DEV=1 electron app --debug --inspect
[34583:0421/120749.695616:ERROR:node_bindings.cc(242)] Error parsing Node.js cli flags 
Debugger listening on ws://127.0.0.1:9229/723b085e-660d-4951-aae3-40794b566798
For help, see: https://nodejs.org/en/docs/inspector
innerError Error: Cannot find module '../build/Debug/pty.node'

Require stack:
- /home/user/tabby/app/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js
- /home/user/tabby/app/node_modules/@tabby-gang/node-pty/lib/index.js
- /home/user/tabby/app/dist/main.js
- /home/user/tabby/node_modules/electron/dist/resources/default_app.asar/main.js

- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (/home/user/tabby/app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/user/tabby/app/node_modules/@tabby-gang/node-pty/src/unixTerminal.ts:20:11)
    at Module._compile (/home/user/tabby/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/tabby/app/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js',
    '/home/user/tabby/app/node_modules/@tabby-gang/node-pty/lib/index.js',
    '/home/user/tabby/app/dist/main.js',
    '/home/user/tabby/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
```
Then

```
App threw an error during load
Error: The module '/home/user/tabby/app/node_modules/@tabby-gang/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 103. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1812)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (/home/user/tabby/app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/user/tabby/app/node_modules/@tabby-gang/node-pty/src/unixTerminal.ts:16:9)
    at Module._compile (/home/user/tabby/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: The module '/home/user/tabby/app/node_modules/@tabby-gang/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 103. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1812)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (/home/user/tabby/app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/user/tabby/app/node_modules/@tabby-gang/node-pty/src/unixTerminal.ts:16:9)
    at Module._compile (/home/user/tabby/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
```
and finally

```
[34633:0421/120750.407563:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[34633:0421/120750.419232:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.419510:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.419662:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.419807:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.419946:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.420105:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.420219:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.420337:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.420455:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.420573:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.420681:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.420789:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.420895:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.421013:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.421124:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.421237:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.421348:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.421475:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.421587:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.421699:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.421808:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.421926:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.422098:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.422238:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.422375:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.422506:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.422620:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.422791:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.422891:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.422990:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.423091:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.423198:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.423299:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.423393:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.423484:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.423593:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.423691:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.423798:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.423908:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
[34633:0421/120750.424009:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or folder (2)
```
Each errors are showing during the same instance of `yarn start` I just separated them to be more readable for you.

**To Reproduce**:
Follow the steps from HACKING.md with a proxy and a firewall on an ubuntu 20.04 linux machine with node v16.14.2 and yarn 1.22.18.

**Comment by Eugeny** [comment]
Have you ran `./scripts/build-native.js`? You also need to re-run it if you've added/removed any dependencies

**Comment by woodmeal** [comment]
> Have you ran `./scripts/build-native.js`? You also need to re-run it if you've added/removed any dependencies

I re-run it with an other proxy with deleting my node_modules and it works, mb for the bother !

**Comment by 13314012171** [comment]
> > Have you ran `./scripts/build-native.js`? You also need to re-run it if you've added/removed any dependencies您是否运行过 ./scripts/build-native.js？
> 
> I re-run it with an other proxy and reinstalled my node_modules and it works, mb for the bother !

I downloaded 'tabby-1.0.181-linux-x64.rpm' and run rpm -ivh tabby-1.0.181-linux-x64.rpm on my new Intranet linux ,then the same problem occurred,Is there anything else I need to do

> > Have you ran `./scripts/build-native.js`? You also need to re-run it if you've added/removed any dependencies
> 
> I re-run it with an other proxy and reinstalled my node_modules and it works, mb for the bother !

I downloaded 'tabby-1.0.181-linux-x64.rpm' and run rpm -ivh tabby-1.0.181-linux-x64.rpm on my new Intranet linux ,then the same problem occurred,Is there anything else I need to do?

**Comment by 13314012171** [comment]
> > Have you ran `./scripts/build-native.js`? You also need to re-run it if you've added/removed any dependencies
> 
> I re-run it with an other proxy and reinstalled my node_modules and it works, mb for the bother !

I downloaded 'tabby-1.0.181-linux-x64.rpm' and run rpm -ivh tabby-1.0.181-linux-x64.rpm on my new Intranet linux ,then the same problem occurred,Is there anything else I need to do?
