### ISSUE TITLE
add plugin error clippy

### ISSUE THREAD

**Issue by XLjavaHome** [Eugeny/tabby#6363]
Version: 1.0.176
Platform: Windows x64 10.0.19042
Plugins: none
Frontend: xterm

add plugin clippy tips   
![image](https://user-images.githubusercontent.com/7547904/167232328-582fe1de-c8b5-4088-be46-e6031ca36466.png)

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by XLjavaHome** [comment]
ERROR Error: Uncaught (in promise): Object: {"message":"request to https://registry.npmmirror.com/tabby-clippy failed, reason: unable to verify the first certificate","type":"system","errno":"UNABLE_TO_VERIFY_LEAF_SIGNATURE","code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE","name":"FetchError","stack":"FetchError: request to https://registry.npmmirror.com/tabby-clippy failed, reason: unable to verify the first certificate\n    at ClientRequest.<anonymous> (D:\\soft\\Tabby\\resources\\app.asar\\node_modules\\npm\\node_modules\\node-fetch-npm\\src\\index.js:68:14)\n    at ClientRequest.emit (node:events:402:35)\n    at ClientRequest.emit (node:domain:475:12)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:390:28)\n    at TLSSocket.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","level":"error"}
FetchError: request to https://registry.npmmirror.com/tabby-clippy failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (D:\soft\Tabby\resources\app.asar\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at resolvePromise (file:///D:/soft/Tabby/resources/app.asar/dist/bundle.js:126779:31)
    at file:///D:/soft/Tabby/resources/app.asar/dist/bundle.js:126686:17
    at rejected (D:\soft\Tabby\resources\builtin-plugins\tabby-plugin-manager\dist\index.js:7964:89)
    at _ZoneDelegate.invoke (file:///D:/soft/Tabby/resources/app.asar/dist/bundle.js:125940:26)
    at Object.onInvoke (file:///D:/soft/Tabby/resources/app.asar/dist/bundle.js:87629:33)
    at _ZoneDelegate.invoke (file:///D:/soft/Tabby/resources/app.asar/dist/bundle.js:125939:52)
    at Zone.run (file:///D:/soft/Tabby/resources/app.asar/dist/bundle.js:125702:43)
    at file:///D:/soft/Tabby/resources/app.asar/dist/bundle.js:126843:36
    at _ZoneDelegate.invokeTask (file:///D:/soft/Tabby/resources/app.asar/dist/bundle.js:125974:31)
    at Object.onInvokeTask (file:///D:/soft/Tabby/resources/app.asar/dist/bundle.js:87616:33)
    at _ZoneDelegate.invokeTask (file:///D:/soft/Tabby/resources/app.asar/dist/bundle.js:125973:60)
    at Zone.runTask (file:///D:/soft/Tabby/resources/app.asar/dist/bundle.js:125746:47)
    at drainMicroTaskQueue (file:///D:/soft/Tabby/resources/app.asar/dist/bundle.js:126153:35)

**Comment by carsweb** [comment]
Facing the same issue with same error from debug console. is there any option to temporarily ignore certificate checks?

**Comment by Dzeng2011** [comment]
I got same error when add new plugins, anyone got a solution to fix it?

**Comment by Dzeng2011** [comment]
here is the errors in DevTools:
core.js:6456 ERROR Error: Uncaught (in promise): Object: {"message":"request to https://registry.npmjs.org/terminus-relaxed-theme failed, reason: unable to get local issuer certificate","type":"system","errno":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY","code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY","name":"FetchError","stack":"FetchError: request to https://registry.npmjs.org/terminus-relaxed-theme failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)\n    at ClientRequest.emit (node:events:539:35)\n    at ClientRequest.emit (node:domain:475:12)\n    at TLSSocket.socketErrorListener (node:_http_client:454:9)\n    at TLSSocket.emit (node:events:527:28)\n    at TLSSocket.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","level":"error"}
FetchError: request to https://registry.npmjs.org/terminus-relaxed-theme failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
    at ClientRequest.emit (node:events:539:35)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at resolvePromise (file:///Applications/Tabby.app/Contents/Resources/app.asar/dist/bundle.js:126782:31)
    at file:///Applications/Tabby.app/Contents/Resources/app.asar/dist/bundle.js:126689:17
    at rejected (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-plugin-manager/dist/index.js:8295:89)
    at _ZoneDelegate.invoke (file:///Applications/Tabby.app/Contents/Resources/app.asar/dist/bundle.js:125943:26)
    at Object.onInvoke (file:///Applications/Tabby.app/Contents/Resources/app.asar/dist/bundle.js:87629:33)
    at _ZoneDelegate.invoke (file:///Applications/Tabby.app/Contents/Resources/app.asar/dist/bundle.js:125942:52)
    at Zone.run (file:///Applications/Tabby.app/Contents/Resources/app.asar/dist/bundle.js:125705:43)
    at file:///Applications/Tabby.app/Contents/Resources/app.asar/dist/bundle.js:126846:36
    at _ZoneDelegate.invokeTask (file:///Applications/Tabby.app/Contents/Resources/app.asar/dist/bundle.js:125977:31)
    at Object.onInvokeTask (file:///Applications/Tabby.app/Contents/Resources/app.asar/dist/bundle.js:87616:33)
    at _ZoneDelegate.invokeTask (file:///Applications/Tabby.app/Contents/Resources/app.asar/dist/bundle.js:125976:60)
    at Zone.runTask (file:///Applications/Tabby.app/Contents/Resources/app.asar/dist/bundle.js:125749:47)
    at drainMicroTaskQueue (file:///Applications/Tabby.app/Contents/Resources/app.asar/dist/bundle.js:126156:35)
