### ISSUE TITLE
not working after upgrade to 1.0.178 

### ISSUE THREAD

**Issue by luasenvy** [Eugeny/tabby#6511]
**Describe the problem**:
tabby not working after upgrade to 1.0.178
```
os: debian 11
wm: xfce4
gpu: gtx1660 super
gpu driver: NVIDIA-SMI 510.68.02    Driver Version: 510.68.02    CUDA Version: 11.6
```

**To Reproduce**:
```
luasenvy@luasenvy:~$ tabby --version
1.0.178
luasenvy@luasenvy:~$ tabby open /home/luasenvy
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: app.disableHardwareAcceleration() can only be called before app is ready
    at new t.Application (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/app.ts:79:17)
    at newWindow (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/index.ts:22:26)
    at App.<anonymous> (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/index.ts:68:30)
(node:4642) UnhandledPromiseRejectionWarning: Error: app.disableHardwareAcceleration() can only be called before app is ready
    at new t.Application (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/app.ts:79:17)
    at newWindow (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/index.ts:22:26)
    at App.<anonymous> (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/index.ts:68:30)
(Use `tabby --trace-warnings ...` to show where the warning was created)
(node:4642) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

temporary solution: set `hacks.disableGPU` to `false` in `~/.config/tabby/config.yaml`

in my case, `hacks.disableGPU` is useful option.
because, webgl is broken when xfce4 screen locked and session restarted. ( power save mode )

thank you

**Comment by piersandro** [comment]
Same problem here
```
os: Manjaro 21.2.6
wm: Cinnamon 5.2.7
gpu: Intel UHD Graphics 620
```

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: app.disableHardwareAcceleration() can only be called before app is ready
    at new t.Application (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/app.ts:74:21)
    at newWindow (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/index.ts:22:26)
    at App.<anonymous> (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/index.ts:68:30)
(node:16691) UnhandledPromiseRejectionWarning: Error: app.disableHardwareAcceleration() can only be called before app is ready
    at new t.Application (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/app.ts:74:21)
    at newWindow (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/index.ts:22:26)
    at App.<anonymous> (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/index.ts:68:30)
(Use `tabby --trace-warnings ...` to show where the warning was created)
(node:16691) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[16732:0530/092514.381759:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.

```

**Comment by thenicholas** [comment]
Same here, won't launch with hacks.disableGPU=true
os: Windows 10 x64 19044.1706
gpu: NVidia Geforce 210
Display driver: 21.21.13.4201

**Comment by larp-welt** [comment]
same for me...

```
Platform: Linux x64 5.15.0-33-generic
Plugins: search-in-browser
Frontend: xterm-webgl
OS: Ubuntu 22.04
WM: Wayland
```

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: app.disableHardwareAcceleration() can only be called before app is ready
    at new t.Application (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/app.ts:74:21)
    at newWindow (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/index.ts:22:26)
    at App.<anonymous> (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/index.ts:68:30)
(node:2401966) UnhandledPromiseRejectionWarning: Error: app.disableHardwareAcceleration() can only be called before app is ready
    at new t.Application (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/app.ts:74:21)
    at newWindow (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/index.ts:22:26)
    at App.<anonymous> (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/index.ts:68:30)
(Use `tabby --trace-warnings ...` to show where the warning was created)
(node:2401966) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2402028:0530/195238.117485:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[2401966:0530/195238.411564:ERROR:nss_util.cc(286)] After loading Root Certs, loaded==false: NSS error code: -8018

```
Setting `hacks.disableGPU=false` didn't work for me.

I downgraded to 1.0.177, and it works fine for me again.

**Comment by luasenvy** [comment]
thank you! [nightly.link](https://nightly.link/Eugeny/tabby/workflows/build/master) version is work! :partying_face:
