### ISSUE TITLE
1.0.179  config sync does not work

### ISSUE THREAD

**Issue by DreamPWJ** [Eugeny/tabby#6548]
![image](https://user-images.githubusercontent.com/16730031/172033201-e6c9b4d6-5816-48a3-86cb-a5714c1d2491.png)
When I use the download function to sync the configuration, it doesn't work at all

**Comment by DreamPWJ** [comment]
How to solve it, the tool is no longer available, because dozens of configurations have been lost, and can only be re-created one by one?

**Comment by wangerzi** [comment]
I got the same problem.o(╥﹏╥)o

**Comment by DreamPWJ** [comment]
> I got the same problem.o(╥﹏╥)o
有解决办法吗？几十个链接不想重建了，直接导致我想弃用了

**Comment by DreamPWJ** [comment]
@Eugeny Please help me, now all configurations are overridden invalid, all connections are no longer working

**Comment by anschein** [comment]
same problem,and I tried web app,also not working🤣

**Comment by anschein** [comment]
> same problem,and I tried web app,also not working🤣

Web app can't delete profiles,Don't know if this link to the sync problem

**Comment by TheFrisianClause** [comment]
I have this problem as well....

**Comment by DraneLixX** [comment]
same....

**Comment by birkanozer** [comment]
> Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Debug logs · Eugeny/tabby Wiki](https://github.com/Eugeny/tabby)**A terminal for a more modern age. Contribute to Eugeny/tabby development by creating an account on GitHub.

I have this error in console.

`core.js:6456 
ERROR Error: Uncaught (in promise): Error: EMFILE: too many open files, open 'C:\Users\<username>\AppData\Roaming\tabby\config.yaml'
Error: EMFILE: too many open files, open 'C:\Users\<username>\AppData\Roaming\tabby\config.yaml
 at resolvePromise (zone.js:1211:1)
    at zone.js:1118:1
    at rejected (C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:11528:89)
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.js:28666:1)
    at _ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1275:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28653:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)`

**Comment by cocox** [comment]
> > Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs
> > > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Debug logs · Eugeny/tabby Wiki](https://github.com/Eugeny/tabby)**A terminal for a more modern age. Contribute to Eugeny/tabby development by creating an account on GitHub.
> 
> I have this error in console.
> 
> `core.js:6456 ERROR Error: Uncaught (in promise): Error: EMFILE: too many open files, open 'C:\Users\<username>\AppData\Roaming\tabby\config.yaml' Error: EMFILE: too many open files, open 'C:\Users\<username>\AppData\Roaming\tabby\config.yaml at resolvePromise (zone.js:1211:1) at zone.js:1118:1 at rejected (C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:11528:89) at _ZoneDelegate.invoke (zone.js:372:1) at Object.onInvoke (core.js:28666:1) at _ZoneDelegate.invoke (zone.js:371:1) at Zone.run (zone.js:134:1) at zone.js:1275:1 at _ZoneDelegate.invokeTask (zone.js:406:1) at Object.onInvokeTask (core.js:28653:1) at _ZoneDelegate.invokeTask (zone.js:405:1) at Zone.runTask (zone.js:178:1) at drainMicroTaskQueue (zone.js:585:1)`

Same error here...

**Comment by DreamPWJ** [comment]
@Eugeny Please pay attention to this issue, it is very important
