### ISSUE TITLE
macOS not create new terminal tab

### ISSUE THREAD

**Issue by gcdsss** [Eugeny/tabby#6684]
Version: 1.0.181
Platform: macOS arm64 21.5.0
Plugins: relaxed-theme, docker
Frontend: xterm

1. shutdown OS and reopen next work day
2. open tabby
3. click `New Terminal` or `Profiles & connections` button
4. the new terminal not create
devtools reports error:
```
Could not read working directory: Error: No such process
    at getWorkingDirectoryFromPID (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/native-process-working-directory/index.js:25:36)
    at Session.<anonymous> (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-local/dist/index.js:5822:96)
    at Generator.next (<anonymous>)
    at /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-local/dist/index.js:5324:71
    at new ZoneAwarePromise (zone.js:1427:1)
    at __awaiter (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-local/dist/index.js:5320:12)
    at Session.getWorkingDirectory (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-local/dist/index.js:5813:16)
    at TerminalTabComponent.<anonymous> (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-local/dist/index.js:5940:59)
    at Generator.next (<anonymous>)
    at /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-local/dist/index.js:5324:71
    at new ZoneAwarePromise (zone.js:1427:1)
    at __awaiter (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-local/dist/index.js:5320:12)
    at TerminalTabComponent.getRecoveryToken (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-local/dist/index.js:5939:16)
    at TabRecoveryService.<anonymous> (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:25966:37)
    at Generator.next (<anonymous>)
    at /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:11530:71
    at new ZoneAwarePromise (zone.js:1427:1)
    at __awaiter (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:11526:12)
    at TabRecoveryService.getFullRecoveryToken (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:25965:16)
    at SplitContainer.<anonymous> (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27588:54)
    at Generator.next (<anonymous>)
    at /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:11530:71
    at new ZoneAwarePromise (zone.js:1427:1)
    at __awaiter (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:11526:12)
    at SplitContainer.serialize (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:27581:16)
    at SplitTabComponent.<anonymous> (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:28065:30)
    at Generator.next (<anonymous>)
    at /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:11530:71
    at new ZoneAwarePromise (zone.js:1427:1)
    at __awaiter (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:11526:12)
    at SplitTabComponent.getRecoveryToken (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:28064:16)
    at TabRecoveryService.<anonymous> (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:25966:37)
    at Generator.next (<anonymous>)
    at /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:11530:71
    at new ZoneAwarePromise (zone.js:1427:1)
    at __awaiter (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:11526:12)
    at TabRecoveryService.getFullRecoveryToken (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:25965:16)
    at AppService.<anonymous> (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:26455:50)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:11527:58)
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.js:28666:1)
    at _ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1275:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28653:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
```

This behavior had been occurred so many time as i upgraded serveral version. Sometime i rebooted OS and it disappear and sometimes it did not.

**Comment by gcdsss** [comment]
update:
 after a while (like 30 minutes), it seems like tabs are frozened...now it just all come out at once.

![image](https://user-images.githubusercontent.com/37131861/175867473-bc1c8297-32fa-4895-85b4-cfa44d9ce083.png)
