### ISSUE TITLE
Build error in macOs Catalina

### ISSUE THREAD

**Issue by wljince007** [Eugeny/tabby#6901]
**Describe the problem**:
[A clear and concise description of what the bug is.]
1. tabby/app/node_modules/@tabby-gang/node-pty:
../src/unix/spawn-helper.cc:48:26: error: use of undeclared identifier 'errno'
2. app/bindings-cpp:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture

**To Reproduce**:
[Steps to reproduce the behavior]
```
➜  tabby git:(master) yarn                                                                                                                                                                                                [1]
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ patch-package && node ./scripts/install-deps.js && node ./scripts/build-native.js
patch-package 6.4.7
Applying patches...
app-builder-lib@22.14.13 ✔
ssh2@1.8.0 ✔

Warning: patch-package detected a patch file version mismatch

  Don't worry! This is probably fine. The patch was still applied
  successfully. Here's the deets:

  Patch file created for

    app-builder-lib@22.14.13

  applied to

    app-builder-lib@23.0.9
  
  At path
  
    node_modules/app-builder-lib

  This warning is just to give you a heads-up. There is a small chance of
  breakage even though the patch was applied successfully. Make sure the package
  still behaves like you expect (you wrote tests, right?) and then run

    patch-package app-builder-lib

  to update the version in the patch file name and make this warning go away.


Warning: patch-package detected a patch file version mismatch

  Don't worry! This is probably fine. The patch was still applied
  successfully. Here's the deets:

  Patch file created for

    ssh2@1.8.0

  applied to

    ssh2@1.10.0
  
  At path
  
    node_modules/ssh2

  This warning is just to give you a heads-up. There is a small chance of
  breakage even though the patch was applied successfully. Make sure the package
  still behaves like you expect (you wrote tests, right?) and then run

    patch-package ssh2

  to update the version in the patch file name and make this warning go away.

---
patch-package finished with 2 warning(s).
info patch 
yarn run v1.22.19
$ /Users/gopath/src/github.com/Eugeny/tabby/node_modules/.bin/patch-package
patch-package 6.4.7
Applying patches...
app-builder-lib@22.14.13 ✔
ssh2@1.8.0 ✔

Warning: patch-package detected a patch file version mismatch

  Don't worry! This is probably fine. The patch was still applied
  successfully. Here's the deets:

  Patch file created for

    app-builder-lib@22.14.13

  applied to

    app-builder-lib@23.0.9
  
  At path
  
    node_modules/app-builder-lib

  This warning is just to give you a heads-up. There is a small chance of
  breakage even though the patch was applied successfully. Make sure the package
  still behaves like you expect (you wrote tests, right?) and then run

    patch-package app-builder-lib

  to update the version in the patch file name and make this warning go away.


Warning: patch-package detected a patch file version mismatch

  Don't worry! This is probably fine. The patch was still applied
  successfully. Here's the deets:

  Patch file created for

    ssh2@1.8.0

  applied to

    ssh2@1.10.0
  
  At path
  
    node_modules/ssh2

  This warning is just to give you a heads-up. There is a small chance of
  breakage even though the patch was applied successfully. Make sure the package
  still behaves like you expect (you wrote tests, right?) and then run

    patch-package ssh2

  to update the version in the patch file name and make this warning go away.

---
patch-package finished with 2 warning(s).
Done in 0.23s.
info deps app
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @electron/remote@2.0.8" has unmet peer dependency "electron@>= 13.0.0".
warning " > electron-promise-ipc@2.2.4" has unmet peer dependency "electron@>= 9.1.2".
warning " > ngx-filesize@2.0.16" has unmet peer dependency "@angular/common@>= 8.0.0".
warning " > ngx-filesize@2.0.16" has unmet peer dependency "@angular/core@>= 8.0.0".
[4/4] Rebuilding all packages...
error /Users/gopath/src/github.com/Eugeny/tabby/app/node_modules/@tabby-gang/node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments: 
Directory: /Users/gopath/src/github.com/Eugeny/tabby/app/node_modules/@tabby-gang/node-pty
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@18.7.0 | darwin | x64
gyp info find Python using Python version 3.9.13 found at "/usr/local/opt/python@3.9/bin/python3.9"
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/usr/local/Cellar/node/18.7.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/gopath/src/github.com/Eugeny/tabby/app/node_modules/@tabby-gang/node-pty/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/18.7.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lw/Library/Caches/node-gyp/18.7.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/lw/Library/Caches/node-gyp/18.7.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/18.7.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/lw/Library/Caches/node-gyp/18.7.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/gopath/src/github.com/Eugeny/tabby/app/node_modules/@tabby-gang/node-pty',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/pty/src/unix/pty.o
In file included from ../src/unix/pty.cc:20:
../../../nan/nan.h:2542:8: warning: 'SetAccessor' is deprecated: Do signature check in accessor [-Wdeprecated-declarations]
  tpl->SetAccessor(
       ^
/Users/lw/Library/Caches/node-gyp/18.7.0/include/node/v8-template.h:837:3: note: 'SetAccessor' has been explicitly marked deprecated here
  V8_DEPRECATED("Do signature check in accessor")
  ^
/Users/lw/Library/Caches/node-gyp/18.7.0/include/node/v8config.h:460:35: note: expanded from macro 'V8_DEPRECATED'
# define V8_DEPRECATED(message) [[deprecated(message)]]
                                  ^
1 warning generated.
  SOLINK_MODULE(target) Release/pty.node
ld: warning: directory not found for option '-L/usr/local/opt/zlib/lib'
  CXX(target) Release/obj.target/spawn-helper/src/unix/spawn-helper.o
../src/unix/spawn-helper.cc:48:26: error: use of undeclared identifier 'errno'
    bail(COMM_ERR_CHDIR, errno);
                         ^
../src/unix/spawn-helper.cc:51:27: error: use of undeclared identifier 'errno'
    bail(COMM_ERR_SETUID, errno);
                          ^
../src/unix/spawn-helper.cc:54:27: error: use of undeclared identifier 'errno'
    bail(COMM_ERR_SETGID, errno);
                          ^
../src/unix/spawn-helper.cc:67:23: error: use of undeclared identifier 'errno'
  bail(COMM_ERR_EXEC, errno);
                      ^
4 errors generated.
make: *** [Release/obj.target/spawn-helper/src/unix/spawn-helper.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/18.7.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node/18.7.0/bin/node" "/usr/local/Cellar/node/18.7.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/gopath/src/github.com/Eugeny/tabby/app/node_modules/@tabby-gang/node-pty
gyp ERR! node -v v18.7.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn install v1.22.19
warning package.json: No license field
warning tabby-web-container@1.0.171-nightly.3: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
$ patch-package
patch-package 6.4.7
Applying patches...
browserify-sign@4.2.1 ✔
Done in 0.59s.
yarn run v1.22.19
warning package.json: No license field
$ /Users/gopath/src/github.com/Eugeny/tabby/web/node_modules/.bin/patch-package
patch-package 6.4.7
Applying patches...
browserify-sign@4.2.1 ✔
Done in 0.22s.
info deps tabby-core
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @ngx-translate/core@14.0.0" has unmet peer dependency "@angular/core@>=13.0.0".
warning " > @ngx-translate/core@14.0.0" has unmet peer dependency "rxjs@^6.5.3 || ^7.4.0".
warning " > bootstrap@4.5.3" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.5.3" has unmet peer dependency "popper.js@^1.16.1".
warning " > ngx-filesize@2.0.16" has unmet peer dependency "@angular/common@>= 8.0.0".
warning " > ngx-filesize@2.0.16" has unmet peer dependency "@angular/core@>= 8.0.0".
warning " > ngx-perfect-scrollbar@10.1.1" has unmet peer dependency "@angular/common@>=9.0.0".
warning " > ngx-perfect-scrollbar@10.1.1" has unmet peer dependency "@angular/core@>=9.0.0".
warning " > ngx-translate-messageformat-compiler@4.11.0" has unmet peer dependency "@angular/core@^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0".
warning " > ngx-translate-messageformat-compiler@4.11.0" has incorrect peer dependency "@ngx-translate/core@^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0".
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 0.23s.
info deps tabby-settings
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 0.70s.
info deps tabby-terminal
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > ngx-colors@3.0.4" has unmet peer dependency "@angular/common@>=10.0.4".
warning " > ngx-colors@3.0.4" has unmet peer dependency "@angular/core@>=10.0.4".
warning " > ngx-colors@3.0.4" has unmet peer dependency "@angular/animations@>=10.0.4".
warning " > ngx-colors@3.0.4" has unmet peer dependency "@angular/forms@>=10.0.4".
warning " > xterm-addon-image@0.1.0" has incorrect peer dependency "xterm@~4.18.0".
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 0.30s.
info deps tabby-web
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > bootstrap@4.6.0" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.6.0" has unmet peer dependency "popper.js@^1.16.1".
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 0.32s.
info deps tabby-community-color-schemes
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 0.07s.
info deps tabby-ssh
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
$ run-script-os
yarn run v1.22.19
$ exit
Done in 0.05s.
Done in 0.60s.
info deps tabby-serial
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 0.13s.
info deps tabby-telnet
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 0.10s.
info deps tabby-electron
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > electron-promise-ipc@2.2.4" has unmet peer dependency "electron@>= 9.1.2".
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 0.30s.
info deps tabby-local
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 0.12s.
info deps tabby-plugin-manager
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 0.15s.
info deps tabby-linkifier
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 0.09s.
info deps web
yarn install v1.22.19
warning package.json: No license field
warning tabby-web-container@1.0.171-nightly.3: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
$ patch-package
patch-package 6.4.7
Applying patches...
browserify-sign@4.2.1 ✔
Done in 0.73s.
info deps tabby-web-demo
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 0.14s.
Building against Electron 19.0.6
Rebuilding app/bindings-cpp
  CXX(target) Release/obj.target/bindings/src/serialport.o
In file included from ../src/serialport.cpp:1:
In file included from ../src/./serialport.h:11:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdio.h:107:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:68:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
#error Unsupported architecture
 ^
In file included from ../src/serialport.cpp:1:
In file included from ../src/./serialport.h:11:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdio.h:107:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:27:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:33:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
#error architecture not supported
 ^
In file included from ../src/serialport.cpp:1:
In file included from ../src/./serialport.h:11:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdio.h:107:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:27:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
        ^
note: '__int128_t' declared here
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
typedef __int32_t       __darwin_dev_t;         /* dev_t */
        ^
note: '__int128_t' declared here
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */
        ^
note: '__uint128_t' declared here
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/
        ^
note: '__uint128_t' declared here
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'
typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'; did you mean '__uint128_t'?
typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */
        ^
note: '__uint128_t' declared here
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'
typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */
        ^
note: '__int128_t' declared here
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */
        ^
note: '__uint128_t' declared here
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */
        ^
note: '__int128_t' declared here
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */
        ^
note: '__uint128_t' declared here
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */
        ^
note: '__uint128_t' declared here
In file included from ../src/serialport.cpp:1:
In file included from ../src/./serialport.h:11:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdio.h:107:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:43:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
typedef __uint32_t      __darwin_wctype_t;
        ^
note: '__uint128_t' declared here
In file included from ../src/serialport.cpp:1:
In file included from ../src/./serialport.h:11:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdio.h:107:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:75:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types/_va_list.h:31:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
#error architecture not supported
 ^
In file included from ../src/serialport.cpp:1:
In file included from ../src/./serialport.h:11:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdio.h:107:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:75:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types/_va_list.h:32:9: error: unknown type name '__darwin_va_list'
typedef __darwin_va_list va_list;
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/bindings/src/serialport.o] Error 1
Error: node-gyp failed to rebuild '/Users/gopath/src/github.com/Eugeny/tabby/app/node_modules/@serialport/bindings-cpp'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `make` failed with exit code: 2


    at NodeGyp.rebuildModule (/Users/gopath/src/github.com/Eugeny/tabby/node_modules/electron-rebuild/lib/src/module-type/node-gyp.js:117:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ModuleRebuilder.rebuildNodeGypModule (/Users/gopath/src/github.com/Eugeny/tabby/node_modules/electron-rebuild/lib/src/module-rebuilder.js:94:9)
    at async ModuleRebuilder.rebuild (/Users/gopath/src/github.com/Eugeny/tabby/node_modules/electron-rebuild/lib/src/module-rebuilder.js:124:14)
    at async Rebuilder.rebuildModuleAt (/Users/gopath/src/github.com/Eugeny/tabby/node_modules/electron-rebuild/lib/src/rebuild.js:145:13)
    at async Rebuilder.rebuild (/Users/gopath/src/github.com/Eugeny/tabby/node_modules/electron-rebuild/lib/src/rebuild.js:108:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by wljince007** [comment]
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdio.h:9
在｀#if defined(__need_FILE) || defined(__need___FILE)｀前面，增加如下两行：
#include <errno.h>
#define __x86_64__ 1

/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:803
在｀#if !defined(__sys_cdefs_arch_unknown__) && defined(__i386__)｀前面，增加如下一行
#define __x86_64__ 1

**Comment by wljince007** [comment]
compile　succ
