### ISSUE TITLE
how to send command to console with quick command plugin

### ISSUE THREAD

**Issue by walleliu1016** [Eugeny/tabby#6941]
**Describe the problem**:
I install the quickcommand plugin, and add some quick command, but can not send to console by click on command or ctrl+enter or enter, the command string can not work.

**To Reproduce**:
![image](https://user-images.githubusercontent.com/8541378/183549062-d6f99551-dcfb-4167-802e-e9e29aec15c9.png)

**Comment by amajauskas** [comment]
Can confirm that quick commands seems to be broken I believe since 1.0.181.

Whenever I try to click on a quick command I get this error in console log:

> core.js:6456 ERROR TypeError: Right-hand side of 'instanceof' is not an object
    at l._send (C:\Users\am-work\AppData\Roaming\tabby\plugins\node_modules\terminus-elastic-quick-commands\dist\index.js:43:1293)
    at l._send (C:\Users\am-work\AppData\Roaming\tabby\plugins\node_modules\terminus-elastic-quick-commands\dist\index.js:43:1264)
    at l.send (C:\Users\am-work\AppData\Roaming\tabby\plugins\node_modules\terminus-elastic-quick-commands\dist\index.js:43:1654)
    at Object.eval [as handleEvent] (l.ngfactory.js:20:23)
    at Object.handleEvent (file:///C:/Program%20Files%20(x86)/Tabby/resources/app.asar/dist/bundle.js:90665:89)
    at Object.handleEvent (file:///C:/Program%20Files%20(x86)/Tabby/resources/app.asar/dist/bundle.js:91217:70)
    at dispatchEvent (file:///C:/Program%20Files%20(x86)/Tabby/resources/app.asar/dist/bundle.js:82532:25)
    at file:///C:/Program%20Files%20(x86)/Tabby/resources/app.asar/dist/bundle.js:89870:23
    at HTMLDivElement.<anonymous> (file:///C:/Program%20Files%20(x86)/Tabby/resources/app.asar/dist/bundle.js:105470:38)
    at _ZoneDelegate.invokeTask (file:///C:/Program%20Files%20(x86)/Tabby/resources/app.asar/dist/bundle.js:125977:31)
    at Object.onInvokeTask (file:///C:/Program%20Files%20(x86)/Tabby/resources/app.asar/dist/bundle.js:87616:33)
    at _ZoneDelegate.invokeTask (file:///C:/Program%20Files%20(x86)/Tabby/resources/app.asar/dist/bundle.js:125976:60)
    at Zone.runTask (file:///C:/Program%20Files%20(x86)/Tabby/resources/app.asar/dist/bundle.js:125749:47)
    at ZoneTask.invokeTask [as invoke] (file:///C:/Program%20Files%20(x86)/Tabby/resources/app.asar/dist/bundle.js:126058:34)
    at invokeTask (file:///C:/Program%20Files%20(x86)/Tabby/resources/app.asar/dist/bundle.js:127219:18)
    at globalCallback (file:///C:/Program%20Files%20(x86)/Tabby/resources/app.asar/dist/bundle.js:127250:29)
    at HTMLDivElement.globalZoneAwareCallback (file:///C:/Program%20Files%20(x86)/Tabby/resources/app.asar/dist/bundle.js:127283:16)
    at HTMLDivElement.sentryWrapped (C:\Program Files (x86)\Tabby\resources\app.asar\dist\sentry.js:3891:23)
defaultErrorLogger @ core.js:6456
handleError @ core.js:6504
dispatchEvent @ core.js:23573
(anonymous) @ core.js:30907
(anonymous) @ platform-browser.js:545
invokeTask @ zone.js:406
onInvokeTask @ core.js:28653
invokeTask @ zone.js:405
runTask @ zone.js:178
invokeTask @ zone.js:487
invokeTask @ zone.js:1648
globalCallback @ zone.js:1679
globalZoneAwareCallback @ zone.js:1712
sentryWrapped @ helpers.js:72

I use "elastic-quick-commands" by Domain - ver 1.1.1

Not sure if thats supported by Termius would love to hear if other people have had no issues with other quick command plugins - I use them quite a lot so would be great to have it working.

**Comment by MajorTomDE** [comment]
Confirm. The plugin "elastic-quick-commands" is broken. It's not possible to insert saved commends into a terminal.

**Comment by amajauskas** [comment]
Ive since found out that the "quick-cmds" by minyoad works fine.
