### ISSUE TITLE
can not open profile and connection

### ISSUE THREAD

**Issue by 1369521908** [Eugeny/tabby#7156]
**Describe the problem**:
click the tab button '+' or 'Profile & Connection' but no response
here is the console log on DevTool
```
core.js:6456 ERROR Error: Uncaught (in promise): true
    at resolvePromise (zone.js:1211:1)
    at zone.js:1118:1
    at zone.js:1134:1
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.js:28666:1)
    at _ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1275:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28653:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
```

**To Reproduce**:
1. open Tabby
2. click the tab button '+' or 'Profile & Connection' but no response

**Comment by 1369521908** [comment]
here is the env

Version: 1.0.183
Platform: Windows x64 10.0.19044
Plugins: none
Frontend: xterm

**Comment by 1369521908** [comment]
<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="webpack://tabby/node_modules/@angular/core/fesm2015/core.js:6456" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">core.js:6456</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">ERROR <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">Error: Uncaught (in promise): true
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at resolvePromise (<span class="devtools-link" role="link" tabindex="-1" title="webpack://tabby/node_modules/zone.js/fesm2015/zone.js:1211:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">zone.js:1211:1</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link" role="link" tabindex="-1" title="webpack://tabby/node_modules/zone.js/fesm2015/zone.js:1118:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">zone.js:1118:1</span>
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at rejected (<span class="devtools-link" role="link" tabindex="-1" title="F:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:11528:89" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">F:\Program Files\Tab<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>t\index.js:11528:89</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at _ZoneDelegate.invoke (<span class="devtools-link" role="link" tabindex="-1" title="webpack://tabby/node_modules/zone.js/fesm2015/zone.js:372:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">zone.js:372:1</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Object.onInvoke (<span class="devtools-link" role="link" tabindex="-1" title="webpack://tabby/node_modules/@angular/core/fesm2015/core.js:28666:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">core.js:28666:1</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at _ZoneDelegate.invoke (<span class="devtools-link" role="link" tabindex="-1" title="webpack://tabby/node_modules/zone.js/fesm2015/zone.js:371:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">zone.js:371:1</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Zone.run (<span class="devtools-link" role="link" tabindex="-1" title="webpack://tabby/node_modules/zone.js/fesm2015/zone.js:134:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">zone.js:134:1</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link" role="link" tabindex="-1" title="webpack://tabby/node_modules/zone.js/fesm2015/zone.js:1275:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">zone.js:1275:1</span>
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at _ZoneDelegate.invokeTask (<span class="devtools-link" role="link" tabindex="-1" title="webpack://tabby/node_modules/zone.js/fesm2015/zone.js:406:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">zone.js:406:1</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Object.onInvokeTask (<span class="devtools-link" role="link" tabindex="-1" title="webpack://tabby/node_modules/@angular/core/fesm2015/core.js:28653:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">core.js:28653:1</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at _ZoneDelegate.invokeTask (<span class="devtools-link" role="link" tabindex="-1" title="webpack://tabby/node_modules/zone.js/fesm2015/zone.js:405:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">zone.js:405:1</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Zone.runTask (<span class="devtools-link" role="link" tabindex="-1" title="webpack://tabby/node_modules/zone.js/fesm2015/zone.js:178:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">zone.js:178:1</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at drainMicroTaskQueue (<span class="devtools-link" role="link" tabindex="-1" title="webpack://tabby/node_modules/zone.js/fesm2015/zone.js:585:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">zone.js:585:1</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size:12px; --monospace-font-family:consolas,lucida console,courier new,monospace; --source-code-font-size:12px; --source-code-font-family:consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">

  | defaultErrorLogger | @ | core.js:6456
-- | -- | -- | --
  | handleError | @ | core.js:6504
  | next | @ | core.js:29269
  | __webpack_modules__.85125.ConsumerObserver.next | @ | Subscriber.js:113
  | __webpack_modules__.85125.Subscriber._next | @ | Subscriber.js:80
  | __webpack_modules__.85125.Subscriber.next | @ | Subscriber.js:51
  | (anonymous) | @ | Subject.js:69
  | errorContext | @ | errorContext.js:22
  | __webpack_modules__.63032.Subject.next | @ | Subject.js:59
  | emit | @ | core.js:25946
  | (anonymous) | @ | core.js:28692
  | invoke | @ | zone.js:372
  | run | @ | zone.js:134
  | runOutsideAngular | @ | core.js:28565
  | onHandleError | @ | core.js:28692
  | handleError | @ | zone.js:376
  | runGuarded | @ | zone.js:147
  | api.microtaskDrainDone | @ | zone.js:1072
  | drainMicroTaskQueue | @ | zone.js:592
  | Promise.then (async) |   |  
  | nativeScheduleMicroTask | @ | zone.js:561
  | scheduleMicroTask | @ | zone.js:572
  | scheduleTask | @ | zone.js:396
  | onScheduleTask | @ | zone.js:283
  | scheduleTask | @ | zone.js:386
  | scheduleTask | @ | zone.js:221
  | scheduleMicroTask | @ | zone.js:241
  | scheduleResolveOrReject | @ | zone.js:1265
  | resolvePromise | @ | zone.js:1202
  | (anonymous) | @ | zone.js:1118
  | Promise.then (async) |   |  
  | (anonymous) | @ | zone.js:1496
  | ZoneAwarePromise | @ | zone.js:1427
  | Ctor.then | @ | zone.js:1495
  | resolvePromise | @ | zone.js:1169
  | (anonymous) | @ | zone.js:1118
  | (anonymous) | @ | F:\Program Files\Tab…\dist\index.js:5319
  | ZoneAwarePromise | @ | zone.js:1427
  | adopt | @ | F:\Program Files\Tab…\dist\index.js:5319
  | step | @ | F:\Program Files\Tab…\dist\index.js:5323
  | fulfilled | @ | F:\Program Files\Tab…\dist\index.js:5321
  | invoke | @ | zone.js:372
  | onInvoke | @ | core.js:28666
  | invoke | @ | zone.js:371
  | run | @ | zone.js:134
  | (anonymous) | @ | zone.js:1275
  | invokeTask | @ | zone.js:406
  | onInvokeTask | @ | core.js:28653
  | invokeTask | @ | zone.js:405
  | runTask | @ | zone.js:178
  | drainMicroTaskQueue | @ | zone.js:585
  | Promise.then (async) |   |  
  | nativeScheduleMicroTask | @ | zone.js:561
  | scheduleMicroTask | @ | zone.js:572
  | scheduleTask | @ | zone.js:396
  | onScheduleTask | @ | zone.js:283
  | scheduleTask | @ | zone.js:386
  | scheduleTask | @ | zone.js:221
  | scheduleMicroTask | @ | zone.js:241
  | scheduleResolveOrReject | @ | zone.js:1265
  | resolvePromise | @ | zone.js:1202
  | (anonymous) | @ | zone.js:1118
  | Promise.then (async) |   |  
  | (anonymous) | @ | zone.js:1496
  | ZoneAwarePromise | @ | zone.js:1427
  | Ctor.then | @ | zone.js:1495
  | resolvePromise | @ | zone.js:1169
  | (anonymous) | @ | zone.js:1118
  | (anonymous) | @ | F:\Program Files\Tab…\dist\index.js:5319
  | ZoneAwarePromise | @ | zone.js:1427
  | adopt | @ | F:\Program Files\Tab…\dist\index.js:5319
  | step | @ | F:\Program Files\Tab…\dist\index.js:5323
  | (anonymous) | @ | F:\Program Files\Tab…\dist\index.js:5324
  | ZoneAwarePromise | @ | zone.js:1427
  | __awaiter | @ | F:\Program Files\Tab…\dist\index.js:5320
  | getPowerShellPath | @ | F:\Program Files\Tab…\dist\index.js:7278
  | (anonymous) | @ | F:\Program Files\Tab…\dist\index.js:7266
  | (anonymous) | @ | F:\Program Files\Tab…\dist\index.js:5324
  | ZoneAwarePromise | @ | zone.js:1427
  | __awaiter | @ | F:\Program Files\Tab…\dist\index.js:5320
  | provide | @ | F:\Program Files\Tab…\dist\index.js:7236
  | (anonymous) | @ | F:\Program Files\Tab…\dist\index.js:7333
  | (anonymous) | @ | F:\Program Files\Tab…\dist\index.js:7333
  | (anonymous) | @ | F:\Program Files\Tab…\dist\index.js:5324
  | ZoneAwarePromise | @ | zone.js:1427
  | __awaiter | @ | F:\Program Files\Tab…\dist\index.js:5320
  | provide | @ | F:\Program Files\Tab…\dist\index.js:7328
  | (anonymous) | @ | F:\Program Files\Tab…\dist\index.js:7647
  | (anonymous) | @ | F:\Program Files\Tab…\dist\index.js:7647
  | (anonymous) | @ | F:\Program Files\Tab…\dist\index.js:5324
  | ZoneAwarePromise | @ | zone.js:1427
  | __awaiter | @ | F:\Program Files\Tab…\dist\index.js:5320
  | getShells | @ | F:\Program Files\Tab…\dist\index.js:7646
  | (anonymous) | @ | F:\Program Files\Tab…\dist\index.js:7612
  | (anonymous) | @ | F:\Program Files\Tab…\dist\index.js:5324
  | ZoneAwarePromise | @ | zone.js:1427
  | __awaiter | @ | F:\Program Files\Tab…\dist\index.js:5320
  | getBuiltinProfiles | @ | F:\Program Files\Tab…\dist\index.js:7611
  | (anonymous) | @ | F:\Program Files\Tab…dist\index.js:26966
  | (anonymous) | @ | F:\Program Files\Tab…dist\index.js:26966
  | (anonymous) | @ | F:\Program Files\Tab…dist\index.js:11530
  | ZoneAwarePromise | @ | zone.js:1427
  | __awaiter | @ | F:\Program Files\Tab…dist\index.js:11526
  | getProfiles | @ | F:\Program Files\Tab…dist\index.js:26965
  | (anonymous) | @ | F:\Program Files\Tab…dist\index.js:27025
  | (anonymous) | @ | F:\Program Files\Tab…dist\index.js:11530
  | ZoneAwarePromise | @ | zone.js:1427
  | __awaiter | @ | F:\Program Files\Tab…dist\index.js:11526
  | (anonymous) | @ | F:\Program Files\Tab…dist\index.js:27002
  | ZoneAwarePromise | @ | zone.js:1427
  | showProfileSelector | @ | F:\Program Files\Tab…dist\index.js:27002
  | (anonymous) | @ | F:\Program Files\Tab…dist\index.js:30329
  | (anonymous) | @ | F:\Program Files\Tab…dist\index.js:11530
  | ZoneAwarePromise | @ | zone.js:1427
  | __awaiter | @ | F:\Program Files\Tab…dist\index.js:11526
  | activate | @ | F:\Program Files\Tab…dist\index.js:30328
  | click | @ | F:\Program Files\Tab…dist\index.js:30342
  | eval | @ | StartPageComponent.ngfactory.js:11
  | handleEvent | @ | core.js:31702
  | handleEvent | @ | core.js:32254
  | dispatchEvent | @ | core.js:23569
  | (anonymous) | @ | core.js:30907
  | (anonymous) | @ | platform-browser.js:545
  | invokeTask | @ | zone.js:406
  | onInvokeTask | @ | core.js:28653
  | invokeTask | @ | zone.js:405
  | runTask | @ | zone.js:178
  | invokeTask | @ | zone.js:487
  | invokeTask | @ | zone.js:1648
  | globalCallback | @ | zone.js:1679
  | globalZoneAwareCallback | @ | zone.js:1712
  | sentryWrapped | @ | helpers.js:72

</span></div>
</body>
</html>
