### ISSUE TITLE
After opening the config sync, it is stuck, unable to switch between pages

### ISSUE THREAD

**Issue by muzisooyaaa** [Eugeny/tabby#7160]
Version: 1.0.183
Platform: Windows x64 10.0.19044
Plugins: none
Frontend: xterm

**Comment by muzisooyaaa** [comment]
![b2a6c13b7f3bbccebf574af6f25978d](https://user-images.githubusercontent.com/100553955/191908269-f86c0b49-5d6e-4914-b54e-76392b039c23.jpg)

**Comment by muzisooyaaa** [comment]
![855f23acdebcec84056b0d49fdc1ae9](https://user-images.githubusercontent.com/100553955/191908304-9e402b85-aac1-4448-bbe2-a8bb7eb18027.png)

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by muzisooyaaa** [comment]
ERROR TypeError: _a.find is not a function
    at ConfigSyncSettingsTabComponent.hasMatchingRemoteConfig (D:\Program Files\Tabby\resources\builtin-plugins\tabby-settings\dist\index.js:15158:79)
    at Object.eval [as updateDirectives] (ConfigSyncSettingsTabComponent.ngfactory.js:439:26)
    at Object.updateDirectives (core.js:32255:1)
    at checkAndUpdateView (core.js:31910:1)
    at callViewAction (core.js:32161:1)
    at execEmbeddedViewsAction (core.js:32114:1)
    at execProjectedViewsAction (core.js:32179:1)
    at callViewAction (core.js:32164:1)
    at execEmbeddedViewsAction (core.js:32114:1)
    at execProjectedViewsAction (core.js:32179:1)
    at callViewAction (core.js:32164:1)
    at execEmbeddedViewsAction (core.js:32114:1)
    at execProjectedViewsAction (core.js:32179:1)
    at callViewAction (core.js:32154:1)
    at execComponentViewsAction (core.js:32093:1)
    at checkAndUpdateView (core.js:31916:1)
    at callViewAction (core.js:32151:1)
    at execComponentViewsAction (core.js:32093:1)
    at checkAndUpdateView (core.js:31916:1)
    at callViewAction (core.js:32151:1)
    at execEmbeddedViewsAction (core.js:32114:1)
    at checkAndUpdateView (core.js:31911:1)
    at callViewAction (core.js:32151:1)
    at execComponentViewsAction (core.js:32093:1)
    at checkAndUpdateView (core.js:31916:1)
    at callViewAction (core.js:32151:1)
    at execEmbeddedViewsAction (core.js:32114:1)
    at checkAndUpdateView (core.js:31911:1)
    at callViewAction (core.js:32151:1)
    at execEmbeddedViewsAction (core.js:32114:1)
    at checkAndUpdateView (core.js:31911:1)
    at callViewAction (core.js:32151:1)
    at execEmbeddedViewsAction (core.js:32114:1)
    at checkAndUpdateView (core.js:31911:1)
    at callViewAction (core.js:32151:1)
    at execComponentViewsAction (core.js:32093:1)
    at checkAndUpdateView (core.js:31916:1)
    at callViewAction (core.js:32151:1)
    at execComponentViewsAction (core.js:32093:1)
    at checkAndUpdateView (core.js:31916:1)
    at callViewAction (core.js:32151:1)
    at execEmbeddedViewsAction (core.js:32114:1)
    at checkAndUpdateView (core.js:31911:1)
    at callViewAction (core.js:32151:1)
    at execComponentViewsAction (core.js:32093:1)
    at checkAndUpdateView (core.js:31916:1)
    at callViewAction (core.js:32151:1)
    at execEmbeddedViewsAction (core.js:32114:1)
    at checkAndUpdateView (core.js:31911:1)
    at callViewAction (core.js:32151:1)

**Comment by Eugeny** [comment]
![image](https://user-images.githubusercontent.com/161476/192607891-e9f83806-93ca-4f6b-8e30-a63aaff568a3.png)

Could you please also enable verbose logging and check what response is logged for the `GET /api/1/configs` is?

**Comment by bepstein111** [comment]
Same issue. I have my sync configured, and now I can't change anything, and it even happens on new installs on new PCs that I'm trying to set up with config sync.
