### ISSUE TITLE
Copy on select and right-mouse past not working. 

### ISSUE THREAD

**Issue by jrunser** [Eugeny/tabby#7259]
Version: 1.0.184
Platform: Windows x64 10.0.22621
Plugins: none
Frontend: xterm

**Comment by Eugeny** [comment]
Please elaborate

**Comment by Gaibhne** [comment]
After the update to that version I can confirm that right click paste just stopped working completely. Tried in both SSH as well as `cmd.exe` windows. Just nothing happens at all on right click. Copy on select seems to still work for me.

Possibly related: after I start a new connection/tab, I still have to click the tab for it to actually 'connect', otherwise it just sits there as a black, unconnected view. Also started to happen in this version. If it turns out to be unrelated I'll open a new issue.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by Gaibhne** [comment]
The `ctrl+shift+i` hotkey did not work for me (on Windows). Going via Settings did - these logs are from opening an SSH window; right click does not trigger any additional log lines:

```
C:\Users\me\AppData\Roaming\tabby\plugins\node_modules\tabby-docker\dist\index.js:1205 Could not load Docker containers: Error: write EPROTO 2283272:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at __node_internal_errnoException (node:internal/errors:594:12)
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
(anonymous) @ C:\Users\me\AppData\Roaming\tabby\plugins\node_modules\tabby-docker\dist\index.js:1205
rejected @ C:\Users\me\AppData\Roaming\tabby\plugins\node_modules\tabby-docker\dist\index.js:1169
invoke @ zone.js:372
onInvoke @ core.js:28666
invoke @ zone.js:371
run @ zone.js:134
(anonymous) @ zone.js:1275
invokeTask @ zone.js:406
onInvokeTask @ core.js:28653
invokeTask @ zone.js:405
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:585
processTicksAndRejections @ node:internal/process/task_queues:96
Promise.then (async)
nativeScheduleMicroTask @ zone.js:561
scheduleMicroTask @ zone.js:572
scheduleTask @ zone.js:396
onScheduleTask @ zone.js:283
scheduleTask @ zone.js:386
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1265
resolvePromise @ zone.js:1202
(anonymous) @ zone.js:1118
(anonymous) @ C:\Users\me\AppData\Roaming\tabby\plugins\node_modules\tabby-docker\dist\index.js:6035
Modem.buildPayload @ C:\Users\me\AppData\Roaming\tabby\plugins\node_modules\tabby-docker\dist\index.js:4181
(anonymous) @ C:\Users\me\AppData\Roaming\tabby\plugins\node_modules\tabby-docker\dist\index.js:4163
emit @ node:events:526
socketErrorListener @ node:_http_client:442
emit @ node:events:526
emitErrorNT @ node:internal/streams/destroy:157
emitErrorCloseNT @ node:internal/streams/destroy:122
processTicksAndRejections @ node:internal/process/task_queues:83
undefined:1          GET file:///C:/Users/me/AppData/Local/Programs/Tabby/resources/app.asar/dist/undefined net::ERR_FILE_NOT_FOUND
core.js:6456 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'onShowLinkUnderline')
TypeError: Cannot read properties of undefined (reading 'onShowLinkUnderline')
    at new e (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:6512:51379)
    at new e (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:6512:13068)
    at t.activate (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:6512:86683)
    at t.AddonManager.loadAddon (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:6523:241179)
    at e.Terminal.loadAddon (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:6523:270531)
    at XTermWebGLFrontend.<anonymous> (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:13973:28)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11135:58)
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.js:28666:1)
    at _ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1275:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28653:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
    at invokeTask (zone.js:491:1)
    at ZoneTask.invoke (zone.js:476:1)
    at data.args.<computed> (zone.js:2358:1)
    at sentryWrapped (helpers.js:72:1)
    at resolvePromise (zone.js:1211:1)
    at zone.js:1118:1
    at rejected (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11136:89)
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.js:28666:1)
    at _ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1275:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28653:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
    at invokeTask (zone.js:491:1)
    at ZoneTask.invoke (zone.js:476:1)
    at data.args.<computed> (zone.js:2358:1)
    at sentryWrapped (helpers.js:72:1)
defaultErrorLogger @ core.js:6456
handleError @ core.js:6504
next @ core.js:29269
__webpack_modules__.85125.ConsumerObserver.next @ Subscriber.js:113
__webpack_modules__.85125.Subscriber._next @ Subscriber.js:80
__webpack_modules__.85125.Subscriber.next @ Subscriber.js:51
(anonymous) @ Subject.js:69
errorContext @ errorContext.js:22
__webpack_modules__.63032.Subject.next @ Subject.js:59
emit @ core.js:25946
(anonymous) @ core.js:28692
invoke @ zone.js:372
run @ zone.js:134
runOutsideAngular @ core.js:28565
onHandleError @ core.js:28692
handleError @ zone.js:376
runGuarded @ zone.js:147
api.microtaskDrainDone @ zone.js:1072
drainMicroTaskQueue @ zone.js:592
invokeTask @ zone.js:491
ZoneTask.invoke @ zone.js:476
data.args.<computed> @ zone.js:2358
sentryWrapped @ helpers.js:72
setTimeout (async)
(anonymous) @ trycatch.js:86
scheduleTask @ zone.js:2360
scheduleTask @ zone.js:393
onScheduleTask @ zone.js:283
scheduleTask @ zone.js:386
scheduleTask @ zone.js:221
scheduleMacroTask @ zone.js:244
scheduleMacroTaskWithCurrentZone @ zone.js:683
(anonymous) @ zone.js:2402
proto.<computed> @ zone.js:973
(anonymous) @ C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:13970
ZoneAwarePromise @ zone.js:1427
(anonymous) @ C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:13970
(anonymous) @ C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11138
ZoneAwarePromise @ zone.js:1427
__awaiter @ C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11134
attach @ C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:13964
(anonymous) @ C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:14533
(anonymous) @ C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11138
ZoneAwarePromise @ zone.js:1427
__awaiter @ C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11134
(anonymous) @ C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:14530
timer @ zone.js:2378
invokeTask @ zone.js:406
onInvokeTask @ core.js:28653
invokeTask @ zone.js:405
runTask @ zone.js:178
invokeTask @ zone.js:487
ZoneTask.invoke @ zone.js:476
data.args.<computed> @ zone.js:2358
processImmediate @ node:internal/timers:466
C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19983 [ssh-localhost-2223]  !  Agent auth selected, but no running agent is detected
C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19983 [ssh-localhost-2223] Host key fingerprint:
C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19983 [ssh-localhost-2223]  ecdsa-sha2-nistp256  ey+iPFb48xM7k4nk/j2rGn1bX4iiIIV+IF+DfO7ipgQ= 
C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19983 [ssh-localhost-2223] Handshake complete: {kex: 'curve25519-sha256', serverHostKey: 'ecdsa-sha2-nistp256', cs: {…}, sc: {…}}
C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19983 [ssh-localhost-2223] Loading private key: C:\Users\me\.ssh\id_rsa.key
```

**Comment by Gaibhne** [comment]
I noticed the Docker error and disabled the Docker plugin; that made the error message disappear, but I still can't paste.

**Comment by mojr13** [comment]
Same issue, when the settings is set to display context menu - No context menu on right click.

**Comment by john-f** [comment]
Ok, so I was able to fix this by switching the frontend from "xterm (WebGL)" to just "xterm".

I believe the issue may be related to this error (which only happens when using "xterm WebGL"):

```
core.js:6456 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'onShowLinkUnderline')
TypeError: Cannot read properties of undefined (reading 'onShowLinkUnderline')
    at new e (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:6512:51379)
    at new e (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:6512:13068)
    at t.activate (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:6512:86683)
    at t.AddonManager.loadAddon (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:6523:241179)
    at e.Terminal.loadAddon (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:6523:270531)
    at XTermWebGLFrontend.<anonymous> (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:13973:28)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11135:58)
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.js:28666:1)
    at _ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1275:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28653:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
    at invokeTask (zone.js:491:1)
    at ZoneTask.invoke (zone.js:476:1)
    at data.args.<computed> (zone.js:2358:1)
    at sentryWrapped (helpers.js:72:1)
    at resolvePromise (zone.js:1211:1)
    at zone.js:1118:1
    at rejected (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11136:89)
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.js:28666:1)
    at _ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1275:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28653:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
    at invokeTask (zone.js:491:1)
    at ZoneTask.invoke (zone.js:476:1)
    at data.args.<computed> (zone.js:2358:1)
    at sentryWrapped (helpers.js:72:1)
```

**Comment by enodr** [comment]
I can confirm after upgrading to version 184 right click and middle click are not working anymore (paste, context menu, etc)

**Comment by Eugeny** [comment]
Fixed
