### ISSUE TITLE
Download the source code, compile it according to the document, and report an error

### ISSUE THREAD

**Issue by jingxuanzhang1** [Eugeny/tabby#7569]
yarn start Can be started normally
yarn build
node script/build-linux Error reported after packaging
Operating environment：
nodejs 18.12.1
Linux Ubuntu 22.04.1
error:
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: app.disableHardwareAcceleration() can only be called before app is ready
    at App.<anonymous> (/home/symjie/.local/share/Trash/files/dist.7/linux-unpacked/resources/app.asar/dist/webpack:/tabby/lib/index.ts:65:9)
    at App.emit (node:events:539:35)
    at App.apply [as emit] (node:domain:475:12)
    at App.n.emit (/home/symjie/.local/share/Trash/files/dist.7/linux-unpacked/resources/app.asar/dist/webpack:/tabby/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25)
(node:21901) UnhandledPromiseRejectionWarning: Error: app.disableHardwareAcceleration() can only be called before app is ready
    at App.<anonymous> (/home/symjie/.local/share/Trash/files/dist.7/linux-unpacked/resources/app.asar/dist/webpack:/tabby/lib/index.ts:65:9)
    at App.emit (node:events:539:35)
    at App.apply [as emit] (node:domain:475:12)
    at App.n.emit (/home/symjie/.local/share/Trash/files/dist.7/linux-unpacked/resources/app.asar/dist/webpack:/tabby/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25)
(Use `tabby --trace-warnings ...` to show where the warning was created)
(node:21901) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by Eugeny** [comment]
Weird - `disableHardwareAcceleration` is only called from the `Application` constructor which is directly called from the main process entrypoint. How are you starting the app?

**Comment by jingxuanzhang1** [comment]
> Weird - `disableHardwareAcceleration` is only called from the `Application` constructor which is directly called from the main process entrypoint. How are you starting the app?

Execute by entering dist file

**Comment by jingxuanzhang1** [comment]
> Weird - `disableHardwareAcceleration` is only called from the `Application` constructor which is directly called from the main process entrypoint. How are you starting the app?

Will also report error
[21866:1128/173418.972848:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
