### ISSUE TITLE
cannot switch off global hotkey ctrl-space

### ISSUE THREAD

**Issue by LocalMountain** [Eugeny/tabby#7855]
Version: 1.0.188
Platform: macOS arm64 21.6.0
Plugins: none
Frontend: xterm-webgl

cannot switch off global hotkey ctrl-space
and there's only one way to switch off the global hotkey to toggle Tabby window in Welcome page, and it doesn't work

**Comment by Eugeny** [comment]
You can switch it off at any time in Settings -> Hotkeys -> Toggle window

**Comment by gelutz** [comment]
Same problem here, I've been trying to find something about this but there is none. @Eugeny 's answer is correct but isn't working for me.
I'm on Windows 10 with an qwerty layout, and switched the hotkey to:
```yaml
toggle-window:
 - Ctrl-Backquote
```
but it doesn't work.
The only key that works so far is `Ctrl-Space`, but there's conflict with vscode ctrl-space hotkey.

**Comment by gelutz** [comment]
Just found this when on devtools trying to set `Ctrl-Backquote`:
```js
Unhandled exception: TypeError: Error processing argument at index 0, conversion failure from Ctrl+Backquote
    at IpcMainImpl.<anonymous> (C:\Users\elut1073\AppData\Local\Programs\Tabby\resources\app.asar\dist\webpack:\tabby\lib\app.ts:42:32)
    at IpcMainImpl.emit (node:events:513:28)
    at IpcMainImpl.emit (node:domain:489:12)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81053)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.apply [as emit] (node:domain:489:12)
    at EventEmitter.n.emit (C:\Users\elut1073\AppData\Local\Programs\Tabby\resources\app.asar\dist\webpack:\tabby\node_modules\@sentry\electron\dist\main\integrations\electron.js:63:25)
(anonymous) @ C:\Users\elut1073\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:27108
(anonymous) @ C:\Users\elut1073\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:28877
emit @ node:events:513
onMessage @ node:electron/js2c/renderer_init:2

```

**Comment by Flandoll** [comment]
I had the same problem.
After testing, it is found that the two switches under the welcome page need to click the 'close and never show again' button to take effect.

Also I found a bug.
After closing the global hotkeys and closing the welcome page, the keys in Settings -> Hotkeys -> Toggle window will be cleared,
If the welcome page is displayed again by modifying the configuration file at this time, the global hotkey switch under the welcome page will be displayed as on, 
and the global hotkey cannot be turned on again through the welcome page.

**Comment by mgulyas42** [comment]
> Same problem here, I've been trying to find something about this but there is none. @Eugeny 's answer is correct but isn't working for me.
> I'm on Windows 10 with an qwerty layout, and switched the hotkey to:
> ```yaml
> toggle-window:
>  - Ctrl-Backquote
> ```
> but it doesn't work.
> The only key that works so far is `Ctrl-Space`, but there's conflict with vscode ctrl-space hotkey.

Hi. It is an Electron app and by default the backquote is not allowed yet as a string. You can Edit the config file to use `Ctrl+\``. 
But it was not enough for me and I had to make a  [workaround](https://github.com/electron/electron/issues/19747#issuecomment-2110900290) on Linux, because of using non qwerty layout

**Comment by mahoromax** [comment]
Still/Again experiencing this.

I disabled it on the welcome screen, but the global hotkey is still preoccupied (especially noticeable in games...)
