### ISSUE TITLE
莫名 tabby 卡死，没有响应，发生问题时开了 6 个标签页，点击所有标签和配置按钮无响应，过了一会才有响应

### ISSUE THREAD

**Issue by aigenguo** [Eugeny/tabby#7936]
Version: 1.0.188
Platform: macOS x64 22.3.0
Plugins: trzsz, quick-cmds
Frontend: xterm-webgl

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by aigenguo** [comment]
I don't know if this is the error log when stuck happened, i saw some similar error in console like this:
core.js:6456 ERROR Error: Uncaught (in promise): [object Number]
    at resolvePromise (zone.js:1211:1)
    at zone.js:1118:1
    at rejected (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:11772:89)
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.js:28666:1)
    at _ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1275:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28653:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:1)
    at invokeTask (zone.js:1648:1)
    at globalCallback (zone.js:1679:1)
    at HTMLButtonElement.globalZoneAwareCallback (zone.js:1712:1)
    at HTMLButtonElement.sentryWrapped (helpers.js:72:1)
defaultErrorLogger @ core.js:6456

**Comment by aigenguo** [comment]
When stuck happend, i was typing command on the of the 6 tabs, it suddendly i can't type command or switch tab that moment.
