### ISSUE TITLE
Any shell doesn't start

### ISSUE THREAD

**Issue by UAnton** [Eugeny/tabby#8009]
**Describe the problem**:
Any shell doesn't start on the 2 last versions.

MacBook Pro 14 M1 Pro
MacOS Ventura 13.3

**To Reproduce**:
Start Tabby and then open new tab after 10-15 min

**Comment by UAnton** [comment]
```
/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:31251 Unhandled exception: Error: openpty failed.
    at new UnixTerminal (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js:102:24)
    at Object.spawn (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js:28:12)
    at new d (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/lib/pty.ts:96:37)
    at IpcMainImpl.<anonymous> (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/lib/pty.ts:147:29)
    at IpcMainImpl.emit (node:events:527:28)
    at IpcMainImpl.emit (node:domain:475:12)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.apply [as emit] (node:domain:475:12)
    at EventEmitter.n.emit (/Applications/Tabby.app/Contents/Resources/app.asar/dist/webpack:/tabby/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25)
(anonymous) @ /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:31251
(anonymous) @ /Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-electron/dist/index.js:29388
emit @ node:events:527
onMessage @ node:electron/js2c/renderer_init:69
```

**Comment by karaketir16** [comment]
Could be related to #7892. Can you check the RAM usage?

**Comment by UAnton** [comment]
700MB
