### ISSUE TITLE
Copy from terminal no longer works

### ISSUE THREAD

**Issue by mrevjd** [Eugeny/tabby#8108]
Version: 1.0.192
Platform: Windows x64 10.0.22621
Plugins: title-control, theme-windows10
Frontend: xterm-webgl

Copying from a Linux terminal no longer works.
Tried the long right click menu option and the short cut keys with no luck.

`error_handler.ts:45 ERROR TypeError: CellData.CellData is not a constructor
    at XTermWebGLFrontend.getLineAsHTML (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:37792:22)
    at XTermWebGLFrontend.getSelectionAsHTML (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:37762:26)
    at XTermWebGLFrontend.copySelection (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:37605:28)
    at C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:37449:22
    at t.EventEmitter.fire (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:25166:55)
    at C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:22779:782
    at t.EventEmitter.fire (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:25166:55)
    at p._fireOnSelectionChange (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:24525:122)
    at p._fireEventIfSelectionChanged (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:24522:239)
    at p._handleMouseUp (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:24516:27)
    at HTMLDocument._mouseUpListener (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:24339:1031)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
    at invokeTask (zone.js:1648:18)
    at globalCallback (zone.js:1679:29)
    at HTMLDocument.globalZoneAwareCallback (zone.js:1712:16)
    at HTMLDocument.sentryWrapped (helpers.ts:87:17)
`

**Comment by MaverickTN** [comment]
I've had the same problem as well after I updated to alpha 190.

**Comment by danghuagood** [comment]
me too

**Comment by jaysoncho92** [comment]
same problem.

**Comment by fayezk13** [comment]
I reverted back to version 1.0.189 from the Alpha 189 release assets until they resolve this issue

**Comment by Eugeny** [comment]
Fixed in 1.0.193
