### ISSUE TITLE
New terminal does not work.

### ISSUE THREAD

**Issue by xuhjbj** [Eugeny/tabby#8109]
Version: 1.0.189
Platform: Windows x64 10.0.19045
Plugins: sync-config, save-output, quick-restart, docker
Frontend: xterm

When I click the "New Terminal" to open a new window,but it does not work,and it does not worked when I restarted the tabby.

**Comment by xuhjbj** [comment]
C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:20218 [ssh-9.46.74.240-22] Loading private key: id_rsa
zone.js:1061 Unhandled Promise rejection: Frontend not ready ; Zone: <root> ; Task: Promise.then ; Value: Error: Frontend not ready
    at SSHTabComponent.<anonymous> (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:14765:23)
    at Generator.next (<anonymous>)
    at C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11157:71
    at new ZoneAwarePromise (zone.js:1427:1)
    at __awaiter (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11153:12)
    at SSHTabComponent.writeRaw (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:14763:16)
    at C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:14758:106
    at SSHTabComponent.<anonymous> (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:15112:23)
    at Generator.next (<anonymous>)
    at C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11157:71
    at new ZoneAwarePromise (zone.js:1427:1)
    at __awaiter (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11153:12)
    at SSHTabComponent.withSpinnerPaused (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:15106:16)
    at C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:14758:77
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.js:28666:1)
    at _ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1275:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28653:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5) Error: Frontend not ready
    at SSHTabComponent.<anonymous> (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:14765:23)
    at Generator.next (<anonymous>)
    at C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11157:71
    at new ZoneAwarePromise (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:126998:29)
    at __awaiter (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11153:12)
    at SSHTabComponent.writeRaw (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:14763:16)
    at C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:14758:106
    at SSHTabComponent.<anonymous> (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:15112:23)
    at Generator.next (<anonymous>)
    at C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11157:71
    at new ZoneAwarePromise (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:126998:29)
    at __awaiter (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11153:12)
    at SSHTabComponent.withSpinnerPaused (C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:15106:16)
    at C:\Program Files\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:14758:77
    at _ZoneDelegate.invoke (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:125943:26)
    at Object.onInvoke (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:87629:33)
    at _ZoneDelegate.invoke (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:125942:52)
    at Zone.run (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:125705:43)
    at file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:126846:36
    at _ZoneDelegate.invokeTask (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:125977:31)
    at Object.onInvokeTask (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:87616:33)
    at _ZoneDelegate.invokeTask (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:125976:60)
    at Zone.runTask (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:125749:47)
    at drainMicroTaskQueue (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:126156:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
api.onUnhandledError @ zone.js:1061
C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:20218 [ssh-9.46.74.240-22] Trying saved password
node:events:505 Uncaught Error: ENOENT: no such file or directory, open 'C:\Instana\learndoc\tabby-client\2023-03-21T075410.216Z - root@fyn21~.ssh.txt'
C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:20218 [sftp] Uploading into /root/ssh.tar
index.html:1 Autofocus processing was blocked because a document already has a focused element.
node:events:505 Uncaught Error: ENOENT: no such file or directory, open 'C:\Instana\learndoc\tabby-client\2023-03-21T075734.250Z - 9.46.72.35-wxs1.fyre.ibm.com-backend.txt'
node:events:505 Uncaught Error: ENOENT: no such file or directory, open 'C:\Instana\learndoc\tabby-client\2023-03-21T081535.750Z - root@wxs1~.ssh.txt'
api.tabby.sh/api/1/configs:1          Failed to load resource: the server responded with a status of 403 ()
C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:20218 [configSync] AxiosError
doLog @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:20218
core.js:6456 ERROR Error: Uncaught (in promise): AxiosError: Request failed with status code 403
    at resolvePromise (zone.js:1211:1)
    at zone.js:1118:1
    at rejected (C:\Program Files\Tabby\resources\builtin-plugins\tabby-settings\dist\index.js:9679:89)
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.js:28666:1)
    at _ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1275:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28653:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:1)
    at invokeTask (zone.js:1648:1)
    at globalCallback (zone.js:1679:1)
    at XMLHttpRequest.globalZoneAwareCallback (zone.js:1712:1)
    at XMLHttpRequest.sentryWrapped (helpers.js:72:1)
defaultErrorLogger @ core.js:6456

**Comment by xuhjbj** [comment]
After waiting a long time, the tabby opened those windows later. I tried to collect log after that, I can not make sure if above error logs are related to timeline about the issue happened.

**Comment by moranrs** [comment]
Did you enable and configure the docker plugin and the docker host is not powered on? If this is the case try disabling the docker plugin.

**Comment by xuhjbj** [comment]
ok,I will try. That issue is not always happening.So we need to wait for reproduce after I disable docker plugin.Thanks.
