### ISSUE TITLE
Unable to copy after update

### ISSUE THREAD

**Issue by Gaibhne** [Eugeny/tabby#8113]
**Describe the problem**:

Topic says it all. Neither right click copy nor context menu copy works any longer. I have option set to 'copy if selected else paste', but none of the other options work either.

**To Reproduce**:

Whenever I try to copy in any (ssh) terminal. Don't use any other terminals, so no idea if that is related to the issue.

I am attaching an error that comes up the moment I attempt to copy when I have the dev tools open:

```
error_handler.ts:45 ERROR Error: Uncaught (in promise): TypeError: CellData.CellData is not a constructor
TypeError: CellData.CellData is not a constructor
    at XTermWebGLFrontend.getLineAsHTML (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:37792:22)
    at XTermWebGLFrontend.getSelectionAsHTML (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:37765:26)
    at XTermWebGLFrontend.copySelection (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:37605:28)
    at SSHTabComponent.<anonymous> (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:38483:43)
    at Generator.next (<anonymous>)
    at C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:34458:67
    at new ZoneAwarePromise (zone.js:1427:29)
    at __awaiter (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:34440:10)
    at SSHTabComponent.handleRightMouseUp (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:38471:16)
    at Object.next (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:38534:26)
    at ConsumerObserver.next (Subscriber.ts:161:25)
    at Subscriber._next (Subscriber.ts:119:22)
    at Subscriber.next (Subscriber.ts:75:12)
    at Subject.ts:68:20
    at Object.errorContext (errorContext.ts:29:5)
    at Subject.next (Subject.ts:61:5)
    at HTMLDivElement.<anonymous> (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:37571:71)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
    at invokeTask (zone.js:1648:18)
    at globalCallback (zone.js:1679:29)
    at HTMLDivElement.globalZoneAwareCallback (zone.js:1712:16)
    at HTMLDivElement.sentryWrapped (helpers.ts:87:17)
    at resolvePromise (zone.js:1211:31)
    at new ZoneAwarePromise (zone.js:1430:17)
    at __awaiter (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:34440:10)
    at SSHTabComponent.handleRightMouseUp (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:38471:16)
    at Object.next (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:38534:26)
    at ConsumerObserver.next (Subscriber.ts:161:25)
    at Subscriber._next (Subscriber.ts:119:22)
    at Subscriber.next (Subscriber.ts:75:12)
    at Subject.ts:68:20
    at Object.errorContext (errorContext.ts:29:5)
    at Subject.next (Subject.ts:61:5)
    at HTMLDivElement.<anonymous> (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:37571:71)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
    at invokeTask (zone.js:1648:18)
    at globalCallback (zone.js:1679:29)
```

**Comment by Keepy38** [comment]
Hi,
I have the same problem. 

**Workaround** : disable Copy with formatting (Setting --> Terminal)

regards

**Comment by Eugeny** [comment]
It's fixed in the latest release
