### ISSUE TITLE
Cannot change Serial Port Baudrate after opening

### ISSUE THREAD

**Issue by hypomaniak** [Eugeny/tabby#8134]
Hello
When opening a new tab with a Serial Port profile and choosing a baudrate, it is not possible to change said baudrate without closing and reopening a new tab on the same port number.
Not sure if it's an interface problem or other.

Steps to reproduce:
1. Open a new Serial tab from basic profile and select baudrate from the popup list.
or
Open a new Serial Tab from a saved profile.
2. Port is opened and correct baudrate is displayed
3. Click on Change Baudrate and select a different value.
4. Baudrate is not updated.

I think this was OK on Alpha 189, but not on 1.0.196.

Other than that, I'm happy with 196, and slowly but surely, this app is spreading around my colleagues.

Config:
1.0.196
Windows 10 Pro 64bits 21H2

**Comment by hypomaniak** [comment]
Forgot the log from the Dev Console:
```

error_handler.ts:45 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'update')
TypeError: Cannot read properties of undefined (reading 'update')
    at SerialTabComponent.<anonymous> (C:\Program Files\Tabby\resources\builtin-plugins\tabby-serial\dist\index.js:3752:29)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Tabby\resources\builtin-plugins\tabby-serial\dist\index.js:3037:24)
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at _ZoneDelegate.invoke (zone.js:371:52)
    at Zone.run (zone.js:134:43)
    at zone.js:1275:36
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:21)
    at invokeTask (zone.js:1648:18)
    at globalCallback (zone.js:1679:29)
    at HTMLAnchorElement.globalZoneAwareCallback (zone.js:1712:16)
    at HTMLAnchorElement.sentryWrapped (helpers.ts:87:17)
    at resolvePromise (zone.js:1211:31)
    at zone.js:1118:17
    at fulfilled (C:\Program Files\Tabby\resources\builtin-plugins\tabby-serial\dist\index.js:3039:9)
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at _ZoneDelegate.invoke (zone.js:371:52)
    at Zone.run (zone.js:134:43)
    at zone.js:1275:36
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:21)
    at invokeTask (zone.js:1648:18)
    at globalCallback (zone.js:1679:29)
    at HTMLAnchorElement.globalZoneAwareCallback (zone.js:1712:16)
    at HTMLAnchorElement.sentryWrapped (helpers.ts:87:17)
handleError @ error_handler.ts:45
next @ application_ref.ts:459
ConsumerObserver.next @ Subscriber.ts:161
Subscriber._next @ Subscriber.ts:119
Subscriber.next @ Subscriber.ts:75
(anonymous) @ Subject.ts:68
errorContext @ errorContext.ts:29
Subject.next @ Subject.ts:61
emit @ event_emitter.ts:114
(anonymous) @ ng_zone.ts:450
invoke @ zone.js:372
run @ zone.js:134
runOutsideAngular @ ng_zone.ts:249
onHandleError @ ng_zone.ts:450
handleError @ zone.js:376
runGuarded @ zone.js:147
api.microtaskDrainDone @ zone.js:1072
drainMicroTaskQueue @ zone.js:592
invokeTask @ zone.js:491
invokeTask @ zone.js:1648
globalCallback @ zone.js:1679
globalZoneAwareCallback @ zone.js:1712
sentryWrapped @ helpers.ts:87
```
