### ISSUE TITLE
Click New Terminal and there is no response

### ISSUE THREAD

**Issue by github24518** [Eugeny/tabby#8155]
Version: 1.0.194
Platform: Windows x64 10.0.22000
Plugins: none
Frontend: xterm-webgl

Click New Terminal and there is no response

**Comment by Rukhazon** [comment]
Hi, same problem here with Windows 11 22621.1413
I see this in the debug console when I click on new tab or profiles :
ERROR TypeError: Cannot read properties of undefined (reading 'nativeElement')
    at dropdown.ts:320:57
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Zone.run (zone.js:134:43)
    at NgZone.runOutsideAngular (ng_zone.ts:249:50)
    at NgbDropdown.open (dropdown.ts:317:19)
    at NgbDropdown.toggle (dropdown.ts:375:9)
    at NgbDropdownToggle_click_HostBindingHandler (dropdown.ts:148:14)
    at executeListenerWithErrorHandling (listener.ts:224:12)
    at wrapListenerIn_markDirtyAndPreventDefault (listener.ts:261:18)
    at HTMLButtonElement.<anonymous> (dom_renderer.ts:58:34)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
    at invokeTask (zone.js:1648:18)
    at globalCallback (zone.js:1679:29)
    at HTMLButtonElement.globalZoneAwareCallback (zone.js:1712:16)
    at HTMLButtonElement.sentryWrapped (helpers.ts:87:17)
handleError	@	error_handler.ts:45
handleError	@	shared.ts:1874
executeListenerWithErrorHandling	@	listener.ts:226
wrapListenerIn_markDirtyAndPreventDefault	@	listener.ts:261
(anonymous)	@	dom_renderer.ts:58
invokeTask	@	zone.js:406
onInvokeTask	@	ng_zone.ts:408
invokeTask	@	zone.js:405
runTask	@	zone.js:178
invokeTask	@	zone.js:487
invokeTask	@	zone.js:1648
globalCallback	@	zone.js:1679
globalZoneAwareCallback	@	zone.js:1712
sentryWrapped	@	helpers.ts:87

**Comment by wzball** [comment]
Hi all

I seem to have the same problem. I had a previous install that I recently upgraded to the latest 1.0.194 using tabby-1.0.194-setup-x64.exe.

When I launch tabby, it loads with the standard open screen with the '+ New terminal', several history items.

When I try to click on any button, such as '+ New Terminal', 'Profiles & connections' or even 'Settings', the UI does not respond. I have the same error message as pasted by Rukhazon.

Running Windows 11 Pro, 22H2, 22621.1413.

> error_handler.ts:45 ERROR TypeError: Cannot read properties of undefined (reading 'nativeElement')
>     at dropdown.ts:320:57
>     at _ZoneDelegate.invoke (zone.js:372:26)
>     at Zone.run (zone.js:134:43)
>     at NgZone.runOutsideAngular (ng_zone.ts:249:50)
>     at NgbDropdown.open (dropdown.ts:317:19)
>     at NgbDropdown.toggle (dropdown.ts:375:9)
>     at NgbDropdownToggle_click_HostBindingHandler (dropdown.ts:148:14)
>     at executeListenerWithErrorHandling (listener.ts:224:12)
>     at wrapListenerIn_markDirtyAndPreventDefault (listener.ts:261:18)
>     at HTMLButtonElement.<anonymous> (dom_renderer.ts:58:34)
>     at _ZoneDelegate.invokeTask (zone.js:406:31)
>     at Object.onInvokeTask (ng_zone.ts:408:29)
>     at _ZoneDelegate.invokeTask (zone.js:405:60)
>     at Zone.runTask (zone.js:178:47)
>     at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
>     at invokeTask (zone.js:1648:18)
>     at globalCallback (zone.js:1679:29)
>     at HTMLButtonElement.globalZoneAwareCallback (zone.js:1712:16)
>     at HTMLButtonElement.sentryWrapped (helpers.ts:87:17)
> handleError @ error_handler.ts:45

![image](https://user-images.githubusercontent.com/53862711/230239866-c042e864-a4e8-4e5b-a8a5-4ded4fb05073.png)


Attached log [saved_log.log](https://github.com/Eugeny/tabby/files/11165068/saved_log.log)

**Comment by YuboHe** [comment]
same problem here

**Comment by github24518** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
