### ISSUE TITLE
use rz/sz failed

### ISSUE THREAD

**Issue by luyuhang2021** [Eugeny/tabby#8318]
when i use 'sz' download file from server, will be stuck long time and failed,this is some debug msg :

```
error_handler.ts:45 ERROR Error: It looks like your application or one of its dependencies is using i18n.
Angular 9 introduced a global `$localize()` function that needs to be loaded.
Please run `ng add @angular/localize` from the Angular CLI.
(For non-CLI projects, add `import '@angular/localize/init';` to your `polyfills.ts` file.
For server-side rendering applications add the import to your `main.server.ts` file.)
    at _global.$localize (core.ts:49:11)
    at consts (ngb-config.ts:10:14)
    at createTView (shared.ts:605:58)
    at getOrCreateComponentTView (shared.ts:571:24)
    at addComponentLogic (shared.ts:1380:17)
    at instantiateAllDirectives (shared.ts:1150:5)
    at createDirectivesInstances (shared.ts:528:3)
    at ɵɵelementStart (element.ts:112:5)
    at ɵɵelement (element.ts:176:3)
    at TransfersMenuComponent_div_6_div_8_Template (template.html:18:7)
    at executeTemplate (shared.ts:495:5)
    at renderView (shared.ts:299:7)
    at TemplateRef.createEmbeddedView (template_ref.ts:96:5)
    at ViewContainerRef.createEmbeddedView (view_container_ref.ts:306:33)
    at NgIf._updateView (ng_if.ts:204:35)
    at set ngIf [as ngIf] (ng_if.ts:172:10)
    at setInputsForProperty (shared.ts:1897:28)
    at elementPropertyInternal (shared.ts:910:5)
    at ɵɵproperty (property.ts:42:5)
    at TransfersMenuComponent_div_6_Template (template.html:17:26)
    at executeTemplate (shared.ts:495:5)
    at refreshView (shared.ts:368:7)
    at refreshEmbeddedViews (shared.ts:1565:9)
    at refreshView (shared.ts:395:5)
    at refreshComponent (shared.ts:1615:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:425:7)
    at refreshEmbeddedViews (shared.ts:1565:9)
    at refreshView (shared.ts:395:5)
    at refreshEmbeddedViews (shared.ts:1565:9)
    at refreshView (shared.ts:395:5)
    at refreshComponent (shared.ts:1615:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:425:7)
    at detectChangesInternal (shared.ts:1770:5)
    at RootViewRef.detectChanges (view_ref.ts:323:5)
    at ApplicationRef.tick (application_ref.ts:1015:14)
    at application_ref.ts:772:16
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at _ZoneDelegate.invoke (zone.js:371:52)
    at Zone.run (zone.js:134:43)
    at NgZone.run (ng_zone.ts:202:50)
    at Object.next (application_ref.ts:771:20)
    at ConsumerObserver.next (Subscriber.ts:161:25)
    at Subscriber._next (Subscriber.ts:119:22)
    at Subscriber.next (Subscriber.ts:75:12)
    at Subject.ts:68:20
    at Object.errorContext (errorContext.ts:29:5)
    at Subject.next (Subject.ts:61:5)
```

**Comment by luyuhang2021** [comment]
rz is same.file is  java.jar and orc file.  txtfile is fine
