### ISSUE TITLE
sz stuck in 43%，finally error

### ISSUE THREAD

**Issue by DorayakiCreme** [Eugeny/tabby#8359]
Version: 1.0.197
Platform: macOS arm64 22.4.0
Plugins: none
Frontend: xterm-webgl
![image](https://user-images.githubusercontent.com/93249643/236170622-1cb51e7f-cd5c-4713-904d-c73d3a46b087.png)

ERROR Error: It looks like your application or one of its dependencies is using i18n.
Angular 9 introduced a global `$localize()` function that needs to be loaded.
Please run `ng add @angular/localize` from the Angular CLI.
(For non-CLI projects, add `import '@angular/localize/init';` to your `polyfills.ts` file.
For server-side rendering applications add the import to your `main.server.ts` file.)
    at _global.$localize (core.ts:49:11)
    at consts (ngb-config.ts:10:14)
    at createTView (shared.ts:606:58)
    at getOrCreateComponentTView (shared.ts:572:24)
    at addComponentLogic (shared.ts:1378:17)
    at instantiateAllDirectives (shared.ts:1148:5)
    at createDirectivesInstances (shared.ts:529:3)
    at ɵɵelementStart (element.ts:112:5)
    at ɵɵelement (element.ts:176:3)
    at TransfersMenuComponent_div_6_div_6_Template (template.html:12:7)
    at executeTemplate (shared.ts:496:5)
    at renderView (shared.ts:300:7)
    at TemplateRef.createEmbeddedView (template_ref.ts:96:5)
    at ViewContainerRef.createEmbeddedView (view_container_ref.ts:306:33)
    at NgIf._updateView (ng_if.ts:204:35)
    at set ngIf [as ngIf] (ng_if.ts:172:10)
    at setInputsForProperty (shared.ts:1895:28)
    at elementPropertyInternal (shared.ts:911:5)
    at ɵɵproperty (property.ts:42:5)
    at TransfersMenuComponent_div_6_Template (template.html:11:26)
    at executeTemplate (shared.ts:496:5)
    at refreshView (shared.ts:369:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at detectChangesInternal (shared.ts:1768:5)
    at RootViewRef.detectChanges (view_ref.ts:321:5)
    at ApplicationRef.tick (application_ref.ts:1028:14)
    at application_ref.ts:785:16
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:127:43)
    at NgZone.run (ng_zone.ts:202:50)
    at Object.next (application_ref.ts:784:20)
    at ConsumerObserver.next (Subscriber.ts:161:25)
    at Subscriber._next (Subscriber.ts:119:22)
    at Subscriber.next (Subscriber.ts:75:12)
    at Subject.ts:68:20
    at Object.errorContext (errorContext.ts:29:5)
    at Subject.next (Subject.ts:61:5)
handleError @ error_handler.ts:45
error_handler.ts:45 ERROR Error: Uncaught (in promise): [object Undefined]
    at resolvePromise (zone.js:1193:31)
    at zone.js:1100:17
    at zone.js:1116:33
    at rejected (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:14363:9)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:127:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:171:47)
    at drainMicroTaskQueue (zone.js:581:35)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:21)
    at invokeTask (zone.js:1631:18)
    at globalCallback (zone.js:1662:29)
    at HTMLButtonElement.globalZoneAwareCallback (zone.js:1695:16)
    at HTMLButtonElement.sentryWrapped (helpers.ts:87:17)
handleError @ error_handler.ts:45
11DevTools failed to load source map: Could not parse content for file:///Applications/Tabby.app/Contents/Resources/app.asar.unpacked/assets/webpack/index.js.map: Unexpected end of JSON input
/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-core/dist/index.js:15969 [zmodem] protocol error Error: Peer aborted session
    at ZmodemReceiveSession._check_for_abort_sequence (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-terminal/dist/index.js:31394:13)
    at ZmodemReceiveSession.consume (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-terminal/dist/index.js:31296:15)
    at ZmodemSentry.consume (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-terminal/dist/index.js:30959:30)
    at ZModemMiddleware.feedFromSession (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-terminal/dist/index.js:39175:29)
    at SessionMiddlewareStack.feedFromSession (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-terminal/dist/index.js:39107:23)
    at SSHShellSession.emitOutput (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-terminal/dist/index.js:40286:25)
    at Channel.<anonymous> (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-ssh/dist/index.js:50038:22)
    at Channel.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at CHANNEL_DATA (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-ssh/dist/index.js:17327:23)
    at 94 (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-ssh/dist/index.js:25859:16)
    at Protocol.onPayload (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-ssh/dist/index.js:20020:10)
    at GenericDecipherNative.decrypt (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-ssh/dist/index.js:24423:26)
    at Protocol.parsePacket [as _parse] (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-ssh/dist/index.js:19998:25)
    at Protocol.parse (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-ssh/dist/index.js:18874:30)
    at Socket.<anonymous> (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-ssh/dist/index.js:17470:21)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by luyuhang2021** [comment]
my server is jumpserver .  And use `/bin/sh ssh user@host` can solve this problem
