### ISSUE TITLE
Can't not input anything in terminal Suddenly

### ISSUE THREAD

**Issue by stevennight** [Eugeny/tabby#8625]
Version: 1.0.197
Platform: Windows x64 10.0.25393
Plugins: cloud-settings-sync
Frontend: xterm-webgl

Can't not input anything in terminal Suddenly. What should I provide?

**Comment by stevennight** [comment]
console log:
```
error_handler.ts:45 ERROR TypeError: Cannot read properties of null (reading 'length')
    at HotkeysService.matchActiveHotkey (C:\Users\Steve\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:20877:55)
    at HotkeysService.pushKeyEvent (C:\Users\Steve\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:20842:30)
    at keyboardEventHandler (C:\Users\Steve\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:37457:33)
    at I._customKeyEventHandler (C:\Users\Steve\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:37477:20)
    at I._keyDown (C:\Users\Steve\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:22927:113)
    at HTMLTextAreaElement.<anonymous> (C:\Users\Steve\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:22746:194)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
    at invokeTask (zone.js:1648:18)
    at globalCallback (zone.js:1679:29)
    at HTMLTextAreaElement.globalZoneAwareCaptureCallback (zone.js:1716:16)
    at HTMLTextAreaElement.sentryWrapped (helpers.ts:87:17)
```

**Comment by stevennight** [comment]
reset the config and work well.
