### ISSUE TITLE
Stuck on the splash screen

### ISSUE THREAD

**Issue by asm0dey** [Eugeny/tabby#8648]
**Describe the problem**:
Since last update my tabby is stuck on splash screen

**To Reproduce**:
My tabby: 1.0.197
OS: 
```
❯ cat /etc/os-release
NAME=EndeavourOS
PRETTY_NAME=EndeavourOS
ID=endeavouros
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL='https://endeavouros.com'
DOCUMENTATION_URL='https://discovery.endeavouros.com'
SUPPORT_URL='https://forum.endeavouros.com'
BUG_REPORT_URL='https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports'
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=endeavouros
```
That's all I see:
![image](https://github.com/Eugeny/tabby/assets/1297282/4c86b6ed-841a-4385-94dd-2eca136bc5da)

`tabby --debug` gives nothing

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by asm0dey** [comment]
DevTools console does not open :(
Neither with --debug, nor with Ctrl+Shift+I

**Comment by asm0dey** [comment]
Sorry, figured it out partially, still can't open console, but now I see 

```
[10316:0704/233654.666816:ERROR:platform_shared_memory_region_posix.cc(217)] Creating shared memory in /dev/shm/.org.chromium.Chromium.oQ2EYV failed: No such file or directory (2)
[10316:0704/233654.666986:ERROR:platform_shared_memory_region_posix.cc(220)] Unable to access(W_OK|X_OK) /dev/shm: No such file or directory (2)
[10316:0704/233654.667066:FATAL:platform_shared_memory_region_posix.cc(222)] This is frequently caused by incorrect permissions on /dev/shm.  Try 'sudo chmod 1777 /dev/shm' to fix.
```
in the log

**Comment by asm0dey** [comment]
Oh wow, with `--no-sandbox` I got following:

```
zone.js:1043 Unhandled Promise rejection: Cannot find module 'tabby-core'
Require stack:
- /opt/Tabby/resources/app.asar/dist/index.html ; Zone: <root> ; Task: null ; Value: Error: Cannot find module 'tabby-core'
Require stack:
- /opt/Tabby/resources/app.asar/dist/index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at o._resolveFilename (node:electron/js2c/renderer_init:2:3833)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at __webpack_modules__.69039.nodeModule.require (plugins.ts:61:34)
    at require (node:internal/modules/cjs/helpers:102:18)
    at plugins.ts:88:39
    at Array.forEach (<anonymous>)
    at initModuleLookup (plugins.ts:86:20)
    at entry.ts:60:21
    at Generator.next (<anonymous>)
    at app.module.ts:38:2
    at new ZoneAwarePromise (zone.js:1411:21)
    at __webpack_modules__.36945.__awaiter (app.module.ts:38:2)
    at EventEmitter.<anonymous> (entry.ts:57:75)
    at Object.onceWrapper (node:events:628:26)
    at EventEmitter.emit (node:events:513:28)
    at Object.onMessage (node:electron/js2c/renderer_init:2:9151) Error: Cannot find module 'tabby-core'
Require stack:
- /opt/Tabby/resources/app.asar/dist/index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at o._resolveFilename (node:electron/js2c/renderer_init:2:3833)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at __webpack_modules__.69039.nodeModule.require (file:///opt/Tabby/resources/app.asar/dist/bundle.js:286:34)
    at require (node:internal/modules/cjs/helpers:102:18)
    at file:///opt/Tabby/resources/app.asar/dist/bundle.js:305:39
    at Array.forEach (<anonymous>)
    at initModuleLookup (file:///opt/Tabby/resources/app.asar/dist/bundle.js:303:20)
    at file:///opt/Tabby/resources/app.asar/dist/bundle.js:144:36
    at Generator.next (<anonymous>)
    at file:///opt/Tabby/resources/app.asar/dist/bundle.js:92:71
    at new ZoneAwarePromise (file:///opt/Tabby/resources/app.asar/dist/bundle.js:22602:21)
    at __webpack_modules__.36945.__awaiter (file:///opt/Tabby/resources/app.asar/dist/bundle.js:88:12)
    at EventEmitter.<anonymous> (file:///opt/Tabby/resources/app.asar/dist/bundle.js:142:66)
    at Object.onceWrapper (node:events:628:26)
    at EventEmitter.emit (node:events:513:28)
    at Object.onMessage (node:electron/js2c/renderer_init:2:9151)
```

**Comment by asm0dey** [comment]
I'm closing the issue: turns out it's the problem of packager, with a different PKGBUILD everything works fine. Sorry for bothering you
