### ISSUE TITLE
Hotkeys tab not working correctly

### ISSUE THREAD

**Issue by CaptainFallaway** [Eugeny/tabby#8756]
Version: 1.0.197
Platform: Windows x64 10.0.19045
Plugins: none
Frontend: xterm-webgl

I have encountered a problem where when I press on hotkeys in the settings it just won't budge or do anything when I press on another one of the settings tabs (see first image). Not only that but when I want to change a keybind, it seems like the popup that comes up doesn't register my keybinds nor look completely right, (see second images) 

I just encountered these problems today and it has never been like this before, I've restarted the program to see if that would fix anything but to no difference. I do not know what I going on or if it can be simulated or not.

Hotkeys tab not working correctly:
![image](https://github.com/Eugeny/tabby/assets/69320425/4a920015-93a0-4fb2-9697-abf2a8e97fbe)

Trying to bind a new keybind:
![image](https://github.com/Eugeny/tabby/assets/69320425/cee55576-ca9e-4f4b-b916-5768b36212d1)

**Comment by CaptainFallaway** [comment]
It's all a little random and confusing. Now I noticed that the hotkeys do work after restarting again but when I'm inside the hotkeys section it's still effecting how menus pop up and it just buggs the the whole program out in some unpredictable ways for my brain atleast.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by CaptainFallaway** [comment]
**When I press on the hotkeys tab this appears:**

`error_handler.ts:45 ERROR TypeError: Cannot read properties of null (reading 'ssh:custom:capnrasp4gb:1a43fea7-ed09-4054-be2a-f76d668e09fb')
    at HotkeySettingsTabComponent.getHotkeys (C:\Program Files\Tabby\resources\builtin-plugins\tabby-settings\dist\index.js:10147:22)
    at HotkeySettingsTabComponent_ng_container_8_div_1_Template (template.html:12:29)
    at executeTemplate (shared.ts:496:5)
    at refreshView (shared.ts:369:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at detectChangesInternal (shared.ts:1768:5)
    at RootViewRef.detectChanges (view_ref.ts:321:5)
    at ApplicationRef.tick (application_ref.ts:1028:14)
    at application_ref.ts:785:16
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:127:43)
    at NgZone.run (ng_zone.ts:202:50)
    at Object.next (application_ref.ts:784:20)
handleError @ error_handler.ts:45
(anonymous) @ application_ref.ts:1037
invoke @ zone.js:368
run @ zone.js:127
runOutsideAngular @ ng_zone.ts:249
tick @ application_ref.ts:1037
(anonymous) @ application_ref.ts:785
invoke @ zone.js:368
onInvoke @ ng_zone.ts:423
invoke @ zone.js:367
run @ zone.js:127
run @ ng_zone.ts:202
next @ application_ref.ts:784
ConsumerObserver.next @ Subscriber.ts:161
Subscriber._next @ Subscriber.ts:119
Subscriber.next @ Subscriber.ts:75
(anonymous) @ Subject.ts:68
errorContext @ errorContext.ts:29
Subject.next @ Subject.ts:61
emit @ event_emitter.ts:114
checkStable @ ng_zone.ts:341
onHasTask @ ng_zone.ts:441
hasTask @ zone.js:422
_updateTaskCount @ zone.js:443
_updateTaskCount @ zone.js:270
runTask @ zone.js:188
drainMicroTaskQueue @ zone.js:581
Promise.then (async)
nativeScheduleMicroTask @ zone.js:557
scheduleMicroTask @ zone.js:568
scheduleTask @ zone.js:392
onScheduleTask @ zone.js:279
scheduleTask @ zone.js:382
scheduleTask @ zone.js:214
scheduleMicroTask @ zone.js:234
scheduleResolveOrReject @ zone.js:1247
resolvePromise @ zone.js:1184
(anonymous) @ zone.js:1100
(anonymous) @ zone.js:1116
Promise.then (async)
(anonymous) @ zone.js:1489
ZoneAwarePromise @ zone.js:1411
Ctor.then @ zone.js:1488
resolvePromise @ zone.js:1151
(anonymous) @ zone.js:1100
(anonymous) @ zone.js:1116
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:27908
ZoneAwarePromise @ zone.js:1411
adopt @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:27907
step @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:27927
fulfilled @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:27914
invoke @ zone.js:368
onInvoke @ ng_zone.ts:423
invoke @ zone.js:367
run @ zone.js:127
(anonymous) @ zone.js:1257
invokeTask @ zone.js:402
onInvokeTask @ ng_zone.ts:408
invokeTask @ zone.js:401
runTask @ zone.js:171
drainMicroTaskQueue @ zone.js:581
Promise.then (async)
nativeScheduleMicroTask @ zone.js:557
scheduleMicroTask @ zone.js:568
scheduleTask @ zone.js:392
onScheduleTask @ zone.js:279
scheduleTask @ zone.js:382
scheduleTask @ zone.js:214
scheduleMicroTask @ zone.js:234
scheduleResolveOrReject @ zone.js:1247
resolvePromise @ zone.js:1184
(anonymous) @ zone.js:1100
(anonymous) @ zone.js:1116
Promise.then (async)
(anonymous) @ zone.js:1489
ZoneAwarePromise @ zone.js:1411
Ctor.then @ zone.js:1488
resolvePromise @ zone.js:1151
(anonymous) @ zone.js:1100
(anonymous) @ zone.js:1116
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:27908
ZoneAwarePromise @ zone.js:1411
adopt @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:27907
step @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:27927
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:27929
ZoneAwarePromise @ zone.js:1411
__awaiter @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:27911
getPowerShellPath @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:33797
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:33787
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:27929
ZoneAwarePromise @ zone.js:1411
__awaiter @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:27911
provide @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:33757
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:4004
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:4004
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:2479
ZoneAwarePromise @ zone.js:1411
__awaiter @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:2461
getShells @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:4003
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:3969
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:2479
ZoneAwarePromise @ zone.js:1411
__awaiter @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:2461
getBuiltinProfiles @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:3968
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:23317
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:23317
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:14369
ZoneAwarePromise @ zone.js:1411
__awaiter @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:14351
getProfiles @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:23316
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:26451
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:14369
ZoneAwarePromise @ zone.js:1411
__awaiter @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:14351
provide @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:26450
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:20934
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:14369
ZoneAwarePromise @ zone.js:1411
__awaiter @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:14351
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:20934
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:20934
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:14369
ZoneAwarePromise @ zone.js:1411
__awaiter @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:14351
getHotkeyDescriptions @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:20932
HotkeySettingsTabComponent @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-settings\dist\index.js:10140
HotkeySettingsTabComponent_Factory @ ɵfac.js? [sm]:1
getNodeInjectable @ di.ts:626
createRootComponent @ component_ref.ts:389
create @ component_ref.ts:228
createComponent @ view_container_ref.ts:420
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-settings\dist\index.js:16226
timer @ zone.js:2355
invokeTask @ zone.js:402
onInvokeTask @ ng_zone.ts:408
invokeTask @ zone.js:401
runTask @ zone.js:171
invokeTask @ zone.js:483
ZoneTask.invoke @ zone.js:472
data.args.<computed> @ zone.js:2335
processImmediate @ node:internal/timers:466

error_handler.ts:45 ERROR TypeError: Cannot read properties of null (reading 'ssh:custom:capnrasp4gb:1a43fea7-ed09-4054-be2a-f76d668e09fb')
    at HotkeySettingsTabComponent.getHotkeys (C:\Program Files\Tabby\resources\builtin-plugins\tabby-settings\dist\index.js:10147:22)
    at HotkeySettingsTabComponent_ng_container_8_div_1_Template (template.html:12:29)
    at executeTemplate (shared.ts:496:5)
    at refreshView (shared.ts:369:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at detectChangesInternal (shared.ts:1768:5)
    at RootViewRef.detectChanges (view_ref.ts:321:5)
    at ApplicationRef.tick (application_ref.ts:1028:14)
    at application_ref.ts:785:16
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:127:43)
    at NgZone.run (ng_zone.ts:202:50)
    at Object.next (application_ref.ts:784:20)
`
    
**After that when I press on one of the terminal like if i was going to just continue with my terminal use this error just keeps appearing, i believe it is in a loop.**

`ERROR TypeError: Cannot read properties of null (reading 'ssh:custom:capnrasp4gb:1a43fea7-ed09-4054-be2a-f76d668e09fb')
    at HotkeySettingsTabComponent.getHotkeys (C:\Program Files\Tabby\resources\builtin-plugins\tabby-settings\dist\index.js:10147:22)
    at HotkeySettingsTabComponent_ng_container_8_div_1_Template (template.html:12:29)
    at executeTemplate (shared.ts:496:5)
    at refreshView (shared.ts:369:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at detectChangesInternal (shared.ts:1768:5)
    at RootViewRef.detectChanges (view_ref.ts:321:5)
    at ApplicationRef.tick (application_ref.ts:1028:14)
    at application_ref.ts:785:16
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:127:43)
    at NgZone.run (ng_zone.ts:202:50)
    at Object.next (application_ref.ts:784:20)
`

**This also appears when I'm pressing on another one of the settings sections.**

`error_handler.ts:45 ERROR TypeError: Cannot read properties of null (reading 'ssh:custom:capnrasp4gb:1a43fea7-ed09-4054-be2a-f76d668e09fb')
    at HotkeySettingsTabComponent.getHotkeys (C:\Program Files\Tabby\resources\builtin-plugins\tabby-settings\dist\index.js:10147:22)
    at HotkeySettingsTabComponent_ng_container_8_div_1_Template (template.html:12:29)
    at executeTemplate (shared.ts:496:5)
    at refreshView (shared.ts:369:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshComponent (shared.ts:1613:7)
    at refreshChildComponents (shared.ts:109:5)
    at refreshView (shared.ts:426:7)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at refreshEmbeddedViews (shared.ts:1563:9)
    at refreshView (shared.ts:396:5)
    at detectChangesInternal (shared.ts:1768:5)
    at ViewRef$1.detectChanges (view_ref.ts:272:5)
    at Object.next (nav-outlet.ts:102:14)
    at ConsumerObserver.next (Subscriber.ts:161:25)
    at Subscriber._next (Subscriber.ts:119:22)
    at Subscriber.next (Subscriber.ts:75:12)
    at filter.ts:72:109
    at OperatorSubscriber._this._next (OperatorSubscriber.ts:70:13)
    at Subscriber.next (Subscriber.ts:75:12)
    at distinctUntilChanged.ts:173:22
    at OperatorSubscriber._this._next (OperatorSubscriber.ts:70:13)
    at Subscriber.next (Subscriber.ts:75:12)
    at mergeInternals.ts:85:24
    at OperatorSubscriber._this._next (OperatorSubscriber.ts:70:13)
    at Subscriber.next (Subscriber.ts:75:12)
    at Subject.ts:68:20
    at Object.errorContext (errorContext.ts:29:5)
    at Subject.next (Subject.ts:61:5)
    at NgbNav._notifyItemChanged (nav.ts:407:23)
    at NgbNav._updateActiveId (nav.ts:401:10)
    at NgbNav.click (nav.ts:291:9)
    at NgbNavLink_click_HostBindingHandler (nav.ts:476:14)
    at executeListenerWithErrorHandling (listener.ts:224:12)
    at wrapListenerIn_markDirtyAndPreventDefault (listener.ts:261:18)
    at HTMLAnchorElement.<anonymous> (dom_renderer.ts:76:34)
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
`

**This is what I've been able to capture, it seems like it's some thing that is in a loop and continues after I've pressed on the hotkeys tab in the settings**

**Comment by CaptainFallaway** [comment]
Sorry for the absolute verboseness. I do not know how to properly debug js code and do not really what to look for either.

**Comment by z-impi** [comment]
I think i have the same issue. My custom shortcuts are not working. only the default ones. 
I switched toggle tabby window from strg+space to F12 and its not working. 
Other combinations also don't work. Posted this because i think its related. 
As stated the defaults are working.

**Comment by CaptainFallaway** [comment]
I have not really cared about this issue for a while, I might start digging again. It's just that It felt like a lone issue for a while.
