### ISSUE TITLE
Cannot select item from command selector

### ISSUE THREAD

**Issue by leodinas-hao** [Eugeny/tabby#8839]
Version: 1.0.197
Platform: Windows x64 10.0.22621
Plugins: none
Frontend: xterm-webgl

The way to produce the bug:
1. open the command selector: ctrl + shift + p
2. type in something not exists in any result (i.e. something random)
3. then type something exists (i.e. close)
4. try to navigate the results from the command selector, there is no focus

Thanks in advance.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by leodinas-hao** [comment]
Please find below logs relevant to the bug. Thanks.

```
index.html:1 
Autofocus processing was blocked because a document already has a focused element.

error_handler.ts:45 
ERROR TypeError: Cannot read properties of undefined (reading 'result')
    at SelectorModalComponent.selectOption (C:\Users\lhao\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19899:41)
    at SelectorModalComponent.onKeyUp (C:\Users\lhao\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:19852:18)
    at SelectorModalComponent_keydown_HostBindingHandler (template.html:0:0)
    at executeListenerWithErrorHandling (listener.ts:224:12)
    at wrapListenerIn_markDirtyAndPreventDefault (listener.ts:261:18)
    at HTMLElement.<anonymous> (dom_renderer.ts:76:34)
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:171:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:483:34)
    at invokeTask (zone.js:1631:18)
    at globalCallback (zone.js:1662:29)
    at HTMLElement.globalZoneAwareCallback (zone.js:1695:16)
    at HTMLElement.sentryWrapped (helpers.ts:87:17)

handleError @ error_handler.ts:45
handleError @ shared.ts:1872
executeListenerWithErrorHandling @ listener.ts:226
wrapListenerIn_markDirtyAndPreventDefault @ listener.ts:261
(anonymous) @ dom_renderer.ts:76
invokeTask @ zone.js:402
onInvokeTask @ ng_zone.ts:408
invokeTask @ zone.js:401
runTask @ zone.js:171
invokeTask @ zone.js:483
invokeTask @ zone.js:1631
globalCallback @ zone.js:1662
globalZoneAwareCallback @ zone.js:1695
sentryWrapped @ helpers.ts:87
```

**Comment by Clem-Fern** [comment]
Hi, I was able to reproduce. Expect a PR :)
