### ISSUE TITLE
innerError Error: Cannot find module '../build/Debug/pty.node'

### ISSUE THREAD

**Issue by sming256** [Eugeny/tabby#8905]
Environment details
OS version: Ubuntu 18.04
node version: 9.11.2
npm version: 5.6.0

```innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:2:117469)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}
```

**Comment by orazmyradov** [comment]
The error message you provided indicates that there is a missing module or package in your Node.js application running on Ubuntu 18.04. To resolve this issue, you can follow these steps:

1. **Check Your Node.js Version**: You are using Node.js version 9.11.2, which is quite outdated. Consider upgrading Node.js to a more recent and supported version. You can use a version manager like NVM (Node Version Manager) to easily manage Node.js versions.

   Install NVM (if not already installed):
   ```bash
   curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
   ```

   Install a newer version of Node.js:
   ```bash
   nvm install 14   # Example: Installing Node.js 14
   ```

   Then, switch to the new Node.js version:
   ```bash
   nvm use 14
   ```

2. **Remove `node_modules` and Reinstall Dependencies**: Navigate to your project directory and remove the `node_modules` folder and `package-lock.json` file if they exist. Then, reinstall your project's dependencies:

   ```bash
   rm -rf node_modules package-lock.json
   npm install
   ```

3. **Check for Missing Dependencies**: Review your project's `package.json` file and ensure that all required dependencies are listed. If you find any missing dependencies, add them to your `package.json` and run `npm install` again.

4. **Check for Correct Module Paths**: Make sure that your code and application are referencing modules using the correct paths. In your error message, it mentions `/opt/Tabby/resources/app.asar`, so ensure that the required modules are in that directory.

5. **Rebuild Native Modules (if needed)**: If your project uses native modules, you might need to rebuild them for your current Node.js version. You can do this with the following command:

   ```bash
   npm rebuild
   ```

6. **Run Your Application**: After making these changes, try running your application again to see if the issue is resolved:

   ```bash
   node your-app.js
   ```
Let me know how it goes

**Comment by evatosco** [comment]
Hi!

The exact same thing happened to me, but only right after I updated Tabby from version Alpha 201 to Alpha 204. The 201 version worked perfectly before.
I installed node and npm (apparently were not installed before, idk how Tabby worked then) but I couldn't find the right folder to install the dependencies. 
Btw, I checked  /opt/Tabby/resources/app.asar ; it's a file, not a folder, in my case. Size 55 Mb.

OS version: Ubuntu 22.04.3 LTS
node version: I tried to solve the problem, so I don't know the earlier version, but now I have v.21.2.0
npm version: Same as node, now it's v.10.2.3

Anyway, I opted for downgrading tabby. I uninstalled 204 and re-installed 201, nothing else. And it works again. I have no idea why.
It opens again. There's an error in the native terminal when running "tabby", but the interface opens!

I hope it helps! For more info, feel free to reach out! Cheers!
