### ISSUE TITLE
Passwords not being remembered

### ISSUE THREAD

**Issue by b0bh00d** [Eugeny/tabby#8928]
**Describe the problem**:
Tabby i snot remembering SSH password, even though I have told it to by enabling the "Remember" checkbox.  I am on Ubuntu 22.04 LTS, and I'm using Tabby v1.0.200.

**To Reproduce**:
I installed Tabby directly from the github project, and it imported "known" connections from the .ssh/ folder when I started it.  I opened the first, and it prompted me to enter the password.  I entered it, and checked the "Remember" checkbox.  I then told it to accept the fingerprint for the host, and it it connected.  When I connect to this same host using Tabby again, it still prompts me for a password.

I looked at the system keychain ("Passwords & Keys"), and I see no new entries.

**Comment by Eugeny** [comment]
Which DE are you using? Tabby uses `libsecret` to interface with secret managers, maybe yours doesn't support it or requires an adapter

**Comment by b0bh00d** [comment]
This is what I'm seeing from `apt list --installed | grep secret`:

> libsecret-1-0/jammy,now 0.20.5-2 amd64 [installed]
> libsecret-common/jammy,jammy,now 0.20.5-2 all [installed,automatic]

So, why isn't Tabby using it?

**Comment by b0bh00d** [comment]
I decided to take another run at this.  Installing Tabby on a clean Ubuntu 22.04 LTS (in a VM) works as expected.  It saves the password.  On my "live" Ubuntu 22.04 LTS system, with lots of other software already installed, it still fails to remember the passwords using the same steps.

I don't know if this is relevant to my issue, but I ran Tabby from the command line, and immediately got this message:

```
Error: Bad atom
    at ReadFixedRequest.callback (/opt/Tabby/resources/app.asar/node_modules/x11/lib/xcore.js:465:29)
    at ReadFixedRequest.execute (/opt/Tabby/resources/app.asar/node_modules/x11/lib/unpackstream.js:41:10)
    at UnpackStream.resume (/opt/Tabby/resources/app.asar/node_modules/x11/lib/unpackstream.js:165:30)
    at UnpackStream.write (/opt/Tabby/resources/app.asar/node_modules/x11/lib/unpackstream.js:102:10)
    at Socket.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/x11/lib/xcore.js:88:21)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10) {
  error: 5,
  seq: 10,
  badParam: 0,
  minorOpcode: 0,
  majorOpcode: 17
}
```
I checked `.config/tabby/log.txt`, and this message does not appear in there.  I checked /var/log/syslog, and the above error _does_ appear in there.

I'm finding nothing about errors accessing the key ring.

**Comment by sim4dim** [comment]
I am seeing the same behavior (not saving ssh password) on MacOS 13.5.2 running Tabby 1.0.2

**Comment by 4mig4** [comment]
I have the same problem on Ubuntu 24.04.4 LTS with Tabby 1.234 but only on certain sessions when I start from CLI I get this as well.

$ tabby --trace-deprecation
(node:16225) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
    at asarStatsToFsStats (node:electron/js2c/node_init:2:1796)
    at Object.t.lstatSync (node:electron/js2c/node_init:2:4883)
    at t.statSync (node:electron/js2c/node_init:2:5445)
    at Object.module.exports [as findUp] (/opt/Tabby/resources/app.asar/node_modules/escalade/sync/index.js:6:19)
    at te.[pkgUp] (/opt/Tabby/resources/app.asar/node_modules/yargs/build/index.cjs:1:48167)
    at te.[guessVersion] (/opt/Tabby/resources/app.asar/node_modules/yargs/build/index.cjs:1:47738)
    at te.version (/opt/Tabby/resources/app.asar/node_modules/yargs/build/index.cjs:1:44741)
    at yargs (/opt/Tabby/resources/app.asar/node_modules/yargs/build/index.cjs:1:62125)
    at createParserFromConfig (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/cli.ts:110:18)
    at t.parseArgs (/opt/Tabby/resources/app.asar/dist/webpack:/tabby/lib/cli.ts:131:20)
[16225:0521/102558.077913:ERROR:ui/gfx/x/atom_cache.cc:232] Add _NET_RESTACK_WINDOW to kAtomsToCache
Error: Bad atom
    at ReadFixedRequest.callback (/opt/Tabby/resources/app.asar/node_modules/x11/lib/xcore.js:465:29)
    at ReadFixedRequest.execute (/opt/Tabby/resources/app.asar/node_modules/x11/lib/unpackstream.js:41:10)
    at UnpackStream.resume (/opt/Tabby/resources/app.asar/node_modules/x11/lib/unpackstream.js:165:30)
    at UnpackStream.write (/opt/Tabby/resources/app.asar/node_modules/x11/lib/unpackstream.js:102:10)
    at Socket.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/x11/lib/xcore.js:88:21)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Socket.Readable.push (node:internal/streams/readable:392:5) {
  error: 5,
  seq: 10,
  badParam: 0,
  minorOpcode: 0,
  majorOpcode: 17
}
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Bad atom
    at ReadFixedRequest.callback (/opt/Tabby/resources/app.asar/node_modules/x11/lib/xcore.js:465:29)
    at ReadFixedRequest.execute (/opt/Tabby/resources/app.asar/node_modules/x11/lib/unpackstream.js:41:10)
    at UnpackStream.resume (/opt/Tabby/resources/app.asar/node_modules/x11/lib/unpackstream.js:165:30)
    at UnpackStream.write (/opt/Tabby/resources/app.asar/node_modules/x11/lib/unpackstream.js:102:10)
    at Socket.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/x11/lib/xcore.js:88:21)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Socket.Readable.push (node:internal/streams/readable:392:5)
