### ISSUE TITLE
Issue after update on ubuntu 22.04

### ISSUE THREAD

**Issue by DIGIVOIP** [Eugeny/tabby#9235]
Nov 15 13:26:56    ubuntu systemd[2367]: Started Application launched by gnome-shell.
Nov 15 13:26:57    ubuntu tabby.desktop[8609]: innerError Error: Cannot find module '../build/Debug/pty.node'
Nov 15 13:26:57    ubuntu tabby.desktop[8609]: Require stack:
Nov 15 13:26:57    ubuntu tabby.desktop[8609]: - /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
Nov 15 13:26:57    ubuntu tabby.desktop[8609]: - /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js
Nov 15 13:26:57    ubuntu tabby.desktop[8609]: - /opt/Tabby/resources/app.asar/dist/main.js
Nov 15 13:26:57    ubuntu tabby.desktop[8609]: -
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at Function.n._resolveFilename (node:electron/js2c/browser_init:2:117760)
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at Module._load (node:internal/modules/cjs/loader:927:27)
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at Module.require (node:internal/modules/cjs/loader:1148:19)
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:34:15)
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     at Module.load (node:internal/modules/cjs/loader:1124:32) {
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:   code: 'MODULE_NOT_FOUND',
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:   requireStack: [
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js',
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     '/opt/Tabby/resources/app.asar/dist/main.js',
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:     undefined
Nov 15 13:26:57    ubuntu tabby.desktop[8609]:   ]
Nov 15 13:26:57    ubuntu tabby.desktop[8609]: }

**Comment by zygfrydw** [comment]
After installing tabby-1.0.204-linux-x64.deb on Ubuntu 22.04 tabby does not start at all. 
The message is:
```
➜  ~ tabby
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:2:117760)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}
```

**Comment by luisnovoc** [comment]
Same on Mint 21.2 (no surprises there)

**Comment by TheBlueKnight42** [comment]
Chiming in, same on KDE-based Kubuntu 23.10 after update to Tabby 204. No longer able to install any version (when I tried to roll back). Apt reports unmet dependencies.

```
The following packages have unmet dependencies:
 tabby-terminal : Depends: gconf2 but it is not installable
                  Depends: gconf-service but it is not installable
```

**Comment by Clem-Fern** [comment]
Got the same problem. It seems to be a problem with all linux platform.

 Log while trying to run tabby locally:
```
yarn run v1.22.19
$ cross-env TABBY_DEV=1 electron app -d --inspect --no-sandbox
Debugger listening on ws://127.0.0.1:9229/3b374d9b-5216-45fd-b9d5-7239823f27e7
For help, see: https://nodejs.org/en/docs/inspector
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /home/clem/DEV/git/tabby/app/node_modules/node-pty/lib/unixTerminal.js
- /home/clem/DEV/git/tabby/app/node_modules/node-pty/lib/index.js
- /home/clem/DEV/git/tabby/app/dist/main.js
- /home/clem/DEV/git/tabby/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:2:117760)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (/home/clem/DEV/git/tabby/app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/clem/DEV/git/tabby/app/node_modules/node-pty/src/unixTerminal.ts:20:11)
    at Module._compile (/home/clem/DEV/git/tabby/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/clem/DEV/git/tabby/app/node_modules/node-pty/lib/unixTerminal.js',
    '/home/clem/DEV/git/tabby/app/node_modules/node-pty/lib/index.js',
    '/home/clem/DEV/git/tabby/app/dist/main.js',
    '/home/clem/DEV/git/tabby/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
App threw an error during load
Error: The module '/home/clem/DEV/git/tabby/app/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 116. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1869)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1869)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (/home/clem/DEV/git/tabby/app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/clem/DEV/git/tabby/app/node_modules/node-pty/src/unixTerminal.ts:16:9)
    at Module._compile (/home/clem/DEV/git/tabby/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: The module '/home/clem/DEV/git/tabby/app/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 116. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1869)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1869)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (/home/clem/DEV/git/tabby/app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/clem/DEV/git/tabby/app/node_modules/node-pty/src/unixTerminal.ts:16:9)
    at Module._compile (/home/clem/DEV/git/tabby/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
libva error: vaGetDriverNames() failed with unknown libva error
```

**Comment by CreeperLKF** [comment]
Same problem for AppImage on Ubuntu 22.04.

**Comment by tinywolf3** [comment]
Same problem on ubuntu 22.04.
I downgraded to alpha 201 and it runs fine.

**Comment by blizzrdof77** [comment]
Same issue on Debian 12. My stacktrace when running it from the terminal is below:

```innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:2:117760)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}
[68824:1116/041841.666574:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
```

**Comment by duzhuoshanwai** [comment]
Same on me , try downgrade to 1.0.201

**Comment by qs5779** [comment]
same on popos 22.04, downgraded to 1.0.201 works for me.

**Comment by stefangweichinger** [comment]
Fedora 39: me too

**Comment by SmollClover** [comment]
I think it's safe to say that it's broken on Linux in general, so just people saying that it's broken for them too on Linux Distro XYZ is a bit redundant.
At this point, I think we just have to wait for #9238

**Comment by akshaybharwani** [comment]
Similar to #5777

**Comment by mfsiat** [comment]
Is there any fix for this?
