### ISSUE TITLE
Tabby execute failed

### ISSUE THREAD

**Issue by wangxufeng** [Eugeny/tabby#9242]
Version: 204
Platform: Manjora Linux

LOG:
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:2:117760)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}
MESA-INTEL: warning: Haswell Vulkan support is incomplete

**Comment by Warmachine13** [comment]
same here on pop-os 

`innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:2:117760)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}
`


 Alpha 204 Debian version

**Comment by demanuPL** [comment]
On Fedora I have the same issue, I've to downgrade to 1.0.202 and its working fine

**Comment by eclipse0922** [comment]
same issue on  Kubuntu 22.04.3

**Comment by Yusuf-R** [comment]
same issue on Ubuntu 22.04
