### ISSUE TITLE
Failed to execute from Ubuntu 22.04

### ISSUE THREAD

**Issue by jason19970210** [Eugeny/tabby#9245]
**Describe the problem**:
After update from Alpha 201 to Alpha 204, tabby cannot be execute from terminal & deskop.

**To Reproduce**:
[Steps to reproduce the behavior]

**Output**
```
OS: Ubuntu 22.04.3 LTS
```

```
user@ubuntu-pc:~$ tabby
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:2:117760)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}
[118992:1117/144551.577287:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
```

**Comment by mullerch** [comment]
Fails the same way for me with Ubuntu 23.10

**Comment by timur-g** [comment]
Please stop installing until fixed.
