### ISSUE TITLE
Tabs no longer restored

### ISSUE THREAD

**Issue by francisdb** [Eugeny/tabby#9267]
I had the issue where tabby won't start, that was fixed with `1.0.205` (#9245) but now my tabs are no longer restored. Tried overwriting the config with the default one but did not help.

**To Reproduce**:

1. open tab
2. do some actions
3. open second tab
4. close tabby
5. start tabby
6. single empty tab visible

Below logs on startup might be related?

```
➜  ~ tabby
[37373:1122/174556.945651:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
Error: Bad atom
    at ReadFixedRequest.callback (/opt/Tabby/resources/app.asar/node_modules/x11/lib/xcore.js:465:29)
    at ReadFixedRequest.execute (/opt/Tabby/resources/app.asar/node_modules/x11/lib/unpackstream.js:41:10)
    at UnpackStream.resume (/opt/Tabby/resources/app.asar/node_modules/x11/lib/unpackstream.js:165:30)
    at UnpackStream.write (/opt/Tabby/resources/app.asar/node_modules/x11/lib/unpackstream.js:102:10)
    at Socket.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/x11/lib/xcore.js:88:21)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.push (node:internal/streams/readable:234:10) {
  error: 5,
  seq: 10,
  badParam: 0,
  minorOpcode: 0,
  majorOpcode: 17
}
[37373:1122/174600.056623:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
```

Ubuntu 23.10 / Wayland / Gnome / AMD Radeon
Installed through apt repo

**Comment by francisdb** [comment]
Looks like this was fixed by a restart, probably some leftover tabby process causing havoc?
