### ISSUE TITLE
I can't install plugins

### ISSUE THREAD

**Issue by line521356** [Eugeny/tabby#9441]
**Describe the problem**:
[When I installed the plugin, a message popped up saying "Error in xxx, [object, object]". When I entered debugging mode, I found that the error message was "FetchError: request to" https://registry.npm.taobao.org/terminus-altair "Failed, reason: certificate has expired".]

**Comment by fatihusta** [comment]
+1

```
wget https://registry.npm.taobao.org/state-local/download/state-local-1.0.7.tgz
--2024-02-02 20:23:12--  https://registry.npm.taobao.org/state-local/download/state-local-1.0.7.tgz
Resolving registry.npm.taobao.org (registry.npm.taobao.org)... 163.181.56.214, 163.181.56.215, 163.181.56.216, ...
Connecting to registry.npm.taobao.org (registry.npm.taobao.org)|163.181.56.214|:443... connected.
ERROR: cannot verify registry.npm.taobao.org's certificate, issued by 'CN=GlobalSign Organization Validation CA - SHA256 - G2,O=GlobalSign nv-sa,C=BE':
  Issued certificate has expired.
To connect to registry.npm.taobao.org insecurely, use `--no-check-certificate'.
```

**Comment by asd2494375445** [comment]
+1
![image](https://github.com/Eugeny/tabby/assets/56380283/d99f9e66-3173-4e60-b4d1-1357162b75e4)

**Comment by L-Super** [comment]
![image](https://github.com/Eugeny/tabby/assets/40905056/c0600b27-39cb-46ef-ac29-c8092f96ba87)

Me too

**Comment by tyh97** [comment]
![图片](https://github.com/Eugeny/tabby/assets/34681937/e7eb94b5-245e-4cb7-a452-dc7316c37f73)
me too

**Comment by tyh97** [comment]
找到问题了，将npm源还原下就可以了

npm config set registry https://registry.npmjs.org/

**Comment by L-Super** [comment]
> 找到问题了，将npm源还原下就可以了
> 
> npm config set registry https://registry.npmjs.org/
> 
> 

👍

**Comment by fatihusta** [comment]
> 找到问题了，将npm源还原下就可以了
> 
> npm config set registry https://registry.npmjs.org/

I tried this `npm config set registry https://registry.npmjs.org`
And `yarn config set registry https://registry.npmjs.org/`

But not worked.

```
yarn install --ignore-scripts
yarn install v1.22.21
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I set `yarn config set "strict-ssl" false -g` it worked but this is not secure.

How can I fix this. Also what is going on registry.npm.taobao.org web site. Why certificate not updating?

**Comment by yanhao-1420** [comment]
我也遇到了同样的问题，不过关掉代理就好了。

**Comment by ming-cmyk** [comment]
![Image](https://github.com/user-attachments/assets/906e513d-5a39-4930-985d-3b38629fb883)
quick-cmds install fail
