### ISSUE TITLE
Problem launching Tabby: terminal auto-open does not work

### ISSUE THREAD

**Issue by justc0de-it** [Eugeny/tabby#9631]
**Describe the problem**:
At the set point, the handle starts the terminal when starting the program. Over the past months, I began to notice that after launching the program, a new tab does not open immediately, but after some time it slows down, so to speak. At this moment, the context menu is not available when you press RMB and you cannot use profiles to connect; only the menu button works. I launched Tabby through the terminal and it gave the following error:

Error: Bad atom
    at ReadFixedRequest.callback (/opt/Tabby/resources/app.asar/node_modules/x11/lib/xcore.js:465:29)
    at ReadFixedRequest.execute (/opt/Tabby/resources/app.asar/node_modules/x11/lib/unpackstream.js:41:10)
    at UnpackStream.resume (/opt/Tabby/resources/app.asar/node_modules/x11/lib/unpackstream.js:165:30)
    at UnpackStream.write (/opt/Tabby/resources/app.asar/node_modules/x11/lib/unpackstream.js:102:10)
    at Socket.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/x11/lib/xcore.js:88:21)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.push (node:internal/streams/readable:234:10) {
  error: 5,
  seq: 10,
  badParam: 0,

  minorOpcode: 0,
  majorOpcode: 17
}

The problem is observed in GNOME (X11, Wayland). I'll attach a video demonstration of what it looks like. No third party modules installed.

https://github.com/Eugeny/tabby/assets/30393784/9dfd866d-4707-4488-b67a-4e8b924cfeb3

**To Reproduce**:
1. Install Tabby on GNOME
2. Start Tabby

**Comment by kubealex** [comment]
Still an issue, also on Fedora 40

**Comment by Chealer** [comment]
@justc0de-it wrote:
> At this moment, the context menu is not available when you press RMB and you cannot use profiles to connect; only the menu button works.

I believe he refers to the secondary (right) mouse button.

Alexander, please see [that checklist](https://blog.michael.gr/post/2014-11-bug-reporting-checklist/), in particular sections 8 to 13. Unfortunately, I understand little from the screencast.

@justc0de-it wrote:

> At the set point, the handle starts the terminal when starting the program.

I do not understand that sentence.
