### ISSUE TITLE
The ssh putty agent is not forwarding the keys!

### ISSUE THREAD

**Issue by sergioguedes** [Eugeny/tabby#9780]
Version: 1.0.209
Platform: Windows x64 10.0.18363
Plugins: none
Frontend: xterm-webgl

Hello, I downloaded Version: 1.0.209 portable, but I think the putty keys forward agent is not working because when I ssh it asks me for a password! The keys are ok, but they work well in Putty.
Now is there any place where I can check the configuration of the forward agent keys?
Thanks

**Comment by SanderFlooris** [comment]
I'm also having issues with my 1Password SSH agent on MacOS, it doesn't seem like it actually talks to the agent, as 1Password doesn't show the confirmation dialog to approve the key request.

If I use SSH in iTerm, it does work properly.

**Comment by Mikrz** [comment]
I'm having the same issue with 1Password's forwarded agent. Initial login to a remote ssh session with the agent works fine, but any subsequent use of the *forwarded* agent fails. It seems Tabby is destroying the agent internally somehow:

```
Unhandled Promise rejection: Object has been destructed ; Zone: <root> ; Task: null ; Value: Error: Object has been destructed
    at SSHAgentStream.assertNotDestructed (C:\Program Files\Tab…ib\helpers.js:16:19)
    at SSHAgentStream.<anonymous> (C:\Program Files\Tab…\lib\agent.js:71:18)
    at Generator.next (<anonymous>)
    at C:\Program Files\Tab…\lib\agent.js:31:71
    at new ZoneAwarePromise (zone.js:1411:21)
    at __awaiter (C:\Program Files\Tab…\lib\agent.js:27:12)
    at SSHAgentStream.close (C:\Program Files\Tab…\lib\agent.js:70:16)
    at Object.next (C:\Program Files\Tab…st\index.js:8403:55)
    at ConsumerObserver.next (Subscriber.ts:161:25)
    at Subscriber._next (Subscriber.ts:119:22)
    at Subscriber.next (Subscriber.ts:75:12)
    at map.ts:58:20
    at OperatorSubscriber._this._next (OperatorSubscriber.ts:70:13)
    at Subscriber.next (Subscriber.ts:75:12)
    at filter.ts:72:109
    at OperatorSubscriber._this._next (OperatorSubscriber.ts:70:13)
    at Subscriber.next (Subscriber.ts:75:12)
    at Subject.ts:68:20
    at Object.errorContext (errorContext.ts:29:5)
    at Subject.next (Subject.ts:61:5)
    at ClientEventInterface.closeCallback (C:\Program Files\Tab…lib\events.js:26:25) Error: Object has been destructed
    at SSHAgentStream.assertNotDestructed (C:\Program Files\Tabby\resources\app.asar\node_modules\russh\lib\helpers.js:16:19)
    at SSHAgentStream.<anonymous> (C:\Program Files\Tabby\resources\app.asar\node_modules\russh\lib\agent.js:71:18)
    at Generator.next (<anonymous>)
    at C:\Program Files\Tabby\resources\app.asar\node_modules\russh\lib\agent.js:31:71
    at new ZoneAwarePromise (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:22931:21)
    at __awaiter (C:\Program Files\Tabby\resources\app.asar\node_modules\russh\lib\agent.js:27:12)
    at SSHAgentStream.close (C:\Program Files\Tabby\resources\app.asar\node_modules\russh\lib\agent.js:70:16)
    at Object.next (C:\Program Files\Tabby\resources\builtin-plugins\tabby-ssh\dist\index.js:8403:55)
    at ConsumerObserver.next (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:3533:25)
    at Subscriber._next (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:3502:22)
    at Subscriber.next (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:3475:12)
    at file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:7639:18
    at OperatorSubscriber._this._next (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:5741:9)
    at Subscriber.next (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:3475:12)
    at file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:7269:68
    at OperatorSubscriber._this._next (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:5741:9)
    at Subscriber.next (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:3475:12)
    at file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:3280:22
    at Object.errorContext (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:12643:5)
    at Subject.next (file:///C:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:3270:20)
    at ClientEventInterface.closeCallback (C:\Program Files\Tabby\resources\app.asar\node_modules\russh\lib\events.js:26:25)
api.onUnhandledError	@	zone.js:1043
```
