### ISSUE TITLE
Impossible to build, at least on an M2 Mac (Sonoma 14.6), at cpu_features

### ISSUE THREAD

**Issue by andylaw** [Eugeny/tabby#9857]
**Describe the problem**:
A clean cloned copy of the repository will not build when following the instructions in HACKING.md on my Macbook Pro Sonoma 14.6

**To Reproduce**:
On a clean development machine, download the source code repository, install Node (I used nvm) and then install yarn into that Node environment. From inside the tabby directory, run `yarn`

***Expected behaviour***
Yarn should install all the dependencies

***Actual behaviour***
The process fails due to the cpu_features module not building

```
********: ********$ yarn
yarn install v1.22.22
warning ../../package.json: No license field
[1/4] 🔍  Resolving packages...
warning Resolution field "nan@2.17.0" is incompatible with requested version "nan@^2.18.0"
warning Resolution field "nan@2.17.0" is incompatible with requested version "nan@^2.19.0"
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @angular/localize@15.2.10" has incorrect peer dependency "@angular/compiler@15.2.10".
warning " > @angular/localize@15.2.10" has incorrect peer dependency "@angular/compiler-cli@15.2.10".
warning " > babel-loader@9.1.2" has unmet peer dependency "@babel/core@^7.12.0".
warning " > pug-loader@2.4.0" has incorrect peer dependency "pug@^2.0.0".
warning " > typedoc@0.22.18" has incorrect peer dependency "typescript@4.0.x || 4.1.x || 4.2.x || 4.3.x || 4.4.x || 4.5.x || 4.6.x || 4.7.x".
warning abbrev@1.1.0: Invalid bin field for "abbrev".
warning ansicolors@0.3.2: Invalid bin field for "ansicolors".
warning ansistyles@0.1.3: Invalid bin field for "ansistyles".
warning archy@1.0.0: Invalid bin field for "archy".
warning call-limit@1.1.0: Invalid bin field for "call-limit".
warning bluebird@3.5.0: Invalid bin field for "bluebird".
warning chownr@1.0.1: Invalid bin field for "chownr".
warning cmd-shim@2.0.2: Invalid bin field for "cmd-shim".
warning columnify@1.5.4: Invalid bin field for "columnify".
warning config-chain@1.1.11: Invalid bin field for "config-chain".
warning debuglog@1.0.1: Invalid bin field for "debuglog".
warning detect-indent@5.0.0: Invalid bin field for "detect-indent".
warning dezalgo@1.0.3: Invalid bin field for "dezalgo".
warning editor@1.0.0: Invalid bin field for "editor".
warning fs-vacuum@1.2.10: Invalid bin field for "fs-vacuum".
warning fs-write-stream-atomic@1.0.10: Invalid bin field for "fs-write-stream-atomic".
warning fstream@1.0.11: Invalid bin field for "fstream".
warning graceful-fs@4.1.11: Invalid bin field for "graceful-fs".
warning has-unicode@2.0.1: Invalid bin field for "has-unicode".
warning iferr@0.1.5: Invalid bin field for "iferr".
warning imurmurhash@0.1.4: Invalid bin field for "imurmurhash".
warning inflight@1.0.6: Invalid bin field for "inflight".
warning inherits@2.0.3: Invalid bin field for "inherits".
warning ini@1.3.4: Invalid bin field for "ini".
warning init-package-json@1.10.1: Invalid bin field for "init-package-json".
warning lazy-property@1.0.0: Invalid bin field for "lazy-property".
warning lockfile@1.0.3: Invalid bin field for "lockfile".
warning lodash._baseindexof@3.1.0: Invalid bin field for "lodash._baseindexof".
warning lodash._baseuniq@4.6.0: Invalid bin field for "lodash._baseuniq".
warning lodash._bindcallback@3.0.1: Invalid bin field for "lodash._bindcallback".
warning lodash._cacheindexof@3.0.2: Invalid bin field for "lodash._cacheindexof".
warning lodash._createcache@3.1.2: Invalid bin field for "lodash._createcache".
warning lodash._getnative@3.9.1: Invalid bin field for "lodash._getnative".
warning lodash.clonedeep@4.5.0: Invalid bin field for "lodash.clonedeep".
warning lodash.restparam@3.6.1: Invalid bin field for "lodash.restparam".
warning lodash.union@4.6.0: Invalid bin field for "lodash.union".
warning lodash.uniq@4.5.0: Invalid bin field for "lodash.uniq".
warning lodash.without@4.4.0: Invalid bin field for "lodash.without".
warning mississippi@1.3.0: Invalid bin field for "mississippi".
warning move-concurrently@1.0.1: Invalid bin field for "move-concurrently".
warning npm-cache-filename@1.0.2: Invalid bin field for "npm-cache-filename".
warning npm-install-checks@3.0.0: Invalid bin field for "npm-install-checks".
warning once@1.4.0: Invalid bin field for "once".
warning osenv@0.1.4: Invalid bin field for "osenv".
warning path-is-inside@1.0.2: Invalid bin field for "path-is-inside".
warning promise-inflight@1.0.1: Invalid bin field for "promise-inflight".
warning read@1.0.7: Invalid bin field for "read".
warning read-cmd-shim@1.0.1: Invalid bin field for "read-cmd-shim".
warning read-installed@4.0.3: Invalid bin field for "read-installed".
warning readdir-scoped-modules@1.0.2: Invalid bin field for "readdir-scoped-modules".
warning retry@0.10.1: Invalid bin field for "retry".
warning sha@2.0.1: Invalid bin field for "sha".
warning slide@1.1.6: Invalid bin field for "slide".
warning sorted-object@2.0.1: Invalid bin field for "sorted-object".
warning sorted-union-stream@2.1.3: Invalid bin field for "sorted-union-stream".
warning tar@2.2.1: Invalid bin field for "tar".
warning text-table@0.2.0: Invalid bin field for "text-table".
warning uid-number@0.0.6: Invalid bin field for "uid-number".
warning umask@1.1.0: Invalid bin field for "umask".
warning unique-filename@1.1.0: Invalid bin field for "unique-filename".
warning unpipe@1.0.0: Invalid bin field for "unpipe".
warning validate-npm-package-license@3.0.1: Invalid bin field for "validate-npm-package-license".
warning validate-npm-package-name@3.0.0: Invalid bin field for "validate-npm-package-name".
warning wrappy@1.0.2: Invalid bin field for "wrappy".
[4/4] 🔨  Building fresh packages...
[-/9] ⠠ waiting...
[-/9] ⠠ waiting...
[-/9] ⠠ waiting...
[8/9] ⠠ cpu-features
warning Error running install script for optional dependency: "/Users/********/tabby-source/node_modules/cpu-features: Command failed.
Exit code: 1
Command: node buildcheck.js > buildcheck.gypi && node-gyp rebuild
Arguments: 
Directory: /Users/********/tabby-source/node_modules/cpu-features
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@22.6.0 | darwin | arm64
gyp info find Python using Python version 3.10.13 found at \"/Users/********/******/bin/python3\"

gyp info spawn /Users/********/******/bin/python3
gyp info spawn args [
gyp info spawn args '/Users/********/.nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/Users/********/tabby-source/node_modules/cpu-features/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/Users/********/.nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/Users/********/Library/Caches/node-gyp/22.6.0/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/Users/********/Library/Caches/node-gyp/22.6.0',
gyp info spawn args '-Dnode_gyp_dir=/Users/********/.nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/Users/********/Library/Caches/node-gyp/22.6.0/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/Users/********/tabby-source/node_modules/cpu-features',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_aarch64_linux_or_android.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_aarch64_macos_or_iphone.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_aarch64_windows.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_arm_linux_or_android.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_mips_linux_or_android.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_ppc_linux.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_x86_freebsd.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_x86_linux_or_android.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_x86_macos.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_x86_windows.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/filesystem.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/stack_line_reader.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/string_view.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/hwcaps.o
  LIBTOOL-STATIC Release/cpu_features.a
  CXX(target) Release/obj.target/cpufeatures/src/binding.o
In file included from ../src/binding.cc:3:
../../nan/nan.h:2546:8: error: no matching member function for call to 'SetAccessor'
  tpl->SetAccessor(
  ~~~~~^~~~~~~~~~~
/Users/********/Library/Caches/node-gyp/22.6.0/include/node/v8-template.h:1055:8: note: candidate function not viable: no known conversion from 'v8::AccessControl' to 'PropertyAttribute' for 5th argument
  void SetAccessor(
       ^
/Users/********/Library/Caches/node-gyp/22.6.0/include/node/v8-template.h:1049:8: note: candidate function not viable: no known conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'AccessorGetterCallback' (aka 'void (*)(Local<String>, const PropertyCallbackInfo<Value> &)') for 2nd argument
  void SetAccessor(
       ^
In file included from ../src/binding.cc:3:
../../nan/nan.h:2592:8: error: no matching member function for call to 'SetAccessor'
  tpl->SetAccessor(
  ~~~~~^~~~~~~~~~~
/Users/********/Library/Caches/node-gyp/22.6.0/include/node/v8-template.h:1055:8: note: candidate function not viable: no known conversion from 'v8::AccessControl' to 'PropertyAttribute' for 5th argument
  void SetAccessor(
       ^
/Users/********/Library/Caches/node-gyp/22.6.0/include/node/v8-template.h:1049:8: note: candidate function not viable: no known conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'AccessorGetterCallback' (aka 'void (*)(Local<String>, const PropertyCallbackInfo<Value> &)') for 2nd argument
  void SetAccessor(
       ^
In file included from ../src/binding.cc:1:
In file included from /Users/********/Library/Caches/node-gyp/22.6.0/include/node/node.h:73:
In file included from /Users/********/Library/Caches/node-gyp/22.6.0/include/node/v8.h:24:
In file included from /Users/********/Library/Caches/node-gyp/22.6.0/include/node/v8-array-buffer.h:12:
/Users/********/Library/Caches/node-gyp/22.6.0/include/node/v8-local-handle.h:269:5: error: static assertion failed due to requirement 'std::is_base_of<v8::Value, v8::Data>::value': type check
    static_assert(std::is_base_of<T, S>::value, \"type check\");
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan_callbacks_12_inl.h:175:20: note: in instantiation of function template specialization 'v8::Local<v8::Value>::Local<v8::Data>' requested here
      cbinfo(info, obj->GetInternalField(kDataIndex));
                   ^
3 errors generated.
make: *** [Release/obj.target/cpufeatures/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (/Users/********/.nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
gyp ERR! System Darwin 23.6.0
gyp ERR! command \"/Users/********/.nvm/versions/node/v22.6.0/bin/node\" \"/Users/********/.nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/********/tabby-source/node_modules/cpu-features
$ patch-package && node ./scripts/install-deps.mjs && node ./scripts/build-native.mjs
patch-package 6.4.7
Applying patches...
app-builder-lib@24.6.4 ✔
ssh2@1.11.0 ✔

Warning: patch-package detected a patch file version mismatch

  Don't worry! This is probably fine. The patch was still applied
  successfully. Here's the deets:

  Patch file created for

    ssh2@1.11.0

  applied to

    ssh2@1.15.0
  
  At path
  
    node_modules/ssh2

  This warning is just to give you a heads-up. There is a small chance of
  breakage even though the patch was applied successfully. Make sure the package
  still behaves like you expect (you wrote tests, right?) and then run

    patch-package ssh2

  to update the version in the patch file name and make this warning go away.

---
patch-package finished with 1 warning(s).
fatal: No names found, cannot describe anything.
node:internal/errors:983
  const err = new Error(message);
              ^

Error: Command failed: git describe --tags
fatal: No names found, cannot describe anything.

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:890:11)
    at Module.execSync (node:child_process:962:15)
    at file:///Users/********/tabby-source/scripts/vars.mjs:13:35
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:482:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5) {
  status: 128,
  signal: null,
  output: [ null, '', 'fatal: No names found, cannot describe anything.\n' ],
  pid: 21636,
  stdout: '',
  stderr: 'fatal: No names found, cannot describe anything.\n'
}

Node.js v22.6.0
error Command failed with exit code 1.

```

**Comment by Eugeny** [comment]
Hi, none of these are actually important (cpu-features is not used and is removed before packaging the app, and the patch still applies, although it could be renamed). However patch-package is crashing for you for some reason. I suspect it expects to find at least some git tags in the repo, and if you cloned without them, you can run `git fetch --tags` to get them

**Comment by andylaw** [comment]
OK. Thanks.

You were right about the tags - I'd forked and then cloned and the forked copy didn't have tags. Cloning direct from the original repository does get past the error.

Apologies for wasting your time
